### ISSUE TITLE
Add "Last updated" to Programmer's Guide page(s)

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#10181]
## Problem statement

The implementation of the API Programmer's Guide is missing the "Last updated" section on each of these pages:
- Getting started
- Data model
- Responses from ReportStream
- Sample payloads and output

The "Last updated" text should be added on those pages to build trust with our users that the information is up-to-date and accurate. 

## What you need to know

- Reference the [Figma prototype](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?type=design&node-id=4812-37084&t=Ws7K90DouxjLKQED-9&scaling=min-zoom&page-id=3592%3A36210&starting-point-node-id=4812%3A37084&show-proto-sidebar=1) for styling

## Acceptance criteria

`Getting started` page includes "Last updated" section
- [ ] `Data model` page includes "Last updated" section
- [ ] `Responses from ReportStream` page includes "Last updated" section
- [ ] `Sample payloads and output` page includes "Last updated" section

## To do

- [ ] ...
