### ISSUE TITLE
Create App Insights Tracking and Visualization for Public Key Tool

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#10359]
## Problem statement

As a ReportStream team member (and PM), I would like to know how the Public Key Tool is being used and determine if our end users are receiving any errors.

## What you need to know
The Public Key Tool was released by the WebX team in Q2 of 2023 and is only available to logged in users.
- [Public Key Tool](https://reportstream.cdc.gov/resources/manage-public-key)
- [Product Brief](https://docs.google.com/document/d/1Wij98IgwWv0P4GfSxKa9T_Pe9EnQzNEuDLHyeqqEPoM/edit)

The items that would be useful to track are:
- When file submission occurs
- If an error occurred
- What error occurred

## Acceptance criteria
- [x] The following data points tracked in App Insights with the associated Session ID:
  - [x] File submission
  - [x] If error occurs, what error was sent to the user
- [x] A table visualization in App Insights Dashboard for all File submission using the Public Key tool showing at least:
  - [x] Time, Session ID, memberType, username, File Submission occurred, which error was received (or indication that no errors were received and upload was a success)
- [x] Test to ensure tracking appropriately
- [x] Review with PM (Chris Kuryak) before closing

## To do

- [ ] ...

**Comment by penny-lischer** [comment]
//Public Key Upload Events
let usg_events = dynamic(["Public Key"]);
let mainTable = union customEvents
    | where timestamp > ago(3h)
    | where isempty(operation_SyntheticSource)
    | extend name =replace("\n", "", name)
    | extend name =replace("\r", "", name)
    | where '*' in (usg_events) or name in (usg_events)
    | where isnotempty(customDimensions["fileUpload"])
    | extend ActiveMembership = todynamic(tostring(customDimensions["activeMembership"]))
    | evaluate bag_unpack(ActiveMembership)
    | extend fileUpload = todynamic(tostring(customDimensions["fileUpload"]))
    | evaluate bag_unpack(fileUpload);
let queryTable = mainTable
| order by timestamp desc 
| project
    ["Date"] = timestamp,
    ["Organization Name"] = parsedName,
    ["Session ID"] = session_Id,
    ["User ID"] = iif(isempty(user_AuthenticatedId), "<undefined>", user_AuthenticatedId),
    ["Member Type"] = memberType,
    ["Status"] = iif(isempty(status), "<undefined>", status),
    ["File Name"] = fileName,
    ["File type"] = fileType,
    ["File size"] = fileSize,
    ["Sender"] = sender,
    ["Service"] = service;
queryTable

**Comment by chris-kuryak** [comment]
Looks good via our screenshare! Thanks!
