### ISSUE TITLE
HL7-FHIR-HL7 ORU-R01 Mapping

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#11655]
### User Story
As ReportStream, I should implement the complete HL7 [HL7v2 -> FHIR Mapping inventory](https://docs.google.com/spreadsheets/d/1PaFYPSSq4oplTvw_4OgOn6h2Bs_CMvCAU9CqC4tPBgk/edit#gid=0) FOR BOTH DIRECTIONS ( HL7v2 -> FHIR and FHIR -> HL7v2) **for all datatype mappings that are used by ORU-R01 segments** so that I can then create mappings for ORU-R01 segments alongside other team members without having to worry about overwriting datatype mappings.

### Description/Use Case

The DataType tab of the [mapping spreadsheet ](https://docs.google.com/spreadsheets/d/1PaFYPSSq4oplTvw_4OgOn6h2Bs_CMvCAU9CqC4tPBgk/edit#gid=1419236962) indicates all the possible HL7v2 -> FHIR data type mappings. RS presently maps some of these, but some are incomplete or do not exactly match the spreadsheet, and some may be missing altogether. The strategy of this epic is to define each mapping (like HD -> Organization) in its own mapping file so that they can be easily reused in the mapping files that deal with mapping HL7v2 segment to FHIR  and FHIR to HL7v2 segments.

> NOTE: This epic involves creating or updating the HL7v2 -> FHIR mappings AND the FHIR -> HL7v2 mappings.

The following is a list that describes all the mappings that are referenced by ORU-R01 segments in the mapping spreadsheet where:

Level 1: The HL7v2 DataType
Level 2: The FHIR DataType the HL7v2 DataType can potentially map to
Level 3: What segment(s) a particular mapping is found in the mapping inventory

NOTE: This list was auto-generated by crawling through all the ORU-R01 mapping inventory segment files but some fields, like CWE and HD, were manually verified.
```md
- [ ] EI
    - [ ] Identifier
        - [ ] OBR[ServiceRequest]-OBR-2
        - [ ] OBR[ServiceRequest]-OBR-3
        - [ ] SPM[Specimen]-SPM-32
        - [ ] OBX[Observation-Component]-OBX-18
        - [ ] OBX[Observation-Component]-OBX-21
        - [ ] OBR[DiagnosticReport]-OBR-2
        - [ ] OBR[DiagnosticReport]-OBR-3
        - [ ] PRT[Device]-PRT-10
        - [ ] ORC[ServiceRequest]-ORC-2
        - [ ] ORC[ServiceRequest]-ORC-3
        - [ ] MSH[MessageHeader]-MSH-21
        - [ ] OBR[Specimen]-OBR-2
        - [ ] ORC[DiagnosticReport]-ORC-2
        - [ ] ORC[DiagnosticReport]-ORC-3
        - [ ] OBX[Observation]-OBX-21
    - [ ] code
        - [ ] OBR[ServiceRequest]-OBR-2
        - [ ] OBR[ServiceRequest]-OBR-3
        - [ ] SPM[Specimen]-SPM-32
        - [ ] OBX[Observation-Component]-OBX-21
        - [ ] OBR[DiagnosticReport]-OBR-2
        - [ ] OBR[DiagnosticReport]-OBR-3
        - [ ] ORC[ServiceRequest]-ORC-2
        - [ ] ORC[ServiceRequest]-ORC-3
        - [ ] ORC[DiagnosticReport]-ORC-2
        - [ ] ORC[DiagnosticReport]-ORC-3
        - [ ] OBX[Observation]-OBX-21
    - [ ] uri
        - [ ] OBR[ServiceRequest]-OBR-2
        - [ ] OBR[ServiceRequest]-OBR-3
        - [ ] SPM[Specimen]-SPM-32
        - [ ] OBR[DiagnosticReport]-OBR-2
        - [ ] OBR[DiagnosticReport]-OBR-3
        - [ ] ORC[ServiceRequest]-ORC-2
        - [ ] ORC[ServiceRequest]-ORC-3
        - [ ] ORC[DiagnosticReport]-ORC-2
        - [ ] ORC[DiagnosticReport]-ORC-3
    - [ ] BackboneElement
        - [ ] PRT[Device]-PRT-10
        - [ ] PRT[Device]-PRT-16
    - [ ] string
        - [ ] PRT[Device]-PRT-21
    - [ ] Reference(ServiceRequest)
        - [ ] ORC[DiagnosticReport]-ORC-2
    - [ ] Reference(Device)
        - [ ] OBX[Observation]-OBX-18
- [ ] EIP
    - [ ] Identifier
        - [ ] SPM[Specimen]-SPM-2
        - [ ] SPM[Specimen]-SPM-3
        - [ ] ORC[DiagnosticReport]-ORC-4
    - [ ] Reference
        - [ ] OBX[Observation]-OBX-33
- [ ] EIP - This is EI in many versions including 2.9
    - [ ] Identifier
        - [ ] ORC[ServiceRequest]-ORC-4
    - [ ] code
        - [ ] ORC[ServiceRequest]-ORC-4
    - [ ] uri
        - [ ] ORC[ServiceRequest]-ORC-4
- [ ] CWE
    - [ ] CodeableConcept
        - [ ] OBR[ServiceRequest]-OBR-4
        - [ ] OBR[ServiceRequest]-OBR-13
        - [ ] OBR[ServiceRequest]-OBR-31
        - [ ] OBR[ServiceRequest]-OBR-46
        - [ ] OBR[ServiceRequest]-OBR-47
        - [ ] SPM[Specimen]-SPM-4
        - [ ] SPM[Specimen]-SPM-6
        - [ ] SPM[Specimen]-SPM-7
        - [ ] SPM[Specimen]-SPM-8
        - [ ] SPM[Specimen]-SPM-9
        - [ ] SPM[Specimen]-SPM-21
        - [ ] SPM[Specimen]-SPM-24
        - [ ] SPM[Specimen]-SPM-27
        - [ ] NTE[ServiceRequest]-NTE-4
        - [ ] OBX[Observation-Component]-OBX-3
        - [ ] OBX[Observation-Component]-OBX-8
        - [ ] OBX[Observation-Component]-OBX-17
        - [ ] OBX[Observation-Component]-OBX-20
        - [ ] NK1[Patient]-NK1-3
        - [ ] NK1[Patient]-NK1-7
        - [ ] OBR[DiagnosticReport]-OBR-4
        - [ ] PD1[Patient]-PD1-5
        - [ ] PD1[Patient]-PD1-6
        - [ ] PD1[Patient]-PD1-7
        - [ ] ORC[ServiceRequest]-ORC-16
        - [ ] ORC[ServiceRequest]-ORC-25
        - [ ] ORC[ServiceRequest]-ORC-29
        - [ ] ORC[ServiceRequest]-ORC-31
        - [ ] PV1[Patient]-PV1-16
        - [ ] PID[Patient]-PID-15
        - [ ] PID[Patient]-PID-16
        - [ ] PID[Patient]-PID-17
        - [ ] PID[Patient]-PID-26
        - [ ] PID[Patient]-PID-27
        - [ ] PID[Patient]-PID-28
        - [ ] PID[Patient]-PID-35
        - [ ] PID[Patient]-PID-36
        - [ ] PID[Patient]-PID-39
        - [ ] PV2[Encounter]-PV2-3
        - [ ] PV2[Encounter]-PV2-7
        - [ ] PV2[Encounter]-PV2-21
        - [ ] PV2[Encounter]-PV2-25
        - [ ] PV2[Encounter]-PV2-40
        - [ ] ORC[DiagnosticReport]-ORC-16
        - [ ] PRT[PractitionerRole]-PRT-4
        - [ ] PRT[PractitionerRole]-PRT-6
        - [ ] PRT[PractitionerRole]-PRT-7
        - [ ] PRT[PractitionerRole]-PRT-23
        - [ ] PRT[RelatedPerson]-PRT-4
        - [ ] PRT[RelatedPerson]-PRT-6
        - [ ] PRT[RelatedPerson]-PRT-7
        - [ ] PRT[RelatedPerson]-PRT-13
        - [ ] PRT[RelatedPerson]-PRT-23
        - [ ] OBX[Observation]-OBX-3
        - [ ] OBX[Observation]-OBX-8
        - [ ] OBX[Observation]-OBX-17
        - [ ] OBX[Observation]-OBX-20
        - [ ] PV1[Encounter]-PV1-4
        - [ ] PV1[Encounter]-PV1-10
        - [ ] PV1[Encounter]-PV1-13
        - [ ] PV1[Encounter]-PV1-14
        - [ ] PV1[Encounter]-PV1-16
        - [ ] PV1[Encounter]-PV1-36
        - [ ] PV1[Encounter]-PV1-38
        - [ ] NK1[RelatedPerson]-NK1-3
        - [ ] NK1[RelatedPerson]-NK1-7
        - [ ] NK1[RelatedPerson]-NK1-20
    - [ ] Quantity
        - [ ] OBX[Observation-Component]-OBX-6
        - [ ] OBX[Observation]-OBX-6
    - [ ] SimpleQuantity
        - [ ] OBX[Observation-Component]-OBX-6
        - [ ] OBX[Observation]-OBX-6
    - [ ] identifier
        - [ ] OBX[Observation-Component]-OBX-15
        - [ ] OBX[Observation]-OBX-15
    - [ ] code
        - [ ] NK1[Patient]-NK1-15
        - [ ] PID[Patient]-PID-8
        - [ ] MSH[MessageHeader]-MSH-19
        - [ ] PV1[Encounter]-PV1-2
        - [ ] NK1[RelatedPerson]-NK1-15
    - [ ] uri
        - [ ] PD1[Patient]-PD1-6
        - [ ] ORC[ServiceRequest]-ORC-16
        - [ ] PV1[Patient]-PV1-16
        - [ ] PID[Patient]-PID-17
        - [ ] PID[Patient]-PID-26
        - [ ] PID[Patient]-PID-28
        - [ ] PID[Patient]-PID-35
        - [ ] PID[Patient]-PID-36
        - [ ] PID[Patient]-PID-39
        - [ ] ORC[DiagnosticReport]-ORC-16
    - [ ] Coding
        - [ ] PV2[Encounter]-PV2-38
        - [ ] PV1[Encounter]-PV1-2
    - [ ] Annotation
        - [ ] OBR[Specimen]-OBR-39
- [ ] ID
    - [ ] code
        - [ ] OBR[ServiceRequest]-OBR-5
        - [ ] OBR[ServiceRequest]-OBR-11
        - [ ] SPM[Specimen]-SPM-20
        - [ ] OBX[Observation-Component]-OBX-11
        - [ ] OBX[Observation-Component]-OBX-29
        - [ ] OBX[Observation-Component]-OBX-30
        - [ ] OBR[DiagnosticReport]-OBR-25
        - [ ] ORC[ServiceRequest]-ORC-1
        - [ ] ORC[ServiceRequest]-ORC-5
        - [ ] OBX[Observation]-OBX-11
        - [ ] OBX[Observation]-OBX-29
        - [ ] OBX[Observation]-OBX-30
    - [ ] CodeableConcept
        - [ ] OBX[Observation-Component]-OBX-10
        - [ ] OBR[DiagnosticReport]-OBR-24
        - [ ] OBX[Observation]-OBX-10
        - [ ] OBX[Observation]-OBX-11
    - [ ] string
        - [ ] PID[Patient]-PID-12
        - [ ] MSH[MessageHeader]-MSH-17
    - [ ] boolean
        - [ ] PID[Patient]-PID-24
        - [ ] PID[Patient]-PID-30
        - [ ] PID[Patient]-PID-31
    - [ ] Coding
        - [ ] PV2[Encounter]-PV2-22
    - [ ] uri
        - [ ] OBX[Observation]-OBX-11
- [ ] TS
    - [ ] dateTime
        - [ ] OBR[ServiceRequest]-OBR-6
        - [ ] OBR[Specimen]-OBR-14
- [ ] XCN
    - [ ] Reference(Practitioner)
        - [ ] OBR[ServiceRequest]-OBR-16
        - [ ] NTE[ServiceRequest]-NTE-5
        - [ ] PD1[Patient]-PD1-4
        - [ ] ORC[ServiceRequest]-ORC-12
        - [ ] PV2[Encounter]-PV2-13
        - [ ] OBR[Specimen]-OBR-10
        - [ ] PRT[PractitionerRole]-PRT-5
        - [ ] PV1[Encounter]-PV1-7
        - [ ] PV1[Encounter]-PV1-8
        - [ ] PV1[Encounter]-PV1-9
        - [ ] PV1[Encounter]-PV1-17
        - [ ] PV1[Encounter]-PV1-52
    - [ ] Reference(PractitionerRole)
        - [ ] OBX[Observation-Component]-OBX-16
        - [ ] OBX[Observation-Component]-OBX-25
        - [ ] OBX[Observation]-OBX-16
        - [ ] OBX[Observation]-OBX-25
    - [ ] string
        - [ ] OBX[Observation-Component]-OBX-16
        - [ ] OBX[Observation-Component]-OBX-25
        - [ ] PV2[Encounter]-PV2-13
        - [ ] PV1[Encounter]-PV1-7
        - [ ] PV1[Encounter]-PV1-8
        - [ ] PV1[Encounter]-PV1-9
        - [ ] PV1[Encounter]-PV1-17
        - [ ] PV1[Encounter]-PV1-52
    - [ ] uri
        - [ ] OBX[Observation-Component]-OBX-16
        - [ ] OBX[Observation-Component]-OBX-25
        - [ ] PV2[Encounter]-PV2-13
        - [ ] PV1[Encounter]-PV1-7
        - [ ] PV1[Encounter]-PV1-8
        - [ ] PV1[Encounter]-PV1-9
        - [ ] PV1[Encounter]-PV1-17
        - [ ] PV1[Encounter]-PV1-52
    - [ ] code
        - [ ] PV2[Encounter]-PV2-13
        - [ ] OBX[Observation]-OBX-25
        - [ ] PV1[Encounter]-PV1-7
        - [ ] PV1[Encounter]-PV1-8
        - [ ] PV1[Encounter]-PV1-9
        - [ ] PV1[Encounter]-PV1-17
        - [ ] PV1[Encounter]-PV1-52
    - [ ] CodeableConcept
        - [ ] OBX[Observation]-OBX-16
- [ ] XTN
    - [ ] ContactPoint
        - [ ] OBR[ServiceRequest]-OBR-17
        - [ ] NK1[Patient]-NK1-5
        - [ ] NK1[Patient]-NK1-6
        - [ ] NK1[Patient]-NK1-31
        - [ ] NK1[Patient]-NK1-40
        - [ ] NK1[Patient]-NK1-41
        - [ ] ORC[ServiceRequest]-ORC-23
        - [ ] PID[Patient]-PID-13
        - [ ] PID[Patient]-PID-14
        - [ ] PID[Patient]-PID-40
        - [ ] PRT[PractitionerRole]-PRT-15
        - [ ] PRT[RelatedPerson]-PRT-15
        - [ ] NK1[RelatedPerson]-NK1-5
        - [ ] NK1[RelatedPerson]-NK1-6
        - [ ] NK1[RelatedPerson]-NK1-31
        - [ ] NK1[RelatedPerson]-NK1-40
        - [ ] NK1[RelatedPerson]-NK1-41
    - [ ] code
        - [ ] NK1[Patient]-NK1-6
- [ ] CX
    - [ ] Identifier
        - [ ] OBR[ServiceRequest]-OBR-53
        - [ ] SPM[Specimen]-SPM-30
        - [ ] SPM[Specimen]-SPM-31
        - [ ] ORC[ServiceRequest]-ORC-33
        - [ ] PID[Patient]-PID-2
        - [ ] PID[Patient]-PID-3
        - [ ] PID[Patient]-PID-4
        - [ ] PV1[Encounter]-PV1-5
        - [ ] PV1[Encounter]-PV1-19
        - [ ] PV1[Encounter]-PV1-50
        - [ ] PV1[Encounter]-PV1-54
        - [ ] NK1[RelatedPerson]-NK1-12
        - [ ] NK1[RelatedPerson]-NK1-33
    - [ ] code
        - [ ] OBR[ServiceRequest]-OBR-53
        - [ ] ORC[ServiceRequest]-ORC-33
        - [ ] PV1[Encounter]-PV1-19
    - [ ] uri
        - [ ] OBR[ServiceRequest]-OBR-53
        - [ ] ORC[ServiceRequest]-ORC-33
        - [ ] PV1[Encounter]-PV1-19
    - [ ] string
        - [ ] PV1[Encounter]-PV1-19
- [ ] CQ
    - [ ] SimpleQuantity
        - [ ] SPM[Specimen]-SPM-12
        - [ ] OBR[Specimen]-OBR-9
- [ ] ST
    - [ ] markdown
        - [ ] SPM[Specimen]-SPM-14
    - [ ] string
        - [ ] PRT[Device]-PRT-19
        - [ ] PRT[Device]-PRT-20
        - [ ] PID[Patient]-PID-19
        - [ ] PID[Patient]-PID-23
        - [ ] MSH[MessageHeader]-MSH-8
        - [ ] MSH[Bundle]-MSH-10
        - [ ] OBX[Observation]-OBX-7
        - [ ] PV1[Encounter]-PV1-53
        - [ ] SFT[MessageHeader]-SFT-2
        - [ ] SFT[MessageHeader]-SFT-3
        - [ ] SFT[MessageHeader]-SFT-4
    - [ ] code
        - [ ] PID[Patient]-PID-19
    - [ ] uri
        - [ ] PID[Patient]-PID-19
        - [ ] PID[Patient]-PID-23
        - [ ] MSH[Bundle]-MSH-10
        - [ ] NK1[RelatedPerson]-NK1-37
    - [ ] xhtml
        - [ ] PV2[Encounter]-PV2-12
    - [ ] Identifier
        - [ ] NK1[RelatedPerson]-NK1-37
- [ ] DTM
    - [ ] dateTime
        - [ ] SPM[Specimen]-SPM-18
        - [ ] NTE[ServiceRequest]-NTE-6
        - [ ] OBX[Observation-Component]-OBX-14
        - [ ] OBX[Observation-Component]-OBX-19
        - [ ] OBR[DiagnosticReport]-OBR-7
        - [ ] OBR[DiagnosticReport]-OBR-8
        - [ ] PRT[Device]-PRT-17
        - [ ] PRT[Device]-PRT-18
        - [ ] ORC[ServiceRequest]-ORC-9
        - [ ] ORC[ServiceRequest]-ORC-15
        - [ ] PID[Patient]-PID-7
        - [ ] PID[Patient]-PID-29
        - [ ] PID[Provenance-Patient]-PID-33
        - [ ] PV2[Encounter]-PV2-8
        - [ ] PV2[Encounter]-PV2-9
        - [ ] OBR[Specimen]-OBR-7
        - [ ] OBR[Specimen]-OBR-8
        - [ ] PRT[PractitionerRole]-PRT-11
        - [ ] PRT[PractitionerRole]-PRT-12
        - [ ] PRT[RelatedPerson]-PRT-11
        - [ ] PRT[RelatedPerson]-PRT-12
        - [ ] OBX[Observation]-OBX-14
        - [ ] OBX[Observation]-OBX-19
        - [ ] PV1[Encounter]-PV1-44
        - [ ] PV1[Encounter]-PV1-45
        - [ ] SFT[MessageHeader]-SFT-6
    - [ ] instant
        - [ ] OBR[DiagnosticReport]-OBR-22
        - [ ] PID[Patient]-PID-33
        - [ ] MSH[Bundle]-MSH-7
    - [ ] date
        - [ ] PID[Patient]-PID-7
        - [ ] NK1[RelatedPerson]-NK1-16
    - [ ] uri
        - [ ] PID[Patient]-PID-7
    - [ ] code
        - [ ] PV1[Encounter]-PV1-45
- [ ] FT
    - [ ] markdown
        - [ ] NTE[ServiceRequest]-NTE-3
- [ ] varies
    - [ ] quantity
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
    - [ ] string
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
    - [ ] CodeableConcept
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
    - [ ] Period
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
    - [ ] dateTime
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
    - [ ] Range
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
    - [ ] time
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
    - [ ] Ratio
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
    - [ ] Quantity
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
    - [ ] SampledData
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
    - [ ] uri
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
    - [ ] Attachment
        - [ ] OBX[Observation-Component]-OBX-5
        - [ ] OBX[Observation]-OBX-5
- [ ] XON
    - [ ] Reference(Organization)
        - [ ] OBX[Observation-Component]-OBX-23
        - [ ] NK1[Patient]-NK1-13
        - [ ] PD1[Patient]-PD1-3
        - [ ] ORC[ServiceRequest]-ORC-21
        - [ ] MSH[MessageHeader]-MSH-22
        - [ ] MSH[MessageHeader]-MSH-23
        - [ ] PRT[PractitionerRole]-PRT-8
        - [ ] PRT[RelatedPerson]-PRT-8
        - [ ] OBX[Observation]-OBX-23
        - [ ] MSH[Provenance-Source]-MSH-22
        - [ ] SFT[MessageHeader]-SFT-1
    - [ ] string
        - [ ] PD1[Patient]-PD1-14
    - [ ] code
        - [ ] MSH[Provenance-Source]-MSH-22
    - [ ] uri
        - [ ] MSH[Provenance-Source]-MSH-22
- [ ] XAD
    - [ ] Address
        - [ ] OBX[Observation-Component]-OBX-24
        - [ ] NK1[Patient]-NK1-4
        - [ ] NK1[Patient]-NK1-32
        - [ ] ORC[ServiceRequest]-ORC-22
        - [ ] PID[Patient]-PID-11
        - [ ] PRT[Observation-Location]-PRT-14
        - [ ] PRT[PractitionerRole]-PRT-14
        - [ ] PRT[RelatedPerson]-PRT-14
        - [ ] OBX[Observation]-OBX-24
        - [ ] NK1[RelatedPerson]-NK1-4
        - [ ] NK1[RelatedPerson]-NK1-32
    - [ ] uri
        - [ ] PRT[Observation-Location]-PRT-14
- [ ] XPN
    - [ ] HumanName
        - [ ] NK1[Patient]-NK1-2
        - [ ] NK1[Patient]-NK1-30
        - [ ] PID[Patient]-PID-5
        - [ ] PID[Patient]-PID-9
        - [ ] NK1[RelatedPerson]-NK1-2
        - [ ] NK1[RelatedPerson]-NK1-30
    - [ ] uri
        - [ ] PID[Patient]-PID-6
    - [ ] string
        - [ ] PID[Patient]-PID-6
- [ ] DT
    - [ ] dateTime
        - [ ] NK1[Patient]-NK1-8
        - [ ] NK1[Patient]-NK1-9
        - [ ] NK1[RelatedPerson]-NK1-8
        - [ ] NK1[RelatedPerson]-NK1-9
- [ ] NDL
    - [ ] Reference(PractitionerRole)
        - [ ] OBR[DiagnosticReport]-OBR-32
        - [ ] OBR[DiagnosticReport]-OBR-34
    - [ ] uri
        - [ ] OBR[DiagnosticReport]-OBR-34
        - [ ] OBR[DiagnosticReport]-OBR-35
    - [ ] code
        - [ ] OBR[DiagnosticReport]-OBR-34
        - [ ] OBR[DiagnosticReport]-OBR-35
    - [ ] Reference(Practitioner)
        - [ ] OBR[DiagnosticReport]-OBR-35
- [ ] CNE
    - [ ] CodeableConcept
        - [ ] PRT[Device]-PRT-22
- [ ] DLN
    - [ ] Identifier
        - [ ] PID[Patient]-PID-20
- [ ] NM
    - [ ] integer
        - [ ] PID[Patient]-PID-25
    - [ ] Quantity
        - [ ] PV2[Encounter]-PV2-10
        - [ ] PV2[Encounter]-PV2-11
- [ ] HD
    - [ ] Reference(Organization)
        - [ ] PID[Patient]-PID-34
        - [ ] MSH[MessageHeader]-MSH-4
        - [ ] MSH[MessageHeader]-MSH-6
        - [ ] PID[Provenance-Patient]-PID-34
        - [ ] MSH[Provenance-Source]-MSH-4
    - [ ] string
        - [ ] MSH[MessageHeader]-MSH-3
        - [ ] MSH[MessageHeader]-MSH-24
    - [ ] uri
        - [ ] MSH[MessageHeader]-MSH-3
        - [ ] MSH[MessageHeader]-MSH-24
        - [ ] MSH[MessageHeader]-MSH-25
        - [ ] PID[Provenance-Patient]-PID-34
        - [ ] MSH[Provenance-Source]-MSH-4
    - [ ] Reference(Device)
        - [ ] MSH[MessageHeader]-MSH-5
        - [ ] MSH[Provenance-Source]-MSH-3
    - [ ] code
        - [ ] MSH[MessageHeader]-MSH-24
        - [ ] MSH[MessageHeader]-MSH-25
        - [ ] PID[Provenance-Patient]-PID-34
        - [ ] MSH[Provenance-Source]-MSH-3
        - [ ] MSH[Provenance-Source]-MSH-4
- [ ] MSG
    - [ ] Coding
        - [ ] MSH[MessageHeader]-MSH-9
    - [ ] string
        - [ ] MSH[Provenance-Source]-MSH-9
- [ ] PT
    - [ ] meta
        - [ ] MSH[MessageHeader]-MSH-11
- [ ] PL
    - [ ] Reference(Location)
        - [ ] PV2[Encounter]-PV2-1
        - [ ] PRT[PractitionerRole]-PRT-9
        - [ ] PRT[RelatedPerson]-PRT-9
        - [ ] PV1[Encounter]-PV1-3
        - [ ] PV1[Encounter]-PV1-6
        - [ ] PV1[Encounter]-PV1-11
        - [ ] PV1[Encounter]-PV1-42
        - [ ] PV1[Encounter]-PV1-43
    - [ ] boolean
        - [ ] PV2[Encounter]-PV2-1
        - [ ] PV1[Encounter]-PV1-11
        - [ ] PV1[Encounter]-PV1-43
    - [ ] uri
        - [ ] PRT[Observation-Location]-PRT-9
    - [ ] Reference
        - [ ] PRT[Observation-Location]-PRT-9
    - [ ] code
        - [ ] PV1[Encounter]-PV1-3
        - [ ] PV1[Encounter]-PV1-6
- [ ] PLN
    - [ ] Identifier
        - [ ] PRT[PractitionerRole]-PRT-24
        - [ ] PRT[RelatedPerson]-PRT-24
- [ ] FC
    - [ ] CodeableConcept
        - [ ] PV1[Encounter]-PV1-20
- [ ] DLD
    - [ ] Reference(Location)
        - [ ] PV1[Encounter]-PV1-37
- [ ] TX
    - [ ] string
        - [ ] SFT[MessageHeader]-SFT-5
```

The strategy for managing this epic is to (generally) create a single story for each HL7v2 DataType (level 1), breaking it up into multiple stories if there are a lot of mappings for a type (like CWE).

### Lessons Learned and Decisions Made
**Instructions:** Update this section as you work through the stories to document any decisions that were made in regards to mapping strategy/ process.

### Acceptance Criteria

- [ ] All DataType mappings referenced by ORU-R01 segments have been updated and documentation created

**Comment by arnejduranovic** [comment]
@Andrey-Glazkv FYI
