### ISSUE TITLE
US Virgin Islands - Receiver Onboarding

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#12262]
### What You Need to Know 
 
- [x] Kickoff meeting completed 
- [x] Receiver intake form completed: [paste info below this] 

### To Do 

- [x] create individual tickets for this epic 
- [x] RS team member who originates this ticket: add any dependencies, as needed
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Receiver" 
     - [x] Epics: [select the epic for this receiver we're onboarding]

**Comment by MikaelahD13** [comment]
Closing, work completed.
