### ISSUE TITLE
EPIC Onboarding - 1. Validate Test Files [ETOR]

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#12996]
### Acceptance Criteria 
- [x] Sample file from sender received by RS team 
- [x] Sample files saved to Keybase by assigned RS engineer 
- [x] Sample file ingested into RS using validation UI tool by assigned RS engineer 
- [ ] Feedback provided to sender by assigned RS engineer  (including instructions on what to modify in order to get validated)* 
- [ ] Sender modifies and re-sends sample file to get file validated by RS engineer* 

*Steps can continue until RS can ingest the file from sender 

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with sender 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: make sure the following are included when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Sender" 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by chris-kuryak** [comment]
From Ott: Flexion came back to say everything is not ready to close. There is some encryption work that still needs to be implemented, and we are waiting for a response from them (Postman) to continue work.

**Comment by chris-kuryak** [comment]
Encryption working for UCSD EPIC. Now waiting on Flexion team to successfully route test messages to UCSD EPIC endpoint. Ott helping where necessary.

**Comment by oslynn** [comment]
Testing with Postman"

<img width="1300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU1DQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd77e516e639b452c6fe25c5053802e1ed8b7e12/image.png" alt="image.png" />


<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUFDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fad6efcee65783247c6e0392fee5dc52769e4c8e/image.png" alt="image.png" />

**Comment by oslynn** [comment]
Done for staging.
