### ISSUE TITLE
EPIC - API Sender Onboarding [ETOR]

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#13001]
### What You Need to Know 

- [ ] Terms of Service agreement signed 

- [ ] Kickoff meeting completed 

- [ ] Company’s intake form: [paste info below this] 

 

### To Do 

- [ ] create individual tickets for this epic 

- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 

- [ ] RS team member who originates this ticket: add any dependencies, as needed
