### ISSUE TITLE
Engineering work to add roadmap to website

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#13664]
## Problem statement
Add the product roadmap to the RS website

## What you need to know
- The content is in this [Roadmap doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BC9FF05CA-C854-458D-8A78-2A5BD2CA50E6%7D&file=20240301_Public_Roadmap.docx&action=default&mobileredirect=true)
- **Do not use** Figma for content source of truth

## Acceptance criteria
- [x] New page created in accordance with [design artifacts](https://www.figma.com/file/86JATe4hOwPfihwwloM5b8/Blockframes?type=design&node-id=2131-1946&mode=design)
- [x] Content matches [Roadmap doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7BC9FF05CA-C854-458D-8A78-2A5BD2CA50E6%7D&file=20240301_Public_Roadmap.docx&action=default&mobileredirect=true)
- [x] Page appears in the side nav on About page
- [x] Page appears in top nav About drop-down
- [x] E2E tests are created
  - [x] Page loads
  - [x] Page content loads without errors
  - [x] All Internal Links work and take you to expected page
  - [x] All External Links work
  - [x] Components work as expected (eg, accordion expands/collapses, side nav, etc)

**Comment by penny-lischer** [comment]
@chris-kuryak should we include e2e as part of this ticket?

**Comment by chris-kuryak** [comment]
@penny-lischer Great point!
Can we roll it in without overloading this ticket? Or does it need to be a separate ticket?

**Comment by penny-lischer** [comment]
I think we should include e2e for all new pages going forward. I will update the points accordingly

**Comment by penny-lischer** [comment]
@audreykwr can you provide the title and description meta for the roadmap please
