### ISSUE TITLE
Deduplication in the UP MVP

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#14103]
## Outcome/Objective  

An MVP version of deduplication detection is implemented in the UP for ELR use cases (ORU-R01). 

 

## Context 

Deduplication was originally built into the CP in response to a specific sender bug. This occurred the beginning of July 22 where a sender(PMG) introduced a bug in their system resulting in tests results not being marked as sent. That meant their system starting sending the same message over and over again. This continued for a few days before we turned off the auth for that sender. In those few days PMG was sender >800,000 messages/day. We worked with PMG and they eventually fixed the bug.  

  

In followup to that that incident, we decided to implement deduplication logic to catch the resends in the event a similar situation occurred in the future. The idea being that duplicate reports would be discarded without the need to completely disable the sender. 

  

Due to a [bug](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/14102), in the implementation the duplication feature never worked for the UP and needs to be re-implemented 

  

Furthermore, recently to solve the file limit issue we've decoupled the batching step within the pipeline so that we can process messages one at a time. However, we do allow senders to send batched messages. Thus we will have scenarios where a sender sends a batch, some messages in that batch are good and processed and others error out. When we ask the sender to fix the errors and resend, if they send in batch, they could resend the whole batch including the messages that were already good and processed. To avoid processing the same messages twice we need a way to detect the duplicate message in the batch and ensure the duplicates are not processed, only the messages that needed fixing should get through. 

 

Some receivers, such as CA Department of Public Health have deduplication systems in place, but not all receivers are fortunate to have the same resources. Therefore, ReportStream aims to provide the same opportunity to access to improved data accuracy by implementing deduplication prior to delivering to its receivers. 

 

## Use Cases 

- As a receiver of the UP, I would like to not receive duplicative data – so that I can have a more accurate account of data that I’m receiving. 

- As a sender to the UP, I would like to submit reports to ReportStream in the most convenient method possible, which may sometimes contain previously submitted, duplicate messages. 

 

## Scenarios  

_“Items” refer to the messages contained within a report. An item may contain multiple DiagnosticReports and Observations (including AOEs)._ 
**SCENARIOS SUPPORTED BY THIS DEDUPLICATION MVP**
 >**1. Deduplicating reports**
_This is what was historically supported by the COVID Pipeline._   
Sender submits Report1 on Nov 1 and submits Report1 (with no changes to the content) on Nov 2. The deduplication feature will remove any subsequent submissions of Report1 (in this case, the one submitted on Nov 2).
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm5YQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba8bfbdfb3d0c6e1f941c6bde513618853f0bb8c/image.png" alt="image.png" />

>**2. Deduplicating items within the same report**  
_This is what was historically supported by the COVID Pipeline._ 
Sender submits Report1 with items A, B, C, A within it. The deduplication feature will remove any subsequent instances of item A.  
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjdYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--924fab9c218ba8f040293576be9b51e25b137d90/image.png" alt="image.png" />

>**3. Deduplicating items across reports**  
Sender submits two reports: Report1 with items A, B, C & Report2 with items D, E, A. The deduplication feature will detect that item A is a duplicate across multiple submitted reports and remove any subsequent instances of item A (in this case, the one that was submitted within Report2). Items D and E will continue to be processed. 
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi9YQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f541401bd3aa59e86057c506da8ee9ca5cc94326/image.png" alt="image.png" /> 
Example: As of Nov 2024, SimpleReport does not have a deduplication feature. An organization that uses SimpleReport’s _CSV Uploader_ adds new test result data by appending new rows to a previously submitted CSV file (new + old content) and uploads it to SimpleReport. SimpleReport will then submit this report to ReportStream (assigning a new message header for each upload instance). 

**XXX  SCENARIOS NOT SUPPORTED  XXX** 
>**4. Deduplicating items across senders**  
Sender ABC submits Report1 [with items A, B, C]. Sender XYZ  submits Report1 [with items A, B, C]. Both reports from both senders are exactly identical (duplicates). A deduplication feature will detect, not only all the items as duplicates, but also the reports as duplicates. Subsequent instances are removed.
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM25YQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cffaafaca838eef9799b82615e72b3cdd49b590/image.png" alt="image.png" />
This MVP will only deduplicate on an individual sender basis. 

 >**5. Deduplicating observations across items**  
Sender submits Report1 with items A and B. Item A contains test result observations for COVID, flu, and RSV. Item B contains the same COVID and flu test result observations (for the same patient, test performed, time, etc.) and an additional observation for syphilis. A deduplication feature will detect that the COVID and Flu observations from Item A and B are identical and remove any subsequent instances (in this case, the ones from item B). The syphilis observation from Item B will continue to be processed by the pipeline. 
<img width="450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1BYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d1363c30ae16d92c073a2956414e360e2cb58cc/image.png" alt="image.png" />

>**6. Deduplicating across systems**  
ReportStream sends Report1 with items A, B, C to a Public Health Dpt. AIMS sends Report2 with items D, E, A. A deduplication feature (mostly likely on the PHD’s side) will detect item A as a duplicate and remove subsequent instances of it.
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--258a507b6201bfc9f81d74fe6dcdb12765a1ac80/image.png" alt="image.png" />

## Product Requirements
1. Once a duplicate message is detected, prevent it from being further processed. 

2. All incoming items of a report should be compared to all items submitted in at least the **past year**. This excludes data submitted prior to the implementation of the deduplication feature.

3. Duplication detection can be configured 'on' or 'off' for a specified sender (at the specific sender level, not sender org level). The default for senders is to have their deduplication configuration as 'on', which means deduplication is active. However, if the sender's settings for dedupe is configured as 'off', the message contents will still be hashed in event that the sender configuration will be toggled back to 'on' in the future.  

4. Senders shall not be able to change their deduplication configuration without the intervention of/ request through a ReportStream admin. 

5. If an Item is determined to be a duplicate, ReportStream shall log (application log AND action log) an error that an item was rejected. The log message should be: ERR, UNKNOWN, "Duplicate message was detected and removed." 

6. For the MVP iteration, the deduplication feature will apply only to test results (ORU_R01) data types. However, one must keep in mind that there may be future iterations that implement deduplication for other data types, such as test orders (for ETOR). 
   

## Acceptance criteria   
- [ ] All the requirements above are met in staging and production 
- [ ] Run a series of tests that represent the supported scenarios above 
- [ ] Each test scenario will simulate at least 5 duplicate items/ reports being detected and removed 
- [ ] Confirm that the duplications are being logged correctly (syntax and timing) 
- [ ] Set deduplication feature ‘off’ for all senders under the ELIMS org.  
- [ ] Prior to deployment, notify Deliver and Product Mgrs of potential deduplication dependencies with active pilot sender partners. 
- [ ] Technical design and final implementation are documented 
 

## Technical Design Considerations
- De-duplication in the covid pipeline currently occurs in the Receive function, but that likely does not make sense for the UP.  It's worth considering if the logic in the UP should live somewhere else (i.e. convert step) 

- The current logic for de-duping needs to be reconsidered for the UP; likely the item hash should be generated from the FHIR bundle so that the logic only needs to get written once - the issue here is if mappings change then FHIR bundle will be different even if original message is the same... 

- What if a message fails because of a bug on our side? If they resent, would hashing see it as the same message and filter out. 
- If a value is blank or not provided, consider how the hash will represent those blank fields (so that it can compare other messages with the same blank fields). 
- Consider how to purge stored hashes once they have "expired" after a year.
- Should MessageID uniqueness be enforced here as well? 
- In the case of SimpleReport, some unique IDs (accession number [specimen ID], CLIA number, etc.) are not guaranteed to be unique or validated due to some users of SimpleReport not having mature systems to generate and track them. If that is the case for SR, it could be true for other senders as well, making deduplication strategies less-effective or error prone. To mitigate accidentally detecting and removing non-duplicates, we recommend being more strict (comparing across many more data elements) with the deduplication criteria. This theoretically allows for more duplicates to pass through RS, but lessens the risk of accidentally removing data that is valid.
- Verify that the deduplication criteria works for all types of ELR messages (e.g., ELIMS, RADxMARS, full-ELR) and doesn't accidentally remove non-duplicates.
  

**Criteria for an item (ORU-0R1 message) to be considered a duplicate** 
Combine all the following into a hash. Should the hashes match, remove the corresponding item(s) that correlate to the subsequent instance(s). 
| Data Element                                                           | HL7                             | FHIR                                                                                                       |
|------------------------------------------------------------------------|---------------------------------|------------------------------------------------------------------------------------------------------------|
| Specimen ID                                                            | SPM.2                           | Specimen.Identifier                                                                                        |
| Accession number                                                       | SPM.30 (not v2.5.1 compatible)  | Specimen.accessionIdentifier                                                                               |
| Specimen Collection Date/Time (if different from other date/time)      | SPM.17                          | Specimen.collection.collectedDateTime                                                                      |
| Patient ID                                                             | PID.3                           | Patient.identifier                                                                                         |
| Patient name                                                           | PID.5                           | Patient.name                                                                                               |
| Patient DOB                                                            | PID.7                           | Patient.birthDate birthDate.extension[1].valueDateTime                                                     |
| Results Rpt/Status Chng – Date/Time                                    | OBR.22                          | DiagnosticReport.issued                                                                                    |
| Result Status                                                          | OBR.25                          | DiagnosticReport.status                                                                                    |
| Performing Organization/ Testing facility CLIA                         | OBX.23                          | Observation.Performer -> Organization.Identifier.value                                                     |
| Performing Organization/ Testing facility name                         | OBX.23                          | Observation.Performer -> Organization.name                                                                 |
| Test performed code                                                    | OBX.3.1                         | Observation.resource.code.system                                                                           |
| Test performed code system                                             | OBX.3.3                         | Observation.resource.code.coding                                                                           |
| Date/Time of the Observation (this appears in multiple HL7 locations)  | OBX.14, OBR.7, SPM.17           | Observation.resource.issued <br>DiagnosticReport.effectiveDateTime DiagnosticReport.effectivePeriod.start  |
| Observation Value/ Test result code                                    | OBX.5                           | Observation.resource.valueCodeableConcept.coding.code                                                      |
| Observation Value/ Test result code system                             | OBX.3.3                         | Observation.resource.valueCodeableConcept.coding.system                                                    |

**Comment by JFisk42** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14103?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @david-navapbc @jack-h-wang @jalbinson @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14103?planning-poker) with Zenhub @david-navapbc

**Comment by Andrey-Glazkv** [comment]
@brandonnava please have a look - need reqs for this one

**Comment by brandonnava** [comment]
Updated with specific use case and product rationale section outlining the scenario surrounding the specific use case that warrants for duplication detection

**Comment by arnejduranovic** [comment]
From your detailed post (thank you!) I am seeing the following additional requirements should get added to the `Product Requirement(s)` section (please confirm or deny):

COICE (PICK ONE):
1.A:  A message shall be considered a duplicate of another message if at least its `message Id`, `patient id`, and `test identifier/code` match another message's. 
    - In HL7v2, these are the following fields: <please complete>
    - In FHIR, these are the following elements: <please complete>
1.B:  A message shall be considered a duplicate of another message if it is an exact string match of another message

2. All incoming messages should be compared to all messages submitted in at least the past year, regardless of the sender of each message.

3. duplication detection logic shall only run on an incoming message if the feature is configured for a particular sender. However, their submitted messages shall still be taken into account for future duplication detection scenarios.

4. If an Item is determined to be a duplicate, ReportStream shall log a warning that an item was rejected

**Comment by brandonnava** [comment]
Not much to add Jess your responses pretty much align with what we took away from our meeting on this with Mo. 

The one thing to add for new requirement 1 in Arnej's list is a part of our brainstorm with Mo was on trying to figure out if dedupe by message Id, patient id, and test identifier/code were enough to tell if a message resent because the first send had an error that needed fixing would be enough to catch that use case or if we needed to also check another field to account for that (I know we mentioned MSH status or OBR.25 though it doesn't seem like either of those is quite right). 

For new requirement 3 I'm wondering do we want to have the feature turn on/off based on sender or receiver? Seems like we'd end up asking receivers if they want dupe detection on or not. 

And on 4 we can talk about if it's a warning or not. On instinct warning seems right but technically don't we allow messages with warnings to be processed and not ones with errors? By that logic since the message wouldn't get processed/sent it would be an error. The flip logic is that usually errors you want to tell the sender so they fix the message but this isn't a type of error that involves improving the message in any way, it just means don't sent it again.

**Comment by JFisk42** [comment]
Presented overall design for Dedupe at engineering sync on Monday, @victor-chaparro had feedback that the engagement team would want two things:
- Azure Event logging with parent_report_id, child_report_id, and sender org/name.
- Nice to have: The ability for the engagement team to resend items that were flagged as duplicates, and bypass the duplication check on that go through. 
  - My initial thought on this is that it could be simply added to the existing poison queue or we could create a dedupe queue. At the moment I don't have an estimate on the relative amount of effort involved in standing up a new queue like that. 

I'm going to go ahead and incorporate the Azure Event into the design and we can have a discussion here or on a call at some point about the priority and requirements for a potential ability to resend duplicate items. Does that sound good @jsutantio ?

**Comment by JFisk42** [comment]
Left a comment on the main task with some short dev notes about the state of the implementation and a link to the branch. 
Current progress ~33% complete
Remaining time for that task: ~6 days

After that task the intention is to push the change to production and collect hash data to verify that we aren't flagging false positives as duplicate items. Once that eval period has happened the next ticket could be completed in under a day. That would turn on the deduplication workflow for all UP senders by default.
