### ISSUE TITLE
Migrate to automated API tools pipeline via OpenAPI

### ISSUE THREAD

**Issue by jpandersen87** [CDCgov/prime-reportstream#14353]
A healthy API is one that automatically generates an OpenAPI document describing it, which allows for automation of things such as code generation of tools that test and use the API in any languages that support it. We need to make the needed changes to backend to facilitate this.

# Acceptance Criteria
- [ ] A 3.1 OpenAPI document describing our API that passes validation is automatically generated with all azure function endpoints as paths
- [ ] Each azure function that acts as an endpoint should be properly annotated with:
  - [ ] security 
  - [ ] method
  - [ ] operationId
  - [ ] path
  - [ ] responses with schemas
