### ISSUE TITLE
[SPIKE] Why is App Insights 'activeMembership' tracking as undefined and <undefined>

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14662]
## Problem statement
App Insights started tracking the variable 'activeMembership' as either `undefined` and `<undefined>` in late April 2024. This is confusing as `undefined` is a string and `<undefined>` is technically defined as "empty". We want to find out the difference between them, why it happened, and devise a solution.

## What you need to know
- [Active Membership by session over time can be seen here](https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourceGroups/prime-data-hub-prod/providers/Microsoft.Insights/components/pdhprod-appinsights/sessions)

## Acceptance criteria

- [ ] Identify the difference in 'activeMembership' between `undefined` and `<undefined>` and what triggers each
- [ ] Identify why the change started happening (if possible)
- [ ] Identify a potential solution(s) to the issue
- [ ] Review with Product and Tech Lead 
- [ ] Help craft the follow-on ticket (if needed)
