### ISSUE TITLE
High Fidelity Design for Message Testing Automation MVP

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15407]
## Problem statement
Design needs to create high-resolution designs for the Message Testing Automation MVP to facilitate a handoff to FE Engineering.

## Milestones & timeline
**Milestone: Hi-fi design explorations**
- Targeted questions for front-end | 17th minute @ Monday, August 12
- [If needed] Review with Design team | Design Crit @ Thursday, Aug 15
- Review final results formatting with Victor | TO BE SCHEDULED
- Design Lead check-in | 1:1 @ Friday, Aug 16th
- [Option 1] Engagement Engineering check-in | Engagement Engineering Sync @ Friday, Aug 16

**Milestone: Draft hi-fi design for cross-team review**
- [Option 2] Engineering check-in | Engagement Engineering Sync @ Tuesday, Aug 20
- Review with Design team | Design Crit @ Thursday, Aug 22
- Design Lead check-in | 1:1 @ Friday, Aug 16th

**Milestone: Final hi-fi design for alignment before eng hand-off**
- Alignment call - Review with Product & Design Lead & Content | Sync meeting @ Monday, August 26
- Reviewed with content strategist for final approval | Via Slack or 1:1 @ Tuesday, August 27
- Share final design link with full team for awareness | Async Slack message @ Wednesday, August 28

## Acceptance criteria

**Review**

- [x]  Reviewed with design and/or design lead 
- [x]  Reviewed with content strategist for final approval 8/27

**Design**
- [x] Incorporated feedback from design, eng, and product on design
- [x] Design includes:
  - [x] Final interaction flow with all states captured or annotated
  - [x] Final visual design (typography styles, colors, layout, spacing)
  - [x] Final content
  - [x] Final USWDS components
  - [x] Final custom components, if any
 

[Figma file
](https://www.figma.com/design/iIGPoS3V2MCVsOOUZKlgiV/Receiver-Message-Testing?node-id=0-1&node-type=CANVAS&t=ljqrUiYhSjkUcBQK-0)

**Comment by jillian-hammer** [comment]
took a pass at filing out the ACs here @jakefishbein-navapbc cc @chris-kuryak. Jake, can you review what I’ve added and write the rest of the ticket once the cross-team reviews of the wireframes are complete? thanks!

**Comment by jakefishbein-navapbc** [comment]
Shared final mocks with engineers. Included annotations regarding any differences with USWDS components, as well as other information.
