### ISSUE TITLE
Public roadmap and FY24 recap content

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#15853]
## Problem statement

We need to keep our public roadmap regularly updated, and with FY24 coming to a close, we can also consider specific things to highlight for this year. 

## What you need to know
Channel for FY24 highlights is not finalized. So the content for that will likely not be final either.

- [Roadmap drafting space](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Public%20roadmap%20content/20240911_Public_Roadmap_updates.docx?d=w74810cebe19742a09bd51c6d1d252050&csf=1&web=1&e=OiSi9U)

## Acceptance criteria

- [x] Content for public roadmap drafted and approved by necessary stakeholders
- [x] Eng ticket made for roadmap site updates
- [ ] Summary of potential FY24 highlights scoped or created

**Comment by chris-kuryak** [comment]
Eng ticket created #15973
