### ISSUE TITLE
Empower the RS Support team with the tools and training to diagnose and solve problems efficiently and independently

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#16378]
### User Story
As a support team member I want to be able to understand errors senders are getting when submitting to ReportStream so I can provide the sender writing in to support with enough information to act on the error and I won't need to escalate the ticket to an onboarding engineer to help. 
 
### Description/Use Case
Research from the [External Message Monitoring Report](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/02_Research/External%20Message%20Monitoring/External%20Message%20Monitoring%20-%20Research%20Report.docx?d=w213deba87972432f8b507a96eec47806&csf=1&web=1&e=boWpmC) highlights the top support ticket categories are all around different aspects of message testing during onboarding. However since Support doesn't currently have access to the right tools for addressing message errors nor the training of how to do so these issues are often escalated to an onboarding engineer causing a capacity strain on an already full capacity onboarding engineering team. By empowering our Support Team we can both speed up resolution of sender submission related tickets and decrease the reliance of escalation to an engineer to solve these types of issues. 

The top three actions needed to empower the Support are as follows:
1) Give Support Team members access to Azure action logs
2) Train Support Team on how to use Azure action logs
3) Train Support Team on how to read the sender/ receiver schemas/ transforms

### Risks/Impacts/Considerations
Risks: Giving Support access to Azure action logs should be done in a way where they can't change or modify the Azure system in any way if possible (read-only access for instance). 

### Dev Notes
If there is any technical documentation that would help the Support Team with answered submission related tickets please share a link in the comments section of this ticket

### Acceptance Criteria

- [ ] Support Team members given access to Azure action logs
- [ ] Support Team trained on how to use Azure action logs
- [ ] Support Team trained on how to read the sender/ receiver schemas/ transforms
