### ISSUE TITLE
Sender Notification System MVP Research

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#16382]
### User Story
As a ReportStream sender I want to be notified of the results of my submissions so I am assured my submissions are successful or if they need to be fixed and resent

### Description/Use Case
[External Message Monitoring research](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/02_Research/External%20Message%20Monitoring/External%20Message%20Monitoring%20-%20Research%20Report.docx?d=w213deba87972432f8b507a96eec47806&csf=1&web=1&e=zxXCCJ) shows 'All sender types want some form of confirmation that their actions (e.g., submission, fixing errors) were successful. Regardless of method, acknowledging their action and the result (success vs.  fail), enables them to have trust and confidence in not only their own actions, but also ReportStream.' The aim of this epic is take our first attempt at providing some sort of method for the sender to be notified of the success of failure of their submission. Some sender types including Flexion ETOR and the VA have asked for a specific type of message confirmation known as ACKs/NACKs following the LOI/LRI spec. Since we have committed to building out basic synchronous accept ACKs for ETOR this epic aims to clarify two aspects of setting up a notification system MVP before we start building:
1) Investigate if the LOI/LRI ACKs/NACKs system we are building meets the notification needs of all RS senders both in terms of method of notification and substance of notification message
2) Based on the results of the investigation write a short brief sharing how LOI/LRI ACKs/NACKs either sufficiently meets the needs of all senders and can be the basis of an MVP or where the LOI/LRI spec falls short of meeting our users needs and what else is required. If the latter, ensure the proposed new method does not contradict what's required for LOI/LRI

### Risks/Impacts/Considerations
Risk/consideration: It's possible how the LOI/LRI spec outlines providing ACKs for Flexion ETOR is at odds with what is best for all other senders. If that is the case we will have to highlight it and consider if ACKs/NACKs as a feature is different than the type of information we provide to all senders as part of a notification system.

### Dev Notes
This is primarily a design research task though engineering may need to be consulted to interpret the LOI/LRI spec
LOI/LRI ACK spec found here: TBD
ETOR ACK Requirements doc (WIP) here: https://cdc.sharepoint.com/:w:/r/teams/OLSS_ETOR_ReportStream/Shared%20Documents/ReportStream%20ETOR%20ACK%20Requirements.docx?d=we5a9fae68cd24c99a757f027562c1737&csf=1&web=1&e=3EdC64

### Acceptance Criteria

- [ ] LOI/LRI ACKs spec researched and understood
- [ ] ETOR ACKs requirements read over to see if it can work for all sender message confirmation needs
- [ ] Short brief written either confirming implementation of LOI/LRI ACKs/NACKS is sufficient to meet all senders needs or insufficient and another method is documented that doesn't contradict ETOR ACK requirements
