### ISSUE TITLE
Roadmap on website: FY25Q2 content update

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#16578]
## User story
As a user, I want to know how ReportStream is planning on improving so I can know if it is going to continue to meet my needs.

## Background & context
This ticket captures the content work of updating the roadmap with the latest updates as we wrap up Q1 and update our roadmap with Q2 deliverables.

- Content doc: [Word doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Website%20content/Public%20roadmap%20content/20250116_Public_Roadmap_FY25Q2.docx?d=w1ac27c09271e4bfb8e9765f6d60c70a2&csf=1&web=1&e=p2C0n9)
- Quarterly Progress Tracker: [Link](https://cdc.sharepoint.com/teams/ReportStream/Lists/FY25%20Quarterly%20Deliverables/AllItems.aspx?viewid=18f093eb-4307-4cfa-837c-ae75a99df500&env=WebViewList&npsAction=createList)

## Acceptance criteria
Content draft
- [x] Update "Objective" section with Q2 progress & what's up next
- [x] Update "Roadmap" section with Q2 progress & what's up next
- [ ] Content doc is eng ready (i.e. includes before & after component table)

Draft approval
- [x] Shared with Product for review
- [x] Shared with PO for awareness
- [x] Draft approved, or ticket for approval is created

**Comment by jillian-hammer** [comment]
@chris-kuryak the updated [roadmap on the website content doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Website%20content/Public%20roadmap%20content/20250116_Public_Roadmap_FY25Q2.docx?d=w1ac27c09271e4bfb8e9765f6d60c70a2&csf=1&web=1&e=cn655X) is ready for your review!

**Comment by jillian-hammer** [comment]
Eng follow-on ticket is [here ](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/17137). will hold on closing this ticket until PO is made aware tomorrow.

**Comment by jillian-hammer** [comment]
Chris captured feedback from the PO in the [content doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Website%20content/Public%20roadmap%20content/20250116_Public_Roadmap_FY25Q2.docx?d=w1ac27c09271e4bfb8e9765f6d60c70a2&csf=1&web=1&e=p2C0n9). Content finalized with eng ready guide. Closing!
