### ISSUE TITLE
[name of STLT] - UP (Shadow) Migration - Validate Test Data

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16828]
[STLT] = name of STLT

### User Story:
As a developer, I want [STLT] to be able to receive COVID data in the exact same format and contents from the Universal Pipeline, as it was from the COVID Pipeline. This will allow us to migrate the receiver without sending any test messages, enabling our decommission of the COVID Pipeline sooner.

### Description/Use Case
[STLT] is already receiving data from the covid pipeline. They will be onboarded to the UP where they will be receiving COVID data from SimpleReport. We need to make sure the message we generate from the UP passes the STLTs validation and matches the output from the COVID pipeline exactly. We can use SimpleReport to submit test messages through the UP for internal checking, but we will not be sending test messages to the [STLT] testing environment.

### Risks/Impacts/Considerations
- Since we will not be confirming test message contents with the STLT, we need to ensure internally that the messages meet STLT requirements before moving to production.

### Dev Notes:
Github Documentation: [LINK](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/onboarding-users/migrating-receivers.md)
- [ ] Ensure that Steps #1-#4 have already been completed
- [ ] Complete Step #5, but DO NOT send any test messages to the STLT.
  - [ ] DO NOT set up transport in staging
  - [ ] DO NOT communicate with the STLT
- [ ] Message from Send Step in CP matches message from Send Step in UP exactly
- [ ] Complete Step #6, but DO NOT send any test messages to the STLT.
  - [ ] DO NOT set up transport in staging
  - [ ] DO NOT communicate with the STLT

### Acceptance Criteria 
- [ ] Created and sent data using Simple Report
- [ ] Document differences between CP and UP COVID messages
- [ ] Review documented differences with the team
- [ ] Confirmed that all COVID messages sent through the CP from SimpleReport to the receiver will match exactly all COVID messages sent through the UP from SimpleReport to the receiver.
- [ ] When finished, tag Mikaelah, Chris, Victor, and Glenn in a slack post stating:
> [STLT] "Shadow Migration" is complete and is ready to be turned on in production
>
> Connection Type in Prod: [REST, SFTP, SOAP, etc]
>
> Positives set up to receive: COVID
>
> Negatives set up to receive: [List of Conditions]
>
> Format receiving: [HL7 or FHIR]

**Comment by abiphilipnava** [comment]
Just assigned and will be working on it on the next sprint

**Comment by abiphilipnava** [comment]
Script  Attached. It will creat an Hl7 file from the Covid pipeline and an hl7 from the UP pipeline, from the csvs files created fron the pipelines. It will then compare the two hl7 files and see if there are any differences . It will a create and output log files with the differences.
[validate_test_data.txt](https://github.com/user-attachments/files/18526208/validate_test_data.txt)

Just rename from txt to sh

**Comment by abiphilipnava** [comment]
It can be use for any STLT shadow migration to compare

**Comment by abiphilipnava** [comment]
[single_entry_withComparison_Archive.zip](https://github.com/user-attachments/files/18606059/single_entry_withComparison_Archive.zip)

Zip file with comparison reports

**Comment by chris-kuryak** [comment]
Waiting on response from SR

**Comment by wcutshall** [comment]
Using these files for comparison...
[comparison-files.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29PQ2c9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff1c3dc403ac6c0faa2e128e02ad5ec8fbd35183/comparison-files.zip)

**Comment by megreed1** [comment]
@sarah-g-parker to double check and we can move this forward.

**Comment by megreed1** [comment]
@sarah-g-parker to finish review of documentation
