### ISSUE TITLE
NY - Onboarding

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#1747]
The following items, generally in order, must be completed to successfully onboard a receiver to ReportStream:

* [x] Added to organization.yml
* [x] Added to organizations-local.yml
* [x] Added to staging settings table
* [x] Added to prod settings table
* [x] Added at least one receiver
* [x] Added OKTA group to download site
* [ ] Added customers to OKTA group for download site
* [x] Is customer contact made?
* What doc format are we supporting for the receiver (HLV, CSV, other)? **(Add comment below)**
* What transport(s) are we supporting for the receiver (SFTP, other)? **(Add comment below)**
* [x] Generate key pair and transfer public key to NY via AFT account
* [x] Tested ELR connection locally?
* [x] Tested ELR connection from Azure?
* [ ] Has the receiver accessed the download site?
* [x] Has the receiver been sent at least one test file?
* [x] Has the receiver signed off on file formatting?
* [x] Are there labs sending data?
* [ ] Has the receiver confirmed receipt of the data?
* [ ] Have the files processed successfully?
* [ ] Are we in production?

**Comment by jlusds** [comment]
Transport mechanism-
NYS Developed Software (UPHN Lite)
S3 (CDC Labs use this currently)

**Comment by jlusds** [comment]
Sprint 22 goal - what is the feasibility/timeline for this?

**Comment by MauriceReeves-usds** [comment]
Moving into "In process" because we have been cleared to move forward with them.

**Comment by MauriceReeves-usds** [comment]
Last communication from NY indicates that they don't have the SFTP site set up, and we need to have another conversation with them about that. @anshulkumar-usds @Adrian-Brewster

**Comment by anshulkumar-usds** [comment]
Checked with NY on 11/21 on next steps with creating SFTP path. No next steps for RS until further news from NY

**Comment by anshulkumar-usds** [comment]
NY needs us to deliver additional test messages to the same sftp location

**Comment by anshulkumar-usds** [comment]
Meeting scheduled with NY team on 12/6

**Comment by anshulkumar-usds** [comment]
There continues to be misalignment with NY on next steps for setting up a transport path. Following up internally in RS on our proposed solution.

**Comment by anshulkumar-usds** [comment]
NY was informed on 12/20 that "ReportStream can support key-based authentication alongside whitelisted IP addresses. Will that work on your side? Let us know if you have any specific instructions or requirements to get started."

Awaiting feedback from NY

**Comment by anshulkumar-usds** [comment]
Followed up with NY on 1/3/22.

**Comment by anshulkumar-usds** [comment]
After meeting with NY on 1/21, NY proposed connecting with their REST API. The spec for the connection is attached.
[https://app.zenhub.com/files/304423150/58d1d7dd-98b2-4887-b1a1-6716370b2e74/download](https://app.zenhub.com/files/304423150/58d1d7dd-98b2-4887-b1a1-6716370b2e74/download)

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds NY was inquiring on our progress for the connection. Just putting this on your radar.

**Comment by brick-green-agile6** [comment]
requested assistance with AFT account creation from NY

**Comment by brick-green-agile6** [comment]
karolina let us know that "CDC as an organization needs to be affiliated with the Health Commerce System". A quick google search tells me the Health Commerce System is NY specific. So my assumption is that an account will need to be created there. Then once that account is ready, apparently we will then be able to create an AFT account.

**Comment by brick-green-agile6** [comment]
Signed, notorized, and emailed copy of my forms for a secondary account to Megan Light and Mike Judd. They are going to have Dan Jernigan sign then mail to NY

**Comment by brick-green-agile6** [comment]
Got account created, working on verification now.

**Comment by brick-green-agile6** [comment]
Requested certificate from entrust. When/if they approve they'll send a link to access the cert. In the meantime I'll upload the CSR and key to keybase.

**Comment by brick-green-agile6** [comment]
Just uploaded the cert to NY! 

@greene858 If I did it correctly, then NY said they'll respond with the OAuth credentials

**Comment by brick-green-agile6** [comment]
Cert was accepted at NY. Received the OAuth client id and client secret. Uploading to keybase

**Comment by brick-green** [comment]
@Adrian-Brewster do we have the onboarding responses for NY?

**Comment by brick-green** [comment]
**header values**

format: HL7
labclia: 10DRPTSTRM

**Comment by sarahnw** [comment]
@brick-green @greene858 I've converted this to an epic. Please start creating tickets and adding them here for whatever is left to do.
