### ISSUE TITLE
React QA Checklist

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#2464]
## Background

The ReportStream web experience was rewritten in React. Before it can launch to production, the following requirements must be met: 

### Nav Bar
- [ ] Log in 
- [ ] Log out 
- [ ] Change orgs (if associated with multiple)
- [ ] Navigate to Daily data
- [ ] Navigate to About
- [ ] Navigate to How it works
- [ ] Collapses into overflow menu on mobile
### Daily data page
- [ ] Shows 30 most recent reports 
- [ ] Fields include: report id, date sent, expires, total tests
- [ ] Link to download csv for each row
- [ ] ELR secondary filter (when needed)
- [ ] Each report links to details page
### Report details page
- [ ] Shows: report type, total tests reported, report send date, download expire dates
- [ ] Button for download csv
- [ ] Link back to the daily data page
### About page
- [ ] Matches prod content
- [ ] Download button for 1 pager
- [ ] Contact us button mail to
### How it works
- [ ] Getting started matches prod content
- [ ] ELR onboarding matches prod content
- [ ] Data download website guide matches prod content
- [ ] Where we live matches prod content
- [ ] System and settings matches prod content
- [ ] Security practices matches prod content
### Misc
- [ ] Automatic log out after 15 min of inactivity
- [ ] Footer content and links match
- [ ] "An official website of the United...." banner
