### ISSUE TITLE
Update Upload.tsx to compile with typescript (e.g. remove `@ts-nocheck` flag)

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#2691]
**Describe the bug**
Upload.tsx requires a `@ts-nocheck` at the top of the file to compile. Remove that and get it compiling and working.

**tasks**

- [x] `@ts-nocheck` from top of file and get fix compiler errors
- [x] Manually test that it works correctly
- [ ] ~Refactor code to support unit tests as best as possible~
