### ISSUE TITLE
Validation Design

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2889]
As the Experience Team, we need some research and design for the Validation feature as outlined in this Epic [https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2095](url).

- [ ] Look at Colorado's validation python script
- [ ] Look at Washington's two sets of R scripts for data validation
- [x] Synthesis/discussion on common errors from calls & research notes
- [x] Document existing RS validation, cleaning, & filtering features
- [x] Zip Code research 
- [x] Flatfile.com
