### ISSUE TITLE
Admin tool to set up a PHD download site

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#312]
PRD: https://docs.google.com/document/d/1J-fymTtGsN2U1JQ8LAIqIsE4ONzu7nE9h0gMfOCHCy0/edit

Build a web experience that allows a public health jurisdiction to receive Data Hub report data and access relevant insights

Story
“As an internal admin, I can set up an account for a new geography”
“As a PHD, I can get access to the existing download site by having a conversation with USDS/CDC”

Requirements
Account set up (e.g. a set of users get access to the following settings)
Set user limitations (e.g. for DH Admin, PHD Admin, PHD Readers). 
Set an HL7 variant
Batching settings (e.g. Users within account receive emails based on a preferred notification cadence - hourly, daily)
Email settings (e.g. turn on or off notification emails)
Validation / QA (e.g. I can easily test to see if i’m seeing the appropriate data, and not the data you shouldn’t see; see test messages)

**Comment by shanewholloway-usds** [comment]
## Initial sketch of work breakdown

**Story:** _“As an internal admin, I can set up an account for a new geography”_

- [ ] Stand up Admin Settings API for organizations.yml -- #373
  - [ ] OpenAPI spec
  - [ ] Settings table in `prime_data_hub` database
    - Initialize db settings table from `organizations.yml`
  - [ ] Stand up Azure function endpoint
    - (reuse csv-downloads work)
    - in `prime-router/src/main/kotlin/azure/AdminSettingsFunction.kt` (or similar)
    - Validate Admin Role on every API call
    - Query/Update settings table from `prime_data_hub` database

- [ ] Stand up Web front-end UX for accessing Admin API
  - (reuse csv-downloads work)
  - [ ] USWDS integration
  - [ ] Okta Login
  - [ ] Confirm Admin Role
  - [ ] Select (submitter/recevier) account from collection of all accounts configured in the system
  - [ ] Display & update receiver basic information (name, description) using API

- [ ] CI/CD integration of Web front-end into prime-data-hub system
  - (reuse csv-downloads work)
  - [ ] API endpoint connection
  - [ ] Web static hosting endpoints


### Expected Outcome

- Internal admins can log in and see 

### In subsequent issues and sprints

- Account set up (e.g. a set of users get access to the following settings)
  - Display & update of receiver standard information
    - Email settings (e.g. turn on or off notification emails)
    - Set data schema (e.g. Users within account see data with XYZ fields)
    - Set geography limitations (e.g. Users within account have access to data based on geographical settings, such as state, county, zipcode)
    - Batching settings (e.g. Users within account receive emails based on a preferred notification cadence - hourly, daily)

  - Developer targeted admin tooling "shim" 
    - halfway between `organizations.yml` and complete onboarding support
    - e.g. YAML in the web, near direct API calls


##### Horizon

- Account set up (e.g. a set of users get access to the following settings)
  - Display & update of receiver advanced configuration
    - e.g. multiple delivery options
    - e.g. change credentials for SFTP, etc.

- Validation / QA (e.g. I can easily test to see if i’m seeing the appropriate data, and not the data you shouldn’t see; see test messages)

**Comment by jlusds** [comment]
Sweet! Overall looks good to me

**Comment by RickHawesUSDS** [comment]
Changed the title to HL7
