### ISSUE TITLE
Add meta tags/standard schema/etc for SEO

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#3181]
## Problem statement

We need to add meta tags and schema standards to help with SEO.

## What you need to know
Adding meta/schema tags will help with what shows up in search results and if links are shared via social media/etc.
From Ming: "can you help me understand why the RS page does not show up when you google it? The RS github page does and is the 2nd highest result behind SimpleReport." https://usds.slack.com/archives/C02HJ43AE8Z/p1635545478124500 

Looks like we have a meta tag defined that prevents robots, like the Google Bot, from crawling the website:
https://github.com/CDCgov/prime-reportstream/blob/64ac89dfbb71aff56be92617fbdd7bea01cbc425/frontend/src/_includes/head_tags_universal.liquid#L7

From Ron: "We do need that tag, but it should only be enabled in lower environments."

We should research what it will take to have marketing pages surface on search engines.

## Acceptance criteria

- [ ] Every page has basic meta and schema properties
- [ ] Public-facing pages have more detailed meta and schema properties (as needed)

## To do

- [ ] [Fill out common meta tags (schema.org)](https://schema.org/Organization)
- [ ] Write/reuse standard copy that'll show up in search results
- [ ] Write/reuse standard copy that'll show up in shares/social
- [ ] Create img that'll be use for shares/social
- [ ] Update robots.txt
- [ ] Add a `sitemap.xml` at the root and fill it in with data

**Comment by HeatherRienks** [comment]
@bgantick will make a follow on ticket for Eng efforts.

**Comment by kevinhaube** [comment]
Consider this "kinda blocked" by #6421 -- @drew-usds Lots of good info in there, check my closing comment. This will be natively integrated after a shift to a static site (Gatsby)!

**Comment by kevinhaube** [comment]
Also added `stale` because this could use a refresh; it's been over 1y

**Comment by chris-kuryak** [comment]
Old - closing. Doing new SEO work now.
