### ISSUE TITLE
Create a system for tracking data issues in the CSV pilot cohort 1

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#3975]
## Problem statement
Teams across report stream need a shared understanding and system for documenting and tracking data issues for the CSV upload pilot.

## What you need to know
For A1H there a number of ways that we were tracking the data issues coming up, but now we will have more senders tracking data issues will be more time intensive and creating another excel file that needs to be updated is not ideal. Here are the places where this information is logged for A1H. 
(1) onboarding time tracker
https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B937228F6-CB84-47F2-9395-99BE042E8EF3%7D&file=Onboarding%20Time%20Tracking.xlsx&action=default&mobileredirect=true
(2) Sender onboarding spreadsheet
(3) Zen hub epics created by Rick under prod test external
(4) Git hub - create issues
(5) VLB being cc'd on emails between Simmi and Rick

## Types of Errors
- Error message senders get on data submission
- Errors/tickets from PHDs when they get an error in their surveillance system from data delivered to them
- Emails between O&O and senders that bring errors to light

## Acceptance criteria
- a place where the data issues are being documented this can mean bringing data from other places into one place (i.e. research synthesis) or for program tracking. 
- the efforts to do this are not duplicative
- find a way to tag/label work across teams i.e. CSV upload pilot

## To do
- [x] met with Rick to discuss current process
- [x] meet with Rachel and Lori to plan process and system
- [x] Lori will work on a Metabase ticket to list errors for A1H (to start)
- [x] Talk to Sarah/Anshul about their tracking of data issues
- [x] Talk to Rick about types & frequency of errors

**Comment by victorialb-usds** [comment]
@rachelhanster and @loripusey can we schedule something this or next week.

**Comment by victorialb-usds** [comment]
o and o have data issue label

**Comment by victorialb-usds** [comment]
Anshul said "we're tracking those issues under the Data Quality Issues epic" setting up meeting for Monday 2/14

**Comment by victorialb-usds** [comment]
In meeting with Anshul and Sarah: mentioned other places: 
- Data issues: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3182
- Support Queue: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/2576
- Root Cause Analysis: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/2960

This is not a scalable way to do this but now have mapped out all the places for the CSV upload pilot.

**Comment by victorialb-usds** [comment]
Also sender onboarding tracking sheet is a source of data: https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B1653409F-6449-4D8C-8707-958767522CAD%7D&file=Sender%20Pipeline%20Onboarding%20Tracker.xlsx&action=default&mobileredirect=true&cid=24426abf-3ba9-46f4-9248-367276c55e02

**Comment by victorialb-usds** [comment]
@rachelhanster please review and then move to closed.

**Comment by victorialb-usds** [comment]
@rachelhanster here is link to same doc in sharepoint https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B04756168-CDC7-46CB-AF62-5D9ADA870F66%7D&file=bea7ccf2-70e6-4e81-af85-a29040872fb7.docx&action=default&mobileredirect=true
