### ISSUE TITLE
(Team Member) Dev/Engineer Onboarding Checklist

### ISSUE THREAD

**Issue by JGreenFearless** [CDCgov/prime-reportstream#4472]
Welcome to the ReportStream Pipeline Team!

Over the next few weeks you'll be spending a lot of time getting setup, learning about ReportStream and all its various components, and getting acclimated as the newest member on the Pipeline Team.  Below is a checklist of items for you to complete that will aid in that process - just check them off ass you go, and feel free to do these in whichever order makes sense for you!  Should you have any questions/concerns that are not addressed here, please feel free to reach out to any of the following team members:

- Pipeline Team Technical Lead @jimduff-usds 
- Pipeline Team Intermittent Scrum Master @smythe5 
- Pipeline Team Product Manager @JGreenFearless 

Happy learning!

### **Getting Started**
- [ ] [How to Setup Your Environment](https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/docs)
- [ ] [ReportStream Development Process](https://docs.google.com/document/d/1vSlVhU8-JofRAtd3EghnyY9NZUwp1KvUdJwhxsfKRYw/edit#heading=h.nkvrtu6c5dwv)
- [ ] Setup a 30min. meeting with the Pipeline Team Product Manager to review the following:
   - ReportStream Mission & Vision
   - Pipeline Team Overview (who's who)
   - Pipeline Team Objectives & Key Results (OKRs) and Key Performance Indicators (KPIs)
   - Review of Zenhub boards
   - Pipeline Team Roadmap review
   - Overview of scheduled Scrum Ceremonies and meetings
   - Open Q&A

### **What is ReportStream?**
   - [ ] [About PRIME ReportStream](https://github.com/CDCgov/prime-reportstream/wiki/About-PRIME-ReportStream)
   - [ ] [PRIME Mission Statement](https://github.com/CDCgov/prime-reportstream/wiki/About-PRIME)
   - [ ] [PRIME Vision Statement](https://github.com/CDCgov/prime-reportstream/wiki/About-PRIME)
   - [ ] [What is PRIME?](https://github.com/CDCgov/prime-reportstream/wiki/About-PRIME)
   - [ ] [What is Interoperability Modernization?](https://github.com/CDCgov/prime-reportstream/wiki/About-PRIME)
- [ ] [About ReportStream Team](https://github.com/CDCgov/prime-reportstream/wiki/About-ReportStream-Team)
- [ ] [How ReportStream Works](https://drive.google.com/file/d/1DuyKYw4VPJtuP4VelJeil5s37ppcJFUf/view?usp=sharing)
- What Problems are we trying to solve?
   - [ ] Watch ["Accelerating APIs in Healthcare:  A Year in Review and Momentum for 2021"](https://www.youtube.com/watch?v=TI8Kwz17OxE) 29:15 - 37:30
   - [ ] Watch ["A Roadmap to 21st Century Public Health Data Infrastructure"](https://himss.zoom.us/rec/play/60rXXwLf19dOu8IrBuwNyyLH8NORv04P_tkEgkQbuI2VuKBdd6GG0lccgGYiNOCAOZNHb1DopNG4yYr1.bOQfPV0HRdlTdo2G?continueMode=true) -- 1hr., 10min.

### **Additional Resources**
The following are links to additional documentation that may be helpful to you.  Please review at your leisure.
- [HHS Laboratory Reporting Guidance for Covid-19 Test Results](https://www.hhs.gov/about/news/2020/06/04/hhs-announces-new-laboratory-dat-reporting-guidance-for-covid-19-testing.html)
- [Types of Covid Testing](https://github.com/CDCgov/prime-reportstream/wiki/About-Types-of-Testing)
- Platforms and Applications for Sending Covid Test Results
   - [HL7 Electronics Lab Reporting (ELR) Guidance - Confluence Page](https://confluence.hl7.org/display/OO/Proposed+HHS+ELR+Submission+Guidance+using+HL7+v2+Messages)
   - [Electronic Case Reporting (eCR) History and Overview](https://www.youtube.com/watch?v=P5DS60jHQEw) -- watch the first 18min.
- [CSTE Reportable Condition Knowledge Management System](https://www.cste.org/group/RCKMS)
- [CSTE - Driving Public Health in the Fast Lane PDF](https://cdn.ymaws.com/www.cste.org/resource/resmgr/pdfs/pdfs2)
- [CDC Public Health Data Modernization - Executive Summary PDF](https://www.cdc.gov/surveillance/pdfs/20_319521-D_DataMod-Initiative_901420.pdf)
- [About Public Health in the U.S.](https://github.com/CDCgov/prime-reportstream/wiki/About-Public-Health-in-the-U.S.)
- [About Data Reporting](https://github.com/CDCgov/prime-reportstream/wiki/About-Data-Reporting#reporting-case-data-to-the-cdc)
- [About PRIME SimpleReport](https://github.com/CDCgov/prime-reportstream/wiki/About-PRIME-SimpleReport)
- [ReportStream CSV Upload Guide](https://github.com/CDCgov/prime-reportstream/wiki/ReportStream-CSV-Upload-Guide)

**Comment by RickHawesUSDS** [comment]
Are you asking people to attend the PRIME orientation session?

**Comment by JGreenFearless** [comment]
I didn't know that there was one!
Can you send me the invite so I can make sure new members are added
accordingly?

Thanks,

Jewel
