### ISSUE TITLE
(Admin) Dev/Engineer Onboarding Checklist

### ISSUE THREAD

**Issue by JGreenFearless** [CDCgov/prime-reportstream#4524]
Below is a checklist of items that will need to be completed prior to a new Dev/Engineer onboarding the Pipeline Team.

- [ ] Assign an Onboarding Buddy
- Ensure access is granted to the following systems
   - [ ] Github/Zenhub
   - Slack Channels
      - [ ] prime-reportstream
      - [ ] prime-reportstream-engineering
      - [ ] prime-reportstream-sender-pipeline
      - [ ] prime-reportstream-receivers
- [ ] Ensure new member is added to scrum ceremonies and meetings
