### ISSUE TITLE
Design blueprints, API senders: Customer-focused approach to ReportStream's whole digital service

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#5090]
## Problem Statement
Service design is a tool used to help an organization understand how a person interacts with a service now and find opportunities to improve. 

As an organization, ReportStream needs customer journey maps and service blueprints as visual frameworks to help us understand API senders and improve upon the digital service delivered from frontstage and backstage perspectives. 

Frontstage and Backstage are defined by what the customer sees

## Note
- [Sample Mural board](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1649439946587/2454a861c8d7bad98a8e33df8c55b094c5b6fa75?sender=u8081ec802748acf27d0d6445)
- [related, old initiative](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2779)

## Considerations

- [ ] A few blueprints that focus on the following:
- Front stage: customer journey or user experience
- Back stage: technical architecture
- Back stage: business operations that are seen by customers
- Back stage: business operations that are support processes, ones that interact with and support visible business operations 
- Organization's business model: how we create and deliver value to customers  

- [ ] Individually, each blueprint is organized by customer journey stage

- [ ] Holistically, the whole blueprint has front-stage and back-stage interactions and can be traced by x-axis (customer journey stage) and y-axis (front stage and backstage) 

- Operations team started a process map on API sender onboarding [here in lucidchart](https://lucid.app/lucidchart/1bb900ca-6a0e-41d1-9c86-d3529ea7e7fc/edit?page=0_0&invitationId=inv_e94a833a-e5a3-4784-96aa-23973f487065#)

## Acceptance criteria

- [ ] Customer journey map reflects reality
- [ ] Service blueprints have been reviewed by team and revised as needed.

**Comment by HeatherRienks** [comment]
Need to assign Andrea Chappelear to shadow @drew-usds on this Epic. Awaiting Andrea's username to be active in ZH.

**Comment by HeatherRienks** [comment]
@a-chappelear - adding you now that you have access to ZH! :)

**Comment by RakshindaAslam** [comment]
@RakshindaAslam - look at Product taking on some of the work for the backstage items.

**Comment by drew-usds** [comment]
Closing, re-factoring these in #6612
