### ISSUE TITLE
Publish "Built for you: New in Reportstream"

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#5118]
## Problem Statement
As a user of ReportStream, I want to know what newly built product information and feature has become available for me.

As an organization, ReportStream needs multiple ways to communicate about new offerings to users.

## Note
- One way is a public webpage, "Build for you: new in ReportStream"
- [Example 1](https://www.intercom.com/changes/en) and [Example 2](https://mailchimp.com/whats-new/)

## To Do

- [ ] Engineers make two changes to existing release notes operations: 1) link PR with original ticket that has user outcome(s) described; 2) Write PR title as [original ticket number] + [title]. detailed proposal [here.](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Releases/ReleaseNotesProposal.pptx?d=w961c0804374b48f98df066d3fcd3ce2c&csf=1&web=1&e=f0wVYU ) TLDR [one-pager here](https://cdc.sharepoint.com/:w:/t/USDSatCDC/ERjfi1u0TN5OubshesUvnSQBgOLOEO4Ig5XWQYfskgYh3g?e=6OqlRB).

- [ ] Product managers create user-friendly content, day after every sprint

- [ ] Experience team create and maintain webpage and ensures user-friendly content adheres to plain language and content style guidelines 

## Consideration
Best practices for formatting summarized release notes:​ 

- Title / Heading (keep it short, clear, and catchy so user feels compelled to read)​ 

- Company / Product Name (help user to know which product is being updated)​ 

- Version and Date (helps user to know when the changes were made)​ 

- New Features (descriptive text and images/videos of new features)​ 

- Fixed Issues (mention what was fixed and how they improve problems in past) 

- Improvements (include enhancements from last version)​ 

- Additional Resources (link up any how-tos or other resources)​

**Comment by RakshindaAslam** [comment]
Another example-JIRA release notes combining feature changes and bugs
https://confluence.atlassian.com/jirasoftware/jira-software-release-notes-776821069.html

**Comment by BerniXiongA6** [comment]
@HeatherRienks we noticed this is still open and O&O is also tagged. Looks like this work is done. Can you confirm and feel free to close if that's true. cc: @brandonnava

**Comment by kevinhaube** [comment]
Closing; this is handled in monthly tickets to publish updates now.
