### ISSUE TITLE
Add and Remove OKTA accounts for SDI Labs

### ISSUE THREAD

**Issue by rhood23699** [CDCgov/prime-reportstream#5178]
## Support Request
Received email from Afreen Rahman at SDI Labs stating his last day at SDI Labs will be 4/25/22, so add support@sdilabsinc.com to replace his account.

## Tasks
- [x] Add an OKTA account for support@sdilabsinc.com.
- [x] Add ReportStream & ReportStream appls to the new accouint.
- [x] Add the new account to sdilabs-ca OKTA group.
- [x] Remove Afreen Rahman's account by EOD, 4/25/22.

**Comment by rhood23699** [comment]
Removed Afreen's account on 4/15/22.
