### ISSUE TITLE
Setup an Incident Response Process

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#518]
As a security engineer, I would like to see the team setup standard operating procedures for incident handling. 

**Required by ATO**
- [x] Clear on call rotation
- [x] Run books on how to run a incident
- [x] Notification of the CDC operations center in the run book

**Practice**
- [ ] Game Day 
- [ ] Zero blame post-mortem
