### ISSUE TITLE
Implement cursor pagination: break down pages by # of results

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5286]
## Problem statement

Our users need to be able to easily access the next 4 pages directly using numbered page changing buttons. They also need to be able to step back to page 1 from any page in the list.

- [Design reference](https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?page-id=754%3A0&node-id=2954%3A21095&viewport=298%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=1150%3A470&show-proto-sidebar=1)
- [USWDS pagination behavior rules](https://designsystem.digital.gov/components/pagination/)

## Things to consider

No matter the approach, we'll need the response to include pointers and/or the data for the next pages. We can change the API to return these as another property, OR we can query them and parse it through front-end functions and interfaces. Either way, we'll actually have to query these results to get the pointers. 

CursorManager (`useCursorManager`) currently doesn't have page number support. Pages (`usePages`) has some support for it but only for a "current page" I believe. CursorManager should take over control of page numbers.

CursorManager dispatches need to be altered; right now they're set up to take the last item on the page as the cursor to the next page. This is the same logic we'll need to use to parse the next 4 pages cursors, THEN apply those in `CursorManager.next` which should be an array now, not a single string.  [See this comment.](https://github.com/CDCgov/prime-reportstream/issues/4779#issuecomment-1118729482)

## Todo

- [ ] API changes to return an array of four cursors representing the next four pages, OR front-end changes to parse incoming pages and store accordingly
- [ ] `useCursorManager` should take these changes into consideration when storing and processing through cursors
- [ ] `PaginationButtons` component should be re-designed to represent the new user experience and take advantage of the new cursor manager features

## Acceptance criteria

- [ ] Pagination component is updated from design in #4779
- [ ] A user can page backwards and forwards
- [ ] A user can see what page they are currently on
- [ ] A user can see and use buttons to navigate to the next 4 pages
- [ ] A user can access page 1 from any point in the list
- [ ] Results display accurately based on any sorting/filtering that is applied

**Comment by kevinhaube** [comment]
Updated the ticket to reference new design direction, repointed during sprint planning on May 10
