### ISSUE TITLE
Valueset editor: UI for valueset details page

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5442]
## Problem statement

As a team member of O&O team, I want to be able to view, add and update value sets via a user interface so that the change is easy to make and these settings changes don't have to wait on deployment.

## Acceptance criteria

- [ ] User is able to view a list of existing values for a selected value set
- [ ] User is able to update an existing value
- [ ] User is able to add an new value without creating a duplicate value for the same system and version
- [ ] Version field only allows number values or periods.

## What you need to know
Page/components for Valueset details page:
![Screen Shot 2022-05-10 at 11.07.25 AM.png](https://images.zenhubusercontent.com/5a6b4b784b5806bc2bc46da6/4928588f-bdba-439d-8377-0208fcadb08b)

Design file: https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=0%3A1

## Work breakdown

- [x] display with dummy data
- [x] api call and data display
- [x] table functionality for row editing
- [x] api call for edit
- [x] table functionality for adding row
- [x] api call for adding item
- [x] UI cleanup
- [ ] expand unit tests on Valueset Index

**Comment by kevinhaube** [comment]
Table changes needed are ticketed in #5460
Sort changes needed are ticketed in #5461
