### ISSUE TITLE
Validation/Upload Service for ReportStream

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5503]
## Problem statement

As a sender or an O&O team member, I want to test my data file in CSV, HL7 or RADx-MARS format and get user friendly responses to understand, identify and fix issues with my data.

As a sender or an O&O team member, I want to upload a CSV or HL7 data file through an authenticated web UI and transmit the data to configured receiver(s). 

## What you need to know

-  [Mural board for Validation Service Deep Dive with Options ](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1651702156098/60d77d324b3bf252c83d30f73f2cc201a59cc1eb?sender=u3fea607b46e84058d3224917)
- The service will be available in a UAT/Sandbox environment that will host live production code
- The initiative includes
   - Setting up Sandbox/UAT environment
   - Improving identified error msgs to more user friendly and actionable response
   - Providing a user-interface that allows file drag&drop or upload feature and display of response to the file
   - HL7, CSV, RADx MARS formats
   - Creating a gated experience with an expression of interest form for new users
   - Creating a gated experience for users being onboarded and O&O team

## Acceptance criteria
Validation Service
- [ ] A user is able to test a data file in any of the supported formats and get an error/success msg
- [ ] For the identified use cases, a user sees the new error msg that is user friendly and actionable
- [ ] Action log is stored for investigating issues

 Upload Service
- [ ] A user is able to upload a data file in any of the supported formats and get an error/success msg
- [ ] For a file with no errors, the data is transmitted to the configured receiver. If warnings exist, they are displayed on the UI.
- [ ] For a file with errors, the user sees the new error msg that is user friendly and actionable and the data is not transmitted.
- [ ] All data and action log is recorded BAU.
## To do

- [ ] Set-up Sandbox/UAT environment
- [ ] Identify use cases for improving error msgs
- [ ] Improve error msgs for identified use cases
- [ ] Build new or make available API end-points for HL7, CSV and RADx MARS formats
- [ ] Build new UI for the Validation only screen
- [ ] Build Expression of Interest form for new external user
- [ ] Integrate TOS ?

**Comment by RakshindaAslam** [comment]
@bgantick - can you add ticket(s) under this initiative for creating the sandbox/UAT environment?
@drew-usds @BerniXiongA6  - fyi for design for building the new validation service UI

**Comment by kevinhaube** [comment]
@CnoteNava @HeatherRienks @chris-kuryak This can be closed out. The only remaining item is another epic already tracking the External Validation Service effort. This, as I see it, is the creation of the _internal_ service, and that is complete. Further work on that service can be found on Platform's board. currently, it's API Error Codes updates!
