### ISSUE TITLE
Make FilterManager configurable on instantiation

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#5512]
## Problem statement

Right now, to set any non-default values in our `FilterManager`, we have to use `useEffect` with an empty deps array, which is frowned upon by our linter and also unnecessary mounting behavior. We should be able to pass a `Partial<FilterManager>` to provide defaults.

## To-do

- [ ] Instantiate FilterManager with partial object
- [ ] Pipe those into the filter hooks
- [ ] Filter hooks need to be able to take default values as params and set them

**Comment by kevinhaube** [comment]
#4859 will add in defaulting PageSize
