### ISSUE TITLE
Receiver-files CLI Tool

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#5799]
## Problem statement

Receiver files need to be accessed from time to time. This tool would mimic the sender files tool by retrieving the receiver files based on report-id or message-id.

## Acceptance criteria

- [ ] Full report is returned if report-id is set with receiver report id
- [ ] Report with single message is returned if message-id and receiver-name is set
- [ ] Reports in separate files for each message are returned if message-id is set but not receiver-name
- [ ] Reports in separate files for each message are returned if report-id is set with sender report but not receiver-name

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5799?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by sarahnw** [comment]
@brick-green when you come back... should this be an epic?

**Comment by brandonnava** [comment]
@brick-green Is this still important and something we want to do or close?

**Comment by brick-green** [comment]
Yeah I think we should still work this

**Comment by brandonnava** [comment]
@brick-green @oslynn If you're looking for a ticket to work on here's an older one we agreed we still want to get done
