### ISSUE TITLE
Build: API Programmer's Guide content migration into mark-down/web pages

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#5814]
THIS IS OLD CONTENT THAT NEEDS TO BE RE-WRITTEN. DELETE THIS HEADER WHEN THAT IS FINISHED

## Problem Statement

As the ReportStream team, we need to migrate the content from the programmer's guide (Word doc format) into mark-down on ReportStream.cdc.gov so that API users can more easily access up-to-date guidance.

## Background

- The existing guide is a doc/pdf. The doc is currently getting updated in several places (Sharepoint, github, RS website)
- The doc is currently versioned (sort of), but has gotten out of sync with multiple teams working on it.
- [Existing programmer's guide](https://reportstream.cdc.gov/assets/pdf/ReportStream-Programmers-Guide-v2.2.pdf), currently linked on [getting-started/.../overview](https://reportstream.cdc.gov/getting-started/testing-facilities/overview)
- As of #5858 we're just linking to the PDF from a page. We'll build everything here out on that

## Questions

- [ ] Is it better as "Programmer's guide" or "API programmer's guide"?
- [ ] Does adding API help with understanding? Or maybe even help with SEO?
- [ ] Is the current path,`/resources/programmers-guide`, good? (unless we need "API" in that?)

## AC

- [ ] Content is broken down from the revamped content (#5809), any unnecessary or duplicate things have been removed or linked to relevant pages.
- [ ] Programmer's guide lives as pages under `/resources`
- [ ] Page has breadcrumbs back to `/resources/*/*`
- [ ] Page uses our uswds sidebar + content area template [link to example]
- [ ] Individual chapters are in sidebar (don't worry about nesting sidebar content overall for `/resources` for now)
- [ ] Uses any existing diagrams/images in the guide (get originals if possible & scale/save for web). They aren't perfect but we can improve those later.
- [ ] Previous PDF path redirects to `/resources/programmers-guide`
- [ ] Share with the team! Keep Pipeline and O&O up to date on launch so they can start sharing that link instead of the PDF.

## To Do

- [ ] ...

**Comment by chris-kuryak** [comment]
This epic was originally under epic #5813 API Programmer's Guide to Web Content.
But to make the epic more manageable and not become an ever-expanding bucket of work, we're separating the Research side of the work from the Design and Building side of the work. This will become the epic for building the new API Web Content. It will be scoped and sized once the research (#5813) is complete.
