### ISSUE TITLE
CI/CD/Automating Deployments 

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#6403]
## Problem statement
Deployments are currently a resource intensive process that require the time of 3+ engineers for 1+ hours several times a week (6+ hours spent not working on ReportStream priorities per week). Let's figure out ways to reduce that time.

## Current process
The current process is outlined in [this sharepoint doc](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B30FBCC7D-02B3-4FDE-BBF2-3EEE980B11E1%7D&file=ReportStream%20Deployment%20Process.docx&action=default&mobileredirect=true&DefaultItemOpen=1&cid=012f1c1e-7e5b-440e-8c49-127511fcc1f6).

There are currently 19+ manual steps that an engineer must take in order to successfully deploy to production, and 1 automated action (not including automated actions that are triggered by a manual step).

## Pain points that we're solving for
- Backend build (long process that runs multiple times during deployment)
- Exception monitoring (need to log in to Azure in order to see exceptions on prod/staging)
- Looking for sends after deploys (a manual step that requires DB or metabase access)
- Running smoke tests (a manual step that can be time consuming)

## Proposed process
There are a few steps we can take to reduce or eliminate the need for manual intervention during deployments. These include, but aren't limited to:
- [ ] Automating smoke tests
- [ ] Combining and reducing build steps
- [ ] Piping exceptions to a place that requires less authentication for easier monitoring (slack?)
- [ ] Enhancing observability of a functioning system after deployments (monitoring sends)

**Comment by doug-s-nava** [comment]
just noticed that it looks like maybe frontend build / test / linting is not running on PRs when targeting a non master branch? see https://github.com/CDCgov/prime-reportstream/pull/6476

**Comment by jeremy-page** [comment]
@doug-s-nava Do you want it to run on any PR? It's easy to fix, the only draw back I see is this will catch the PR to merge it to Production and the Deployment branches.

**Comment by doug-s-nava** [comment]
yeah, that's a good point. Is there a way to run on every PR except those based off Production and Deployment?

**Comment by jimduff-usds** [comment]
Goal:  Get the ReportStream github actions build down from 20 minutes (or more) to under 5 minutes.

**Comment by brandonnava** [comment]
@jeremy-page @jimduff-usds Checking in on this. Did we hit the under 5min github action build down goal? Close the ticket?

**Comment by brandonnava** [comment]
@GilmoreA6 @oslynn you've both been doing some great deployment work. Any opinions on this being a priority?

**Comment by chris-kuryak** [comment]
@kevinhaube @stephenkao  Do you have any context on this issue and if we can mark it as complete? I noticed that both issues within this epic are closed.

**Comment by LaFreda1** [comment]
Awaiting response from eng sync
