### ISSUE TITLE
ME - Onboarding

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6406]
The following items, generally in order, must be completed to successfully onboard a receiver to ReportStream:

* [ ] Added to organization.yml
* [ ] Added to organizations-local.yml
* [ ] Added to staging settings table
* [ ] Added to prod settings table
* [ ] Added at least one receiver
* [ ] Added OKTA group to download site
* [ ] Added customers to OKTA group for download site
* [ ] Is customer contact made?
* What doc format are we supporting for the receiver (HLV, CSV, other)? **(Add comment below)**
* What transport(s) are we supporting for the receiver (SFTP, other)? **(Add comment below)**
* [ ]  Got credentials?
* [ ] Tested ELR connection locally?
* [ ] Tested ELR connection from Azure?
* [ ] Has the receiver accessed the download site?
* [ ] Has the receiver been sent at least one test file?
* [ ] Has the receiver signed off on file formatting?
* [ ] Are there labs sending data?
* [ ] Has the receiver confirmed receipt of the data?
* [ ] Have the files processed successfully?
* [ ] Are we in production?
* [ ] Update customerStatus flag in production settings to active

**Comment by sarahnw** [comment]
**Do you have an implementation guide we should follow?**​ Nothing specific to Maine; we follow the PHIN HL7 spec for ELR

**Do you accept HL7 v2.5.1?​** Yes, we prefer it
**What sending protocol do you use to accept files?​ 
SFTP (preferred)​ This is our preferred as well**
REST API​ 
AS2​ 
**Do you accept HL7 batch messages?​** Yes
**Would you like to receive the AoE questions?​** Yes
**1.  Frequency - we typically send files every two hours.​** That’s fine

If SFTP 

**How do we get credentials for an SFTP connection?​** Scott Snow can coordinate
**Do the credentials need to be rotated/do they expire?​** They don’t expire
**Do you need to whitelist our IP addresses before we connect?​** No
**What file path do we need to write files to on the SFTP server?** We’ll provide that info
**What value do you want in MSH-5?​** MEDOH

**What value do you want in MSH-6?​** MEDOH

**Do you require us to put our own identifier and CLIA in MSH-4?​** Yes, please

**Do you require a specific value in MSH-21-1 (Message profile ID)?​** We have facilities use “PHLabReport-NoAck”

**Do you want to receive OTC results? If so, how would you like to receive them?** No, thanks

These are the ones I (Scott) don’t have answers for yet -

Is there a limit on the number of messages in a batch?​ 
Do you require a specific file name format?​ 
Do we need to suppress the QST flag in OBX-29?​ 
Are there any other fields that are required? For example, the ordering provider information is sometimes missing, and some states won’t accept messages without it.​

**Comment by brandonnava** [comment]
@brick-green to check in and see if ready to onboard

**Comment by LaFreda1** [comment]
@sliu1000 can we reach out to Maine to see if their situation has changed?

**Comment by sliu1000** [comment]
@LaFreda1 It looks like the last correspondence was August 2022. I'll reach out.

**Comment by LaFreda1** [comment]
We have been meeting with Maine to see how we can assist with their onboarding. Our next check-in will be this month (November).

**Comment by chris-kuryak** [comment]
ME in production. Closing
