### ISSUE TITLE
KS - Onboarding

### ISSUE THREAD

**Issue by sarahnw** [CDCgov/prime-reportstream#6408]
The following items, generally in order, must be completed to successfully onboard a receiver to ReportStream:

* [ ] Added to organization.yml
* [ ] Added to organizations-local.yml
* [ ] Added to staging settings table
* [ ] Added to prod settings table
* [ ] Added at least one receiver
* [ ] Added OKTA group to download site
* [ ] Added customers to OKTA group for download site
* [ ] Is customer contact made?
* What doc format are we supporting for the receiver (HLV, CSV, other)? **(Add comment below)**
* What transport(s) are we supporting for the receiver (SFTP, other)? **(Add comment below)**
* [ ]  Got credentials?
* [ ] Tested ELR connection locally?
* [ ] Tested ELR connection from Azure?
* [ ] Has the receiver accessed the download site?
* [ ] Has the receiver been sent at least one test file?
* [ ] Has the receiver signed off on file formatting?
* [ ] Are there labs sending data?
* [ ] Has the receiver confirmed receipt of the data?
* [ ] Have the files processed successfully?
* [ ] Are we in production?
* [ ] Update customerStatus flag in production settings to active

**Comment by sarahnw** [comment]
Putting Kansas on hold

**Comment by oslynn** [comment]
@brandonnava, we should reach out to KS, again.  Do you want me to reach out to them?

**Comment by BerniXiongA6** [comment]
@brandonnava let's have a plan before reaching out. this one is more nuanced. Thanks for offering @oslynn but this should be escalated PRIME-wide which I'll do and get back to the team.

**Comment by brandonnava** [comment]
@oslynn To query metabase to find out what senders have data ready for KS. Brick suggests looking at some other data points while you're at it

**Comment by oslynn** [comment]
Good after noon,  Jeanne, Dane, Sam, Micheal,

Thank you for your time with meeting with us. Below please ReportStream Onboarding Questionnaire.

I am starting to work on your organization and setup ReportStream to route KS messages to you. 

Please answer following questions and return it to me.

PRIME Onboarding Questions

Engineering

 1. A copy of the Implementation guide.

 2. Do you require a specific file name format? - No

 3. Do you accept HL7 v2.5.1? - Yes

 4. What sending protocol do you use to accept files? - SFTP

 5. Do you accept HL7 batch messages? - Yes

 6. Is there a limit on the number of messages in a batch? - No

 7. Frequency -we typically send files every two hours. – That works for us

 

HL7

 1. What value do you want in MSH-5? - KSDOH

 2. What value do you want in MSH-6? - KDHE

 3. Do you require us to put our own identifier and CLIA in MSH-4? - No

 4. Would you like to receive the AoE questions? – We would take it but it’s not required

 5. Do we need to suppress the QST flag in OBX-29? – Doesn’t matter to us

 6. Are there any other fields that are required? – MSH.7 – Report Date/Time, PID.5 – Patient Name, PID.7 – Patient DOB, ORC.21 – Ordering Facility, OBR.4 – Ordered Test, OBX.3 – Performed Test, OBX.5 – Test Result, OBX.19 – Test Date/Time, OBX.23 – Performing Facility, SPM.4 – Specimen Source, SPM.17 – Collection Date/Time

 7. Do you require a specific value in MSH-21-1 (Message profile ID)? - No

SFTP
 1. How do we get credentials for an SFTP connection? – We will send it through email
 2. Do the credentials need to be rotated/do they expire? - No
 3. Do you need to whitelist our IP addresses before we connect? - Yes
 4. What file path do we need to write files to on the SFTP server? – This will be included when we send the credentials

REST
 1. How do we authenticate via API Key or Auth2?
 2. Do you need to whitelist our IP address before we connect?
 3. What is the URL endpoint for authentication?
 4. What is the URL endpoint for POSTing message?

Data Quality Filters

(How) Do you want to receive OTC results? - No
We look forward to working with you! Thank you!

-Ott Sathngam
CDCReportStream Engineer.

**Comment by oslynn** [comment]
Good after noon, Jeanne,

Thank you for your reply and so glad to see KS (my home state) onboards with CDC ReportStream.  
Below please find public IP addresses for ReportStream  and Development/Testing.

ReportStream public IPs address to white list:


158.111.236.0/24 (i.e 158.111.236.0, 158.111.236.1, 158.111.236.2, … , 158.111.236.24)

45.26.16.41   <— This IP is for Development and Testing.


I will start working on the setting/configuration for your production and staging feed.


Very respectfully,
-Ott Sathngam
CDC ReportStream Eng.

**Comment by oslynn** [comment]
It is DONE.
