### ISSUE TITLE
Track and display metrics and progression of test results sent in 

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6499]
## Problem statement

As a Receiver, I would like to see the following:
- how many test results are sent in by reporting facilities on a daily/weekly/monthly basis
- how many test results failed to be delivered to the receiving PHD and why
- How many results are sent by individual providers under a combined CLIA 
The purpose of this is to understand where the results are coming from, the expected volume and frequency and ability to monitor when the results stop coming in or fall outside the normal range and follow up to understand why.

As an internal admin, I would like to see the following:
- ability to track a single or multiple msgIDs to understand what happened to it and why it did not make it to the expected state 
The purpose of this is to help with addressing support tickets. 

## What you need to know
- Mural with initiative break-down https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660849046968/e257020850ab71f57b31120e27ec06203ae9c22b?sender=u3fea607b46e84058d3224917

## Acceptance criteria
- [ ] Receiver    
      - User is able to view metrics around test results sent in by facility by day/month
       - User is able to view last sent date for all facilities that send data to that PHD
- [ ] Internal admin 
        - User is able to track an individual test result across ReportStream for 
                    - success in being delivered or the reason why it was not delivered
                    - all associated dates, facility, organization, report ID and other related data

## To do
- [ ] Confirm the requirements and purpose for internal admin
- [ ] Scope out MVP and the rest of feature roll-out plan
- [ ] Mapping out services being provided under this initiative
- [ ] Information Architecture and navigation
- [ ] Wireframes
- [ ] Identify what information is available and what needs to be built for API

**Comment by RakshindaAslam** [comment]
cc @bgantick @drew-usds @a-chappelear 
@brick-green @sarahnw @BerniXiongA6 - O&O team - please review the requirements and A/C for internal admin sections and let us know if it needs to be updated/reviewed.

**Comment by kevinhaube** [comment]
cc: @CnoteNava @HeatherRienks @chris-kuryak  on the above :)

**Comment by chris-kuryak** [comment]
This looks like an epic that was created for the entire life cycle of creating a visualization for receivers to track and display where they are receiving test results/data from.

Moving this back to New Items since it needs to be re-scoped based on the results of our Single Message MVP.

**Comment by chris-kuryak** [comment]
Removing Single Message Tracker Epic #6992 from this epic since it is being worked independently from this larger effort.

**Comment by chris-kuryak** [comment]
Closing because this is an old epic that is currently being working on in other pieces (STLT Dashboard MVP for example). All issues in this epic are already closed as well.
