### ISSUE TITLE
[Message ID][Search][UI] View Results

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6659]
## Problem statement

As an internal admin, I would like to be able to search for a message ID and get the following information about that message.

## What you need to know
Mural with initiative break-down https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660849046968/e257020850ab71f57b31120e27ec06203ae9c22b?sender=u3fea607b46e84058d3224917

## Acceptance criteria

As an internal admin, I am able to:
- As a user with Admin privileges Navigate to an authenticated webpage for this feature under the "Admin" dropdown
- Enter a message ID and perform a search function
- If the message ID is not found, display a message that says "No results found"
- If results are found, display this information:
```
- message id
- sender
- date/time submitted to ReportStream (order by?)
- incoming report id
```
*Mock data for now

## TODO:
- [x] Add "Message ID Search" to the top navigation bar's "Admin" dropdown
- [x] Create "Admin only" message id search page
- [x] Implement the designs for displaying a message id query (use dummy data for now)
- [x] Add feature flag
- [ ] **[BLOCKED #6670]** Hook up the front-end to get the data from the newly created API (needs to be another tix)

## Designs
https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=411%3A1068

**Comment by RakshindaAslam** [comment]
@brick-green - can you give us the msg ID format and any constraints for input, like numeric only, etc. 
cc @bgantick

**Comment by brick-green** [comment]
@RakshindaAslam That field is a string so no format. Typically it's a GUID but not always.

**Comment by RakshindaAslam** [comment]
@brick-green - Thank you. Are there any max/min length constraints?
