### ISSUE TITLE
Aspira Health - API Sender Onboarding

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6872]
### What You Need to Know 

- [x] Terms of Service agreement signed 

- [x] Kickoff meeting completed 

- [x] Company’s intake form: ReportStream API – format HL7

Q: What is your expected message volume?

A: We currently report anywhere between 60-200 daily results

Q: Are you currently reporting to any other states outside of your state?

A: No just DE

Q: What is your current process for reporting COVID-19 data?

A: Manual entry through Redcap, located here: https://redcap.dhss.delaware.gov/surveys/?s=CH478NH4A7

Q: What state do you report to?

A: DE

 

### To Do 

- [x] create individual tickets for this epic 

- [x] RS team member who originates this ticket: complete the following when creating this Issue. 

- [x] RS team member who originates this ticket: add any dependencies, as needed

**Comment by brick-green** [comment]
Berni:
Completed intro/kickoff meeting on Wed 9/14/2022 with William Albanese

**Comment by brick-green** [comment]
Berni:
Ok to move to O&O backlog until they're ready to re-engage @BerniXiongA6 can follow up on email chain down the road.

**Comment by brandonnava** [comment]
@brick-green When will we know it's time to reengage?

**Comment by brick-green** [comment]
Oh I do not remember! @BerniXiongA6 Any memories here?

**Comment by BerniXiongA6** [comment]
When we completed Kickoff call, they said they were told that RS can help with system set-up. @brick-green explained that we help with integration to RS, but not set up. Aspira's EMR is Athena. They wanted to know if Athena currently integrates with RS. The sender contact William Albanese sounded as though he was pretty early on with their company, so it might be a good idea to reach out again after the new year unless we hear from them first. @brandonnava

**Comment by sliu1000** [comment]
Christopher from Delaware reached out for an update on the onboarding status. I responded as:

Hi Christopher,

I'm looking in through the notes in our system and see that Aspira's EMR is Athena.  We are waiting on WIlliam to confirm that Athena can integrate with ReportStream and have not heard back.  Please advise if you'd like us to reach back out for an update.

Best regards,

The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

**Comment by brandonnava** [comment]
@sliu1000 Didn't you share an update on this earlier this week? Are we still going to onboard them? Thanks

**Comment by sliu1000** [comment]
@brandonnava Yes, we've had some back-and-forth conversation with William from Atracare.  Please see below the communications:

Hi Sharon,

I'd like to add Nijanthan to this email chain.  He is a Project Coordinator for Athena and will collect all information and then assign this project to a team that will develop the necessary interface.

He is going to need a physical address for the CDC in order to get the process started, so if you could recommend the best address, that would be great.  Then he can instruct us on the next steps to build the interface.

Thanks,
On Wed, Jan 18, 2023 at 11:55 AM Report Stream (CDC) <reportstream@cdc.gov> wrote:
Hi William,

Can you please provide days and times that work for you to discuss this further? Also, if you could include a few of the Athena folks on the call that would be helpful.

Best regards,

Sharon
The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

From: William Albanese <walbanese@atracare.com>
Sent: Wednesday, January 4, 2023 1:17 PM
To: Report Stream (CDC) <reportstream@cdc.gov>
Cc: lalbanese@atracare.com <lalbanese@atracare.com>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Biskie, Joel (CDC/DDPHSS/OD/HITSSU) (CTR) <rtz3@cdc.gov>; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>; Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) <rwe7@cdc.gov>
Subject: Re: Aspira Health Kickoff Meeting
 
Yes!  Your timing is perfect as I met again today with the Athena team and we tried to figure out how to get the syntax into the EMR.  Their initial ask from the IT department yielded no responses.  They are following up.

In the meantime, if you can connect us with anyone that is able to assist with Athena or knows how to integrate the code, it would benefit everyone nation-wide on Athena as they attempt to integrate this interface.

We will be working on this and hope to get it going soon.

Thank you,

**Comment by sliu1000** [comment]
Updates:

Reeves, Maurice (CDC/OD/OCS)
Nijanthan AV <anijanthan@athenahealth.com>;William Albanese <walbanese@atracare.com>;Report Stream (CDC)
lalbanese@atracare.com;Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR)
Good evening Nijanthan,

My name is Maurice, and I’m the product owner for the Report Stream project. I apologize in advance, but I am just following up to confirm: are you saying that you aren’t able to send HL7 messages? Reading through the documentation for your software I saw a specification listed for the ORU_R01 message type, among others, here: https://docs.athenahealth.com/interfaces/guides/hl7v2-documents
HL7v2 Documents | Interfaces - Athenahealth
Health Level Seven ® (HL7) is a standard format used to exchange data within and across organizations. For more information on this standard, visit the HL7 website. athenahealth supports the following HL7v2 message types: Demographics - ADT. Specification and Sample Messages. Appointments - SIU. Specification and Sample Messages
docs.athenahealth.com

 

Is it possible for us to schedule a quick call over Zoom so we could discuss what we’re trying to accomplish, and see if we can figure out if it is possible?

 

Thank you very much,

Maurice

From: Nijanthan AV <anijanthan@athenahealth.com>
Date: Monday, January 23, 2023 at 15:57
To: William Albanese <walbanese@atracare.com>, Report Stream (CDC) <reportstream@cdc.gov>
Cc: lalbanese@atracare.com <lalbanese@atracare.com>, Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>, Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>
Subject: RE: Aspira Health Kickoff Meeting

Hello William,

 

I had internal discussion with my manager on this he confirmed we unable to procced via HL7 like external care facility. We have only option is via report builder tool also we have existing Global orders report name "COVID-19 Orders Report" which is in our report builder tool library. Please use the report builder tool to activate the existing report to your practice. Which is the option you would be using to establish the report using report builder tool. Thanks.!

Regards,

Nijanthan AV
Senior Analyst
(he/him/his
A picture containing logo
Description automatically generated
Global Infocity • Chennai • India – 600 096
athenahealth.com

**Comment by LaFreda1** [comment]
@sliu1000 can we reach out to Aspira to confirm if they are willing to move forward?

**Comment by sliu1000** [comment]
@TaneaY Hi Tanea, can we please assign a team member to follow up on this? Thank you Sharon

**Comment by OHoward2023** [comment]
Update:

To: William Albanese <walbanese@atracare.com>
Cc: Reeves, Maurice (CDC/DDPHSS/OD) <qva8@cdc.gov>;Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR)
Hi William,

Just following up on next steps. Were you able to connect with Athena Team? If so, are you still interested in signing up for ReportStream? If not, please reply to this email and we will close your ticket.

Please let us know if you have any further questions/concerns.

Best Regards,

Olivia
The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays
