### ISSUE TITLE
Message Tracker - Multiple Results

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6990]
## Problem statement

As an internal admin, I would like the ability to search for multiple msgIDs to understand what happened to it and why it did not make it to the expected state.
The purpose of this is to help with addressing support tickets.

## What you need to know
Mural with initiative break-down https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660849046968/e257020850ab71f57b31120e27ec06203ae9c22b?sender=u3fea607b46e84058d3224917

Wireframe for the ongoing work on this feature
https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=411%3A1069

## To do

- [ ] Add tickets for Research with O+O and Support Team to clarify what is desired on a tool that can search multiple message IDs at the same time
- [ ] Add tickets for Design work
- [ ] Add tickets for engineering work

**Comment by RakshindaAslam** [comment]
@HeatherRienks

**Comment by HeatherRienks** [comment]
@fmccaf1 - Please check with O&O as part of 6987 (usability testing) to see if this is needed. Thanks!

**Comment by kevinhaube** [comment]
@CnoteNava @HeatherRienks @chris-kuryak Labeled stale as we are not sure whether this upgrade is needed. Usability research on the mvp will discover this need if it exists. However, being a plausible next iteration, I'll leave it open for us!

**Comment by chris-kuryak** [comment]
@kevinhaube Thanks for this comment! Really helps with the clarity for me.

**Comment by chris-kuryak** [comment]
Moving back to New Items as it is awaiting scope and priority from our results with the Single Message epic #6992

**Comment by fmccaf1** [comment]
Unanswered questions from [ticket 6953](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/6953)

- What is the complete lifecycle of a ReportStream message? And, does a message's lifecycle always follow the same steps, or are there situations in which a lifecycle may differ from the norm?

- Can we (are we technically able to) include all steps of the message's lifecycle in the message detail view of this tool?

- Will "transport results" field be filled in when the tool is in prod? If not, what needs to happen to fill this field consistently?

- Lastly, the link to report id was not functioning at the time of these tests. Once the bugs present during testing are addressed, it would be wise to invite O&O engineers back to look at these screens and provide feedback.

I think we can move forward with designs for now, and save thinking through how to represent the message at different stages of the lifecycle. Question for the team is whether I should move forward with answering these questions next sprint, or if we should save it further down the road.
