### ISSUE TITLE
Public Validation Service - MVP

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6993]
## Problem statement

As a prospective sender with no access to the protected ReportStream website, I want to be test my data file in CSV or HL7 format and get user friendly responses to understand, identify and fix issues with my data.

As a RS onboarding engineer/support team member, I spend time validating files from prospective senders. Currently, I receive the files from prospective senders, run them through the validator, receive errors, communicate those errors back to the sender, the sender then sends a new file and the cycle repeats until there are no errors.
To mitigate this, we can make the Validation service available to unauthenticated users.

## Impact to ReportStream
- Automate more of the onboarding process and reduce the burden on O+O engineers/support staff

## What you need to know
-  [Mural board for Validation Service Deep Dive with Options ](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1651702156098/60d77d324b3bf252c83d30f73f2cc201a59cc1eb?sender=u3fea607b46e84058d3224917)
 - Provide user-interface that allows file drag&drop or upload feature and display of response to the file
 - There is an expectation of reusing CSV Uploader components and features and not a full new page
- Design details in https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6365

## Acceptance criteria
- [ ] User is able to upload a file in HL7 or CSV format on the public site without authenticating
- [ ] User is able to view success or error msgs based on the validation of the data file

## Consideration
- Can this be hidden behind a feature flag while we test it?
> Yes, but we will need to extend current functionality if we hope to selectively show it to only _some_ Sender organizations at a time. As of now, it's all Senders or no Senders allowed to see it. We can still have it isolated in Demo environments for research purposes!

## To do
- [ ] @fmccaf1 (design) to capture current Sender feedback on internal Validate tool through Demo environments
- [ ] @kevinhaube (eng) to work with @fmccaf1 (design) to form tickets for this Epic
- [ ] @kevinhaube (eng) to usher through refinement until ready for PRIME time (that's a CDC PRIME pun)

**Comment by RakshindaAslam** [comment]
cc @HeatherRienks

**Comment by kevinhaube** [comment]
Will present the following question in O&O sync on November 9th, 2022, to _possibly_ unlock more Validation work:
> Do we expect onboarded senders logging in to see this Validator? Is their access or functionality in any way improved for being authenticated (i.e. validating against any sender in their org, not just default?)

**Comment by kevinhaube** [comment]
Documenting next steps for this initiative:

- [ ] @fmccaf1 (design) to capture current Sender feedback on internal Validate tool
- [ ] @kevinhaube (eng) to work with @fmccaf1 (design) to form tickets for this Epic
- [ ] @kevinhaube (eng) to usher through refinement until ready for PRIME time (that's a CDC PRIME pun)

**Comment by chris-kuryak** [comment]
Current status: Going to test with at least 3 senders to see how it goes (possibly 2 in the next sprint, James Gilmore leading) and gather feedback.
