### ISSUE TITLE
Backward compatibility for full ELR for data displayed on reportstream.gov

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6994]
## Problem statement
With the Hospital Corporation of America getting ready to send full ELR data to Colorado via ReportStream API, the user needs to continue seeing the submission history and delivered data history (Daily Data) with no issues.
The purpose of this ticket is to test the full ELR daily data history and document any issues that need to be fixed.

## What you need to know
- Work is in progress for pipeline and is expected to be ready for testing in staging by week of Oct 17th for Daily Data and week of Oct 3rd for Submission History
 
## Acceptance criteria
The following outcome is desired:
- [ ] On sending data for multiple diseases via the full ELR endpoint, and delivering that data to Colorado PHD
- Daily Data UI for CO PHD shows details for all the records delivered in the dataset correctly.
- Submission History for HCA shows details for all the records delivered in the dataset correctly.
- [ ] Any reference to COVID 19 on the Daily Data or Submission UI are noted.

The following is documented:
- [ ] If there are COVID 19 references, they are documented as an output of this ticket
- [ ] Any work required to fix issues found is captured in tickets for future work

## To do

- [ ] Submit a test file for multiple reportable diseases on Staging via the new full ELR API endpoint and delivered to CO PHD
- [ ] Confirm that all the test results are accounted for in the  UI

**Comment by RakshindaAslam** [comment]
cc @HeatherRienks

**Comment by HeatherRienks** [comment]
@kevinhaube - let's discuss what remains on this one.

**Comment by kevinhaube** [comment]
@HeatherRienks Since there weren't that many changes, all changes have been taken care of, and in smoke testing, no errors occurred! This could be considered closed! 

Areas that still MIGHT contain some static covid references would be public site content.

**Comment by HeatherRienks** [comment]
FYI-@fmccaf1 - I am closing this ticket, per @kevinhaube's comment, but see note above about Covid references.
