### ISSUE TITLE
Vikor Scientific LLC - API Sender Onboarding

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7087]
### What You Need to Know 

- [ ] Terms of Service agreement signed 

- [x] Kickoff meeting completed 

- [ ] Company’s intake form: [paste info below this] 

 

### To Do 

- [ ] create individual tickets for this epic 

- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 

- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by BerniXiongA6** [comment]
Referred by Laura King / SimpleReport.
Berni is handling intake at this time - 10/20/2022.

Last correspondence from prospective API Sender - 10/20/2022:
> Hi Berni,
> 
>  
> 
> I will answer your questions next week when I come back on the clock but before we move forward with this process, I need Laura to onboard us with simple report. We have a deadline approaching with the state of Colorado that needs to be met by November. I appreciate your prompt response. Thanks!
> 
>  
> 
> Regards,
> 
>  
> 
> Marshall Chew, MSHI
> Sr. Health Officer Liaison
> Vikor Scientific LLC

Berni's initial intake email - 10/20/2022:

> Hi Marshall,

> 
>  
> 
> I apologize for the delay in getting back to you.
> 
>  
> 
> We're happy to provide you with next steps for the ReportStream API Sender onboarding process. 
> 
> If you could reply to all with answers to these questions, this will help us determine your needs/requirements:
> What is your expected daily message volume? 
> Are you currently reporting to any other states? 
> What is your current process for reporting COVID-19 data (i.e., CSV, HL7)?
> Preview our API Programmer's Guide:
> Please preview our programmer's guide, which details the technical steps and requirements for API data senders.
> If it's determined that ReportStream would be a good fit for your needs, we will start the enrollment process with your organization. 
> We look forward to hearing from you!
> 
>  
> 
> Thanks,
> 
> Berni

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 create ind. tickets before mid-November

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 and team can reach back out to Marshall of Vikor in early January 2023

**Comment by sliu1000** [comment]
@GilmoreA6 I think this is Inbios not Vikorscientific? If so, can I close this?

**Comment by brandonnava** [comment]
@sliu1000 to reach out

**Comment by sliu1000** [comment]
Sent a follow-up email to Marshall/Sender.  Waiting for response.

**Comment by LaFreda1** [comment]
@sliu1000 can we follow up here?

**Comment by sliu1000** [comment]
@TaneaY Hi Tanea, can you please assign a team member to follow up on this. Thank you. Sharon

**Comment by Jcavallo7** [comment]
Following up now.

**Comment by Jcavallo7** [comment]
*user states* 

Hi Juan,

We just completed our internal HL7 validations and are ready to start working on onboarding with you guys. What would be our next steps? Thanks!

Regards,
Marshall Chew, MSHI

**Comment by LaFreda1** [comment]
Hi Juan, please let them know that an engineer will reach out to them (and tag Ott) with the next steps to complete onboarding. Thanks!

**Comment by sliu1000** [comment]
@TaneaY can you please assign since Juan is on split shift today. Please cc Ott and Don

**Comment by cloudmagic80** [comment]
Branch. https://github.com/CDCgov/prime-reportstream/tree/oo/cloudmagic/7087
