### ISSUE TITLE
Revision Cycle: Validation Service

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7123]
## Problem Statment

The Validation service has been tested by O&O, and requests were made for changes to the UI to:
- Add consistency in messaging
- Update table display and information
- and make changes to the API error messages

## Resources

Florence's usability testing research mural: https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1666190212832/25f971cebb2d289837352dc406cb379ce362068c?sender=ua604735c5cf1162b042a4310

## To-do

- [x] Set up Epic with description
- [x] Set up individual tickets
- [ ] Prioritize order of importance
- [ ] Refine and point with engineering

## Tickets

> ⚠️ Not yet in priority order

- [ ] Complete #7124
- [ ] Complete #7125
- [ ] Complete #7126
- [ ] Complete #7127
- [ ] Complete #7128
