### ISSUE TITLE
SimpleHealthKit - API Sender Onboarding

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7132]
### What You Need to Know 

- **[Yes, signed on 10/14/2022]** Terms of Service agreement signed 

- [Originally scheduled 10/24 but cancelled due to staffing issues] Kickoff meeting completed 

- [ ] Company’s intake form: [paste info below this] 

- Name: Ramtej Pinisetty
- Job title: Program Manager
- Organization: Simple HealthKit Inc.
- Email address: statereporting@simplehealthkit.com, ramtej@simplehealthkit.com
- Phone number: +1 833 474 7745
- Organization that referred me to ReportStream:
- Public health department(s) I report to: California and Louisiana 
- Current reporting method(s): HL7, CSV

### To Do 

- [ ] create individual tickets for this epic 

- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 

- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 to reschedule sender onboarding kickoff -- will update epic once the kickoff meeting is confirmed

**Comment by BerniXiongA6** [comment]
Email from BX to sender - updated on 10/31/2022:

> Hi Ramtej,
> 
> Thank you for your patience. Beginning this week, our onboarding team has been reduced by nearly 40% and we expect backfills hopefully by the end of the calendar year. That being said, our backlog for onboarding new data senders to ReportStream is roughly 3 to 4 weeks. We can certainly schedule a kickoff meeting with your team this or next week; however, we won't begin verifying test files until mid-November at best.  
> 
> Would you still be interested in moving forward with becoming a ReportStream data sender, given this timeline? If so, we have some availability as follows:
> 
> Wed 11/2 at 2pm-2:30pm ET
> Thur 11/3 Between 12:00pm-1pm ET
> Thur 11/10 Between 3pm-5pm ET
> 
> Looking forward to hearing from you.
> 
> Best,
> Berni

**Comment by BerniXiongA6** [comment]
BX sent out this follow-up email post-kick-off to sender on 11/3/2022:
> Hi Ram, Linus, and Abdul:
> 
> 
> 
> Thanks again for joining the sender kickoff meeting with the ReportStream team today. 
> 
> 
> 
> As we discussed, here are the next steps:
> 
> 
> Terms of Service (ToS):
> If you haven't already done so, you'll need to sign this before we move to testing in production.
> To review our TOS, visit https://reportstream.cdc.gov/terms-of-service  
> After reviewing, sign the ToS agreement form at https://reportstream.cdc.gov/sign-tos
> Programmer's Guide: 
> Review the programmer's guide that Brick, our engineer, reviewed today: https://reportstream.cdc.gov/resources/programmers-guide
> 
> Generate dummy data (no PII):
> If you need assistance with this or have questions that the programmer's guide can't answer, please reply to this email and we can have you meet with a ReportStream engineer
> Our current backlog is out to 3-4 weeks, so you've got time to work on this!
> 
> Share the test file: 
> When it's ready, you can reply to this email and attach your sample test file (no PII).
> Our engineers should be able to take a first look at validating the test file in mid-late November.
> 
> Again, here's a screenshot of the onboarding steps slide we briefly discussed today (a detailed version of these onboarding steps is included in the Programmer's Guide above): 
> 
> 
> 
> We look forward to working with you!
> 
> Thanks,
> Berni
> 
> P.S. Ram or Abdul, could you forward this email to Linus as I don't have his email address.

**Comment by sliu1000** [comment]
Update from Sender:

Validation test file sent for review:

Hope you and your team are doing well. We want to move forward with the next steps for the onboarding process.
We signed the TOS and reviewed the programmers guide. We will proceed with CSV format. Additionally, the guide mentions
that we can use an existing format that we use to report to CA. We are providing a test file in that format.

Please let us know when we can expect validation to finish.

**Comment by brandonnava** [comment]
@brandonnava To bring into next sprint

**Comment by Jcavallo7** [comment]
Hello, 

User states: Hello James,

Thank you for reviewing our initial file. We made the necessary changes based on your guidance. Please take a look at our new file attached below. 

Please let us know if there are questions and what the next steps are when this file passes your validation.

Best regards,
Ramtej Pinisetty"

**Comment by sliu1000** [comment]
Update from Sender:

Hello James,

 As per your email, I have added the UTC offset to the following fields: date_result_released, test_result_date, order_test_date, testing_lab_specimen_received_date, specimen_collection_date. 

I have also generated the public keys via RSA and have attached them to this email as well. 

Staging: shk-rs-rsa-public-key.pem
Production: shkprod-rs-rsa-public-key.pem

Please let me know if anything else is required from our end.

Thank you and have a great day,
Abdul Ahmed @ Simple HealthKit

**Comment by sliu1000** [comment]
Update from Sender:

Hi James,

I wanted to check in to see if we can move to the next step. We are hoping to get this live by Feb 3rd. We have some new clients starting to test with us soon.

Best Regards,
Ramtej Pinisetty
