### ISSUE TITLE
[Message Tracker][API] Documentation 

### ISSUE THREAD

**Issue by ahay-agile6** [CDCgov/prime-reportstream#7170]
## Purpose

The API was written in tandem with the front-end for MVP to see if it works.

Add documentation and Open API specs for better understanding of how the API works and what it is for.

## Acceptance Criteria

- [ ] kdocs written for new db access methods
- [ ] kdocs written for azure MessagesFunctions class
- [ ] new endpoints added to the Open API spec
