### ISSUE TITLE
[Message Tracker][API] optimize message search api endpoint

### ISSUE THREAD

**Issue by ahay-agile6** [CDCgov/prime-reportstream#7262]
## Problem Statement
queries to the covid_result_metadata table are timing out on staging and production

## Acceptance Criteria
- [ ] queries don't time out...

## TO DO:
- [x] try adding an index on messageId to make the queries quicker (this already exists db/migration/V11__add_test_data_table.sql)
- [x] check if there are indexes on action_log to tracking_id (confirmed, there is one)
- [x] try using a targeted select statement for only the columns needed
- [ ] try adding a varchar_ops index on message_id in the `covid_result_metadata` table

## Notes:
- later in the day, the queries do not time out and they're actually blazing fast. my theory is that there is much less activity going on in the database. something must be locking it up, of which #7256 may mitigate
