### ISSUE TITLE
Organization and Global Feature Permissions APIs

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7390]
## Problem statement

As a PRIME Admin (a member of our Design team), I need the ability to show and hide features from specific organizations from the UI. And, as a PRIME Admin (a member of Experience team), I need the ability toggle a feature flag at the global level, allowing or disallowing access to a feature immediately and entirely.

## What you need to know

Our current access control (feature flag) system uses `localStorage` and hard-coded strings in the UI to operate. This is a low-level implementation that was added early on for hiding work in-progress due to twice-weekly deployments. Now, we aim to improve our capabilities.

The Experience team is working on the API for this front-end Epic. (#7456)

## Questions to answer

- Do we roll our own, or implement a feature flag service? Benefits and drawbacks of each?
**Roll our own. A service at this moment is more overhead than we know is worth it.**

## Acceptance criteria

- [x] Global availability overrides organization, always
- [x] The client application can retrieve a list of all flags and their attributes for PrimeAdmins
- [x] PrimeAdmins can alter the attributes and of feature flags
- [x] PrimeAdmins can add and remove feature flags
- [x] The client application can send an org name to validate the org has permission for a feature

**Comment by kevinhaube** [comment]
Need to split out platform work into its own epic and get design tickets included in our epic.

**Comment by chris-kuryak** [comment]
All issues complete. Follow up epic of Feature Flags v2 #7734 is already on the board that will address future features.
