### ISSUE TITLE
[Message Tracker] Immediate Improvements

### ISSUE THREAD

**Issue by ahay-agile6** [CDCgov/prime-reportstream#7413]
The big takeaway is that there is a difference between a "send" action and "batch" action.
Depending on which action type, anything related to the file needs a different label or wording.

## Improvement Notes:

1. **Receivers**: order by receiver name
2. **Receivers**: Incoming Report Id label should be "Outgoing Report Id" if the action type is "send"
3. **Receivers**: Incoming Report Id is mislabeled if action type is "send"
4. **Receivers**: Incoming File Name label is mislabeled if the action type is "send"
  - Should be "Outgoing File Name"
5. **Receivers** Incoming File URL is mislabeled-ish
  - there is a difference between "internal" files and "ready" files
  - difference between action type "batch" and "send"
  - label the difference "Outgoing File" and "Incoming File" is the internal RS format file
6. **Receivers**: Add Time stamp to "Date/Time" submitted information
7. **Sender**: Add "Date/Time" field
  - make sure to have the time stamp there, lol

## Acceptance Criteria

this refers to the message details page, i.e. https://reportstream.cdc.gov/message-details/29811087

- [ ] In the "Sender" section, add a Date/Time field
- [ ] Under the "Receivers" section, order the receivers alphabetically first by receiver name, then receiver service
- [ ] Under the "Receivers" section, add the timestamp to the "Date/Time" field
- [ ] Under the "Receivers" section, depending on the "action type" of the action log (receiver information):
  - [ ] label anything that has the "send" action to "Outgoing"
  - [ ] label anything that has the "batch" action to "Incoming" (shouldn't need to change )
  - [ ] this includes fields such as "File URL", "File Name", and "Report Id"

## Additional Notes:

How to activate the Message Tracker feature:
1. Log in as an Admin
2. navigate to /admin/features
3. type in "message-tracker" to the input text box and then click "Add"
4. In the "Admin" dropdown, there should now be the "Message Id Search" link

**Comment by fmccaf1** [comment]
Planning some work right now to look into file lifecycles and how they can fit into these designs. For now, please hold off on labelling based on the file url and whether it includes send, batch, receive, ready, other, or anything else. 

@chris-kuryak

**Comment by chris-kuryak** [comment]
Note to self: This is blocked by Design until after more research is finished, per Flo. It is unsure if the ticket as written is telling the engineering team to do the correct task.

**Comment by fmccaf1** [comment]
On reviewing this ticket again, @chris-kuryak, I think we can close it. All of these changes are design-related and the ticket for redesigning the screens includes almost all of these in the ACs [(7698)](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/7698)

My ticket for next sprint [(7735)](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/7735) addresses any ACs here that are not addressed in Jillian's ticket, 7698.
