### ISSUE TITLE
PA - Onboarding

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7414]
# What You Need to Know
In meeting with the PA Dept of Health ELR Team, we discussed how the state is not connected with RS currently. We agreed upon the solution to onboard PA with SOAP. This is the epic for onboarding PA Dept of Health.

# Acceptance Criteria
The following items, generally in order, must be completed to successfully onboard a receiver to ReportStream (if there are any steps within this that are not relevant to SOAP connection, let's please make those steps clear when we add individual tickets):

* [x] Added to organization.yml
* [ ] Added to organizations-local.yml
* [x] Added to staging settings table
* [ ] Added to prod settings table
* [x] Added at least one receiver
* [ ] Added OKTA group to download site
* [ ] Added customers to OKTA group for download site
* [x] Is customer contact made?
* What doc format are we supporting for the receiver (HLV, CSV, other)? **(Add comment below)**
* What transport(s) are we supporting for the receiver (SFTP, other)? **(Add comment below)**
* [ ]  Got credentials?
* [x] Tested ELR connection locally?
* [x] Tested ELR connection from Azure?
* [ ] Has the receiver accessed the download site?
* [x] Has the receiver been sent at least one test file?
* [x] Has the receiver signed off on file formatting?
* [x] Are there labs sending data?
* [x] Has the receiver confirmed receipt of the data?
* [x] Have the files processed successfully?
* [ ] Are we in production?
* [ ] Update customerStatus flag in production settings to active

# To Do

- [x] CREATE individual tickets to break down receiver onboarding process for this epic (see 5 steps below):
- [x] 1. Set up receiver connection (for SOAP)
- [ ] 2. Build receiver settings (to their requirements) 
- [x] 3. Validate test data
- [ ] 4. Validate production data
- [ ] 5. Go Live coordination

- [ ] ADD any dependencies to each individual ticket

- [ ] TAG this Epic inside each individual ticket

**Comment by BerniXiongA6** [comment]
Tagging @brandonnava @MauriceReeves-usds @brick-green for visibility -- I'm happy to add individual tickets to this epic once I follow up with PA in email to discuss next steps. Sounds like we would start working with them next sprint or the following. I'll leave another comment in this epic when I send out that follow up email to PA Dept of Health.

**Comment by brick-green** [comment]
PA provided documents. Attaching to epic for ease of access. Will also save in keybase and sharepoint.
[Disease Reporters Guide to Upload PA-ELR Messages.pdf](https://github.com/CDCgov/prime-reportstream/files/10383701/Disease.Reporters.Guide.to.Upload.PA-ELR.Messages.pdf)
[Disease Reporter Guide.pdf](https://github.com/CDCgov/prime-reportstream/files/10383697/Disease.Reporter.Guide.pdf)
[Add Designee Administration.pdf](https://github.com/CDCgov/prime-reportstream/files/10383699/Add.Designee.Administration.pdf)
[Reminder--Using PA-NEDSS with Edge's IE Compatibility Mode Infobyte.pdf](https://github.com/CDCgov/prime-reportstream/files/10383700/Reminder--Using.PA-NEDSS.with.Edge.s.IE.Compatibility.Mode.Infobyte.pdf)
