### ISSUE TITLE
Update Duplicate Detection logic

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#7442]
## Problem Statement:

We need to update our logic to allow detection of duplicates within a file that has not already been processed and to be able to reject individual messages within a batch file, not the entire file.

## What you need to know:

allowDuplicates: false does not strip out duplicate tests from within bulk submission if those messages have not already been processed. Also, the entire CSV file or HL7 batch message will fail if there is a single detected duplicate row.

## acceptance critera:
- [ ] Duplicate detection is able to reject single messages within batch files
- [ ] Duplicate detection is able to identify duplicates within a batch message that have not previously been received

## to-do:
- [ ] complete ticket #7150 to turn on duplicate detection for all senders

**Comment by BerniXiongA6** [comment]
Let's discuss in sprint planning if this is something that needs to come into this sprint yet @GilmoreA6 @brandonnava

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 create backlog refinement meeting and add this ticket in that convo cc: @brandonnava -- @GilmoreA6 can also bring up to UP team regardless of O&O's AC
