### ISSUE TITLE
Error Codes for HL7 Validator

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7453]
## Problem statement

After the prototype is complete (#5641) our first service to adopt error codes will be the HL7 validator.

## What you need to know

Lives in `hl7serializer.kt`

##### Key figures
- Prototype built by Penny
- O&O contacts in-the-know: Berni, Mo 
- Initiative managed by Kevin H.

##### History

We are embedding codes into error types with a focus on using these stable codes to produce a translation of more distorted/less useful messages like stack traces. Additionally, this opens up a plethora of creative use cases for API senders, such as translation to a foreign language they have a need to support, or even mapping to a better understanding of the error using our API Programmer's Guide's definition of the error code.

## Acceptance criteria

- [ ] All HL7 validation errors and warnings present codes for mapping messages
- [ ] Given codes can be mapped to an entry in the API Programmer's Guide
- [ ] Documentation for O&O is created, and a presentation/demo is given for support training purposes

## Design

See [PR 7688](https://github.com/CDCgov/prime-reportstream/pull/7688)

**Comment by chris-kuryak** [comment]
API Platform team's work is complete. New API codes have been created and documented by Arnej. Remaining work for the Exp team is in the Public Validator epic #5517 .
cc: @stephenkao

**Comment by chris-kuryak** [comment]
Oops, this is not on Experience board. Re-opened so Avniel and API team can disposition.
