### ISSUE TITLE
App Insights MVP

### ISSUE THREAD

**Issue by hannasage** [CDCgov/prime-reportstream#7518]
## Problem statement

Currently, ReportStream (RS) Product Managers (PdMs) have little to no insight as to 
whether the features they launch for the static website (cdc.reportstream.gov) and the 
authenticated experience, are meeting the needs of the end-users.

## Product vision

Providing quantitative metrics such as page views, button clicks and the like, will not only 
aid in future feature-development efforts, but also offers the ability to capture product 
growth overtime, allowing stakeholders to make well-informed business decisions about the 
product.

## What we know

React package docs for App Insights integration: https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript-react-plugin#use-react-hooks

Overall requests include knowing the org/roles of users performing actions, and an actionable insight to be gained from tracking a button event in the app. These requests led Jewel/Kevin to forming/documenting the AC for this Epic.

## Acceptance criteria

- [ ] Insights data is tracked with "soft" identifiers like a user's organization and role (MemberType)
- [ ] Insights sessionId is given to back-end with every API call
- [ ] Custom insights can be easily created with hooks and implemented in components
- [ ] Insight: Total page views by various membership data
- [ ] Insight: Total number of sessions by `memberType`
- [ ] Insight: Session duration by various membership properties
- [ ] Insight: Click events for numbered and "next/prev" pagination buttons

**Comment by chris-kuryak** [comment]
MVP Complete! Closing epic.
