### ISSUE TITLE
Dendi Inc. - API Sender Onboarding

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7582]
### What You Need to Know 

- [ ] Terms of Service agreement signed 

- [x] Kickoff meeting completed 

- [x] Company’s intake form: [paste info below this] 

 Background Information:

> Name: Lizzie VanSword
> Job title: Product Manager
> Organization: Dendi, Inc.
> Email address: integrations@dendisoftware.com
> Phone number: (205)616-0357
>  
> 
> Public health department(s) I report to: all states listed and a few not listed
> Current reporting method(s): CSV to each state
>  
> 
> We would be providing this service to all of our labs that we currently operate as the LIS for.
> 
> What is your expected daily message volume? 5,000 tests daily 
> Are you currently reporting to any other states? Our clients report to AL, CA, GA, CT, FL, IL, KY, LA, MD, MO, NC, NE, NJ, NM, NY, OH, TN, TX, VA, WV
> What is your current process for reporting COVID-19 data (I.e. CSV, HL7)?  CSV File upload by each lab

### To Do 

- [ ] create individual tickets for this epic 

- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 

- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by sliu1000** [comment]
Update from Sender:

Hi James,

We plan to use the 2nd Connectivity option, using the shared secret API key.
Please generate a secret key and send it via encrypted message. Dendi LIS will use that secret key with each submission.
Best regards,

Shatabdo Banerjee
dendisoftware.com

**Comment by sliu1000** [comment]
Update from Sender:

Hi James,

We tried to send the file to production and received the following errors.
"errorCode": "INVALID_MSG_PARSE_CODE" - for field patient_race (patient_race) - this maybe related to "Other Race" 
"errorCode": "INVALID_MSG_EQUIPMENT_MAPPING" - this is named as "Accula SARS-Cov-2 Test* " 
Please  let us know how we need to update these items and re-submit the file?

Best regards,

Shatabdo Banerjee
dendisoftware.com

**Comment by sliu1000** [comment]
Update from Sender:

Hi James,

We have submitted another file [NPI fix + Out of state patients] .  Please review and let us know :

"id": "362f066f-ae2e-4e81-927e-bdb33ca60421",

"submissionId": 24096910,

"overallStatus": "Received",

"timestamp": "2023-05-08T16:18:31.404Z",

Best regards,
Shatabdo

**Comment by sliu1000** [comment]
Update from Sender:

We sent the file today and received an error message.
Please let us know the issue?
The COVID LOINC code is https://loinc.org/94500-6


    "id": null,
    "submissionId": 24247993,
    "overallStatus": "Error",
    "timestamp": "2023-05-25T14:16:08.343Z",
    "plannedCompletionAt": null,
    "actualCompletionAt": null,
    "sender": "",
    "reportItemCount": null,
    "errorCount": 124,
    "warningCount": 372,
    "httpStatus": 400,

Error rcvd - 

"field": "test_performed_name (test_performed_name)",

"message": "No match found for test_performed_name (test_performed_name); please refer to the CDC LIVD table LOINC Mapping spreadsheet for acceptable values.",

"errorCode": "INVALID_MSG_EQUIPMENT_MAPPING"
