### ISSUE TITLE
An index of reporting Facilities

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7651]
## Problem statements

Facilities contribute test results to ReportStream, and we package them to send to STLTs in a nice clean "Report". Daily Data, the current way to see these reports, will let you drill down and see which Facilities contributed to a report. STLTs have shown **great interest** in being able to see it from the other end. **We will build an index of facilities that link to Facility detail pages for each facility listed.**

## Resources & info

Mockup: https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=4113%3A24718&t=OPRDPwECK1uB94Xa-0

## Acceptance criteria

- [ ] Receiver users can see a nav item to visit the Facilities page
- [ ] The page contains a table of facilities, sorted A-Z on Ordering Provider by default
- [ ] Table can be server-side sorted by Ordering Provider, Performing Facility, Submitter, and Most Recent Report Date
- [ ] Table support numbered server-side pagination with a default page size of 10 entries

**Out of scope for this ticket**

- [ ] Ordering Provider, Performing Facility, and Submitter can be clicked through to access details pages for the facility.

## To-do

- [ ] _[How are you going to complete this work? Feel free to use this section to make your todo list!]_

**Comment by chris-kuryak** [comment]
This is already being worked on as part of the STLT Dashboard MVP. Closing this ticket.
