### ISSUE TITLE
The contact and info section of Facilities detail

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7652]
## Problem statements

Currently in Daily Data, our Report-centric view of data for STLTs, we do not give any contact information for the reporting facilities. On our new Facilities Detail page, **we will compose two sections, one of which houses the contact info for a reporting facility so end-users can reach out on an as-needed basis.**

>For the curious mind, the other section is #7653!

## Resources & info

Mockup: https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=4046%3A23032&t=OPRDPwECK1uB94Xa-0

Each of the 3 main facility types (Ordering, Performing, Submitter) all have seemingly unique needs while sharing most of their common needs for the UI, per the above mockups.

## Acceptance criteria

The following demographic and statistical information is displayed in the Facility information UI

**All**
- [ ] Contact info
- [ ] Reporting since date
- [ ] All-time test count
- [ ] Average tests per report
- [ ] A chip to denote facility type

**Ordering facility**
- [ ] NPI
- [ ] Ordering facility name (this _may_ or _may not_ duplicate the page's title)

**Performing facility**
- [ ] Submitter for this performing facility

**Submitter**
- [X] No special requirements

## To-do

- [ ] _[How are you going to complete this work? Feel free to use this section to make your todo list!]_

**Comment by chris-kuryak** [comment]
Closing as we are currently redesigning the STLT dashboard MVP. This work will be re-ticketed if needed.
