### ISSUE TITLE
The contributions table of Facilities detail

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7653]
## Problem statement

The major request from STLTs was to see a list of contributions to a report from the Facility side. Each report may have 1 or more facilities that have contributed to its batch. To achieve this, **we will build a table of their report contributions, and compose it in the Facility details UI.**

## Resources & info

Mockups: https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=4113%3A24718&t=OPRDPwECK1uB94Xa-0

## Acceptance criteria

- [ ] Table shows report id, sent date, and facilities total contributions for that report in each row
- [ ] Report ID links to report details page
- [ ] A **full** copy of this data is downloadable as a CSV. If it's paginated, this may require an unpaginated request!

## Todo

- [ ] _[How are you going to complete this work? Feel free to use this section to make your todo list!]_

**Comment by chris-kuryak** [comment]
Closing as we are currently redesigning the STLT dashboard MVP. This work will be re-ticketed if needed.
