### ISSUE TITLE
Message ID tracker - Redesign based on internal usability findings

### ISSUE THREAD

**Issue by fmccaf1** [CDCgov/prime-reportstream#7698]
### Problem statement
This ticket is a follow-on from [6953](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/6953)
The purpose of 6953 effort was to identify what updates/new enhancements need to be made to make the tool useful for the O&O team for reducing the time spent in manual work today.

Feedback sessions with the O&O team are complete and have been used to identify some issues with the design. This ticket is for the design work to iterate on the original designs for the message id search tool. 

### Need to know
[Link to figma designs](https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=411%3A1068&t=HwP3APB89XEt8CvC-1)
[Link to Mural board with feedback session findings](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1671211214584/1ac88bde3c057ca7b43f6a7801025bd7adffb4ee?sender=ua604735c5cf1162b042a4310)

### Acceptance criteria
- [x] Discuss open questions with Eng: 1) Which reports should have the lifecycle status displayed?  2) Can/should transport result names be reformatted to be more legible? 3) What would be more helpful in list view?: link to incoming report or link to outgoing report? 4) Does file name help with scannability - is there any reason to keep it?

- [x] Add accordions or another way to move from top to bottom of page more quickly while scanning sections

- [x] ~~For receiver data, change "incoming" to "outgoing," i.e. Outgoing report ID, Outgoing file URL~~
_For now, just remove the outgoing/incoming text. We need more info on a file's lifecycle before deciding what gets the outgoing vs. incoming descriptor_

- [x] Move warnings/errors to more closely associate with the sender file: this could necessitate a "sender file section" which would include the message id searched, warnings and errors associated with that message, who sent it, incoming report id, and incoming file URL. Or, keep the page organization and move warnings/errors closer to sender info.

- [x] Allow users to sort receiver data by receiver name and date/time (this requires a grid of some kind)

- [x] Add exact time (hour: minute: seconds) to "date/time submitted"

- [x] Account for long transport result text (scrollable div? or some other design solution?)

- [x] For each message, include the incoming and outgoing file URLs

- [x] Check in with O&O to get feedback on designs

**Comment by fmccaf1** [comment]
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/d88bca96-86ee-4108-b14e-187d99712404)

**Comment by jillian-hammer** [comment]
Hey team, while revising the Message ID designs in response to O&O and Experience team feedback, I wanted to revisit removing the "Back" button (see below) to make it consistent with the Submission Detail page. 
![image.png](https://images.zenhubusercontent.com/639236212968fbce989b5d65/938fa34e-0025-4a5b-abc5-26722107c4ae)

I've included some alternate solutions below.

**Approach 1: Return to Message ID**
Similar to approach we're using for the Submission Detail page (#7712), but imo feels redundant with the browser's back button.
![image.png](https://images.zenhubusercontent.com/639236212968fbce989b5d65/9e21b66d-1a1b-42a7-bfd4-30730ee7a5f5)

**Approach 2: Breadcrumbs**
Common UX convention, and my preference if possible.

- Approach 2A: Child & Parent 
![image.png](https://images.zenhubusercontent.com/639236212968fbce989b5d65/e08acb94-b9f1-4d65-9057-95befa20698b)

- Approach 2B: Parent Only
Fallback if child breadcrumb isn't possible
![image.png](https://images.zenhubusercontent.com/639236212968fbce989b5d65/66de01ec-63ff-4e0c-8878-b428df9038df)

Let me know if any of y'all have thoughts!

**Comment by jillian-hammer** [comment]
hey @stephenkao @etanb (tagging y'all since you've been my message ID commenters, but anyone else can weigh in!)

let me know what you think of the above ideas ☝️ aside from this open item, the design revisions are complete from my end.

**Comment by stephenkao** [comment]
@jillian-hammer Sorry for the delay here!  I like Approach 2A as well, and it's something we should be able to do pretty easily.  What are your thoughts, @etanb?

**Comment by etanb** [comment]
Definitely like 2A the most! Big thumbs up to transparency of the site hierarchy in our breadcrumbs.

**Comment by jillian-hammer** [comment]
@stephenkao @etanb Great! thank you both. I'll finalize Approach 2A in the designs for handoff. Closing this ticket.
