### ISSUE TITLE
Redesign Message Tracker Details based on internal usability findings

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7754]
## Problem statement

We want to implement some changes to how the data is conveyed on the Message Tracker to improve the visual hierarchy and overall readability based on internal usability findings.

## What you need to know
- The new design includes two primary sections -- one about the Sender and one list the Receivers -- with more emphasis on actionable data.  See the [Figma](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=393%3A4746&starting-point-node-id=393%3A4746) for reference.
- Style Guide specs in [Figma](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=708%3A8503&t=ZQx7bNZo5AQSeFij-1)
- **NOTE:** Do not include Performing Facility field in this MVP.

## Acceptance criteria

- [x] All sections
   - [x] Divided by a horizontal border/rule
   - [x] All sizes and spacings match the design

--- 

- [x] Title section
  - [x] Page title is renamed to `Message ID Search`

---

- [x] Sender section
  - [x] Shows updated data:
    - [x] Submitter: currently `Sender Name`
    ~~- [ ] Performing Facility: net new field~~  removed from AC as this new field caused tech issues
    - [x] Performing Facility field is removed (even though it is shown in the Figma file)
    - [x] Incoming Report ID: keep as-is
    - [x] Date/Time Submitted: existing field (`submittedDate`) not yet displayed
    - [x] File Location: existing field (`fileUrl`) but needs to be parsed
    - [x] Incoming File Name: existing field (`fileUrl`) but needs to be parsed
  - [x] Warnings and errors are grouped in [Accordions](https://designsystem.digital.gov/components/accordion/), each with the respective counts
