### ISSUE TITLE
LabDAQ - API Sender Onboarding

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7769]
### What You Need to Know 

- [X] Terms of Service agreement signed 

- [X] Kickoff meeting completed 

- [X] Company’s intake form: [paste info below this] 

 Background Information on Sender:
> We are switching our LIMS from EVE to LabDAQ next month. LabDAQ doesn’t have the ability to create a .csv file with the specific values needed for the report. However LabDAQ is able to interface, HL7, so we wanted to set this up before we’re live with the new LIMS.

> Daily message volume should be about 50 initially, and we expect that to increase.

> We are currently reporting to TX, LA and MI.
> Currently we are reporting through SimpleReport with a .csv file.
> TOS Agreement Completed
> 

### To Do 

- [ ] create individual tickets for this epic 
- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by BerniXiongA6** [comment]
Updated 12/27/2022: Completed sender kickoff call today w/ @GilmoreA6 (presenter), @lizzieamanning and @BerniXiongA6 . Sender says they will work on establishing their connection capability before starting to onboard w/ us. We recommended that they reach out w/ questions or next steps to RS shared inbox email.

**Comment by LaFreda1** [comment]
@GilmoreA6 @sliu1000 any updates on this sender? Did they fully onboard?

**Comment by GilmoreA6** [comment]
@LaFreda1 to my knowledge they have not reached out to us since the kick-off. If I remember correctly they did not have the ability to send via REST API at the time and needed to explore how they would solve that challenge.

**Comment by sliu1000** [comment]
@LaFreda ***@***.***>@Gilmore, James ***@***.***> I’ll close this out and reopen if they reach back out.

Sharon

**Comment by lizzieamanning** [comment]
**Consolidated Notes**
Background Information on Sender:
We are switching our LIMS from EVE to LabDAQ next month. LabDAQ doesn’t have the ability to create a .csv file with the specific values needed for the report. However LabDAQ is able to interface, HL7, so we wanted to set this up before we’re live with the new LIMS.

Daily message volume should be about 50 initially, and we expect that to increase.
We are currently reporting to TX, LA and MI.
Currently we are reporting through SimpleReport with a .csv file.
TOS Agreement Completed

Q/A

LabDAQ does not support a connection to API- only TCPIP, VPN, SFTP
LabDAQ familiar with the LIVD mapping tool for CDC
Date/time: LabDAQ can do UTC offset no problem

Next Steps

LabDAQ to determine if there is a way for their system to make a REST API call before proceeding with RS
LabDAQ will reach out with questions to RS shared inbox

@GilmoreA6 was right, added notes for clarity posterity @LaFreda1
