### ISSUE TITLE
Hawaii - Receiver Onboarding

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7804]
### What You Need to Know 

- [ ] Terms of Service agreement signed 
- [ ] Kickoff meeting completed 
- Megan Light is currently POC on helping SR and RS schedule a receiver kickoff with Hawaii. See comment below for email thread.
- [ ] Receiver intake form completed: [paste info below this] 

### To Do 

- [ ] create individual tickets for this epic 
- [ ] RS team member who originates this ticket: add any dependencies, as needed
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" 
     - [ ] Epics: [select the epic for this receiver we're onboarding]

**Comment by BerniXiongA6** [comment]
Megan L. emailed Hawaii on 12/16/2022:

> Light Mueller, Megan (CDC/DDID/NCEZID/DPEI)
> jonathan.johnson@doh.hawaii.gov;denise.ok@doh.hawaii.gov
> Judd, Michael (CDC/DDPHSS/OD);Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR);Wallace, Jayna (CDC/DDPHSS/OD/HITSSU)
> Hi Jonathan and Denise,
> 
>  
> 
> I was forwarded the thread below, and am happy to hear you are reaching out to onboard for SimpleReport and ReportStream. I primarily work on the ELC HIS activities, but also work closely with USDS to help get ReportStream connections set up with public health departments.
> 
>  
> 
> Usually, the first step is to set up a kickoff call to walk you through what ReportStream is, how it works, what onboarding looks like, etc. As part of that, we also talk about SimpleReport so you can understand how it works for providers and facilities in your state. If you are already familiar with SimpleReport and ReportStream and want to move straight into onboarding, I am happy to facilitate that as well. Would you all prefer a kickoff call, or to move right into what is needed for onboarding?
> 
>  
> 
> Thanks!
> 
> Megan
> 
>  
> 
> ______________________
> 
> Megan Light Mueller, MPH
> 
> CDC/NCEZID/DPEI
> 
> wpa8@cdc.gov

**Comment by MikaelahD13** [comment]
Closing, work completed.
