### ISSUE TITLE
Public Key / Token Auth Tool

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#7862]
## Problem statement

Current Process/problem:
The sender emails us two separate public keys. Then those are stored in the database under sender settings. (Currently stored on staging and prod.) Then we send them an email that they can start testing (authentication) and includes the API endpoint to point to. And link them to API Programmer's guide.
This happens on almost every new sender (majority). Server-to-server auth.

Proposed solution:
- automate this on the authenticated side of the website where a sender can log in and upload their keys.
- Ideally after the data validation (tool) step

Out of Scope:
- Generating new keys

## Potential Impact
- Reduce time/burden on O+O Engineers onboarding

## What you need to know

- Exchanging keys via email can be tricky and a security risk
- Provide sender a tool to sender to update Public Key without need for RS support team or engineers

- [Internal Admin Tools Mural (priority #3)](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1660314801327/4b604589b88626292f8218ebd84a80f095a68da9?sender=u788ba8e0ebf56a2ad7d18905)
- Eng-ready [Figma File](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2167%3A21663&t=WLhbJIqQnfBOulOo-1)
- Eng-ready [Figma Prototype](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=2167%3A21663&scaling=min-zoom&page-id=2167%3A21637&starting-point-node-id=2167%3A21663)

## Acceptance criteria

- [ ] Sender can send in their keys (automated)
- [ ] Selecting a specific sender (if multiple exist)
- [ ] Sender can manage/change their key
- [ ] Staging/Prod key is tied to the environment they are logged into
- [ ] On auth side of website
- [ ] Informs Sender of next steps after successfully inputing key(s)

## To do

- [x] #8593 
- [x] #8704 
- [x] #8398 
- [x] #8805 
- [x] #8396 
- [x] #8397 
- [x] #8395 
- [x] #8400 
- [x] #7899 
- [x] #8133

**Comment by chris-kuryak** [comment]
Closing as this feature has launched.
