### ISSUE TITLE
End-to-end testing

### ISSUE THREAD

**Issue by stephenkao** [CDCgov/prime-reportstream#7866]
## Problem Statement
When we deploy new FE work, we don't have automated testing to ensure that the all of our pages/links/features work. 
We have Cypress available to us in our codebase, and we have a few very simple tests written for it, but we're not actively maintaining end-to-end testing.  

## Impact

- This could help smoke test larger UX changes and cut down on the human intervention needed for post-deployment checking, reducing errors in production and speeding up deployment checks
- Could positively impact DevOps (TBD)

## What you need to know
These are the high-level tasks we need to tackle before  it can be fully part of our process:
- [ ] Basic capabilities (login -- currently broken, switching between organizations, etc.)
- [ ] Write the post-deployment tests and backfill other tests
- [ ] Figure out data population/cleanup
  - [ ] `ignore` organization for production
  - [ ] API request commands
- [ ] Dockerize + CI/CD for running against pull requests

Future ideas
- [ ] Component testing
- [ ] Accessibility testing

**Comment by jpandersen87** [comment]
Replaced with #12143
