### ISSUE TITLE
Database Regressions & Optimizations

### ISSUE THREAD

**Issue by thetaurean** [CDCgov/prime-reportstream#7991]
## Problem statement

Various regressions have accumulated in the database and need to be addressed. These regressions impact database read/write performance and cause several issues in production endpoints. The bulk of the identified work involves index changes, but includes normalization and missing constraint issues as well.

These cross-functional changes will impact the schema, backend, and frontend; cooperation w/ other teams will be valuable. See POCs below and please suggest someone or add yourself!

Special thanks to @clediggins-usds for enumerating these over time and brain dumping them to me.

### Docs
- TBD

### People
- Organizer(s): @thetaurean
- Grand Poobahs: @jimduff-usds @clediggins-usds
- Platform Team: @thetaurean 
- Experience Team: @stephenkao (maybe?)
- Pipeline Team: @carlosfelix2 (maybe?)

## Acceptance criteria

- [ ] Improvements in performance are benchmarked in a scientific manner on a production/like system
- [ ] Deployments done in staging first and identically in production*
- [ ] **Deploy to staging before PR is merged**
\* a good way identified is to do the index changes manually assuring liberal use of IF EXIST clauses

## To do

Let's create separate tickets per functional issue and link them here, subdividing further as needed.

#### Insufficient indexes

- `DatabaseAccess.kt` `next_action_at` `next_action`
  - `fetchNumReportsNeedingBatch` and possibly others will benefit also

#### Excessive indexes

- `ItemLineage` has too many indexes
- `report_file` has too many indexes
- `checkRecentlySent`
  - would be slow if not for createdAt w/ backstop time
  - runs every minute per active receiver
  - could benefit from another index or query rewrite
- `SettingTable` has too many indexes

#### Bad indexes

🗞️ bad index! bad!
- there's a BRIN index on `report_file` that is bad
- bad index on `action_log`

### Normalization Issues

- Unneeded `covid_result_metadata` columns (`*_at`); they already exist in `action?log`
- `action_log`: `sending_org` and `sending_org_client` -> `sender_id`

### Missing foreign key constraints

- `Task` table on `report_id`
-  `Task` table on `receiver_name`

#### Query Set

What queries will we use to as our test set
- Should include changed and unchanged queries
- A subset of these will be documented for future or possibly regular testing
- These can go in individual tickets and be gathered

#### Tooling

What will we use to measure query performance
- Document this tooling for future reuse

### Deployment

What process will be used to deploy the changes
- Document this process for future reuse

**Comment by MichaelEsuruoso** [comment]
no longer needed
