### ISSUE TITLE
Innovar Healthcare - API Sender Onboarding

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8010]
### What You Need to Know 

- [ ] Terms of Service agreement signed 

- [ ] Kickoff meeting completed 

- [ ] Company’s intake form: [paste info below this] 

 

### To Do 

- [ ] create individual tickets for this epic 

- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 

- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by sliu1000** [comment]
Sender sent a test HL7 file for review today.  Still waiting for TOS agreement to be signed. Sent a reminder.

**Comment by oslynn** [comment]
Email from Innovar healthcare:

Hello Ott,

Unfortunately, the lab decides not to continue with this.

Thank you.
____________________________________________________

Thanks,

Cathy Fung

Software Engineer

Innovar Healthcare

445 Dexter Avenue
Suite 4050
Montgomery, AL 36104
(334) 544-0149  Direct Line
www.innovarhealthcare.com
