### ISSUE TITLE
INBIOS - API Sender Onboarding

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8024]
### What You Need to Know 

- [x] Terms of Service agreement signed 

- [ ] Kickoff meeting completed 

- [ ] Company’s intake form: [paste info below this] 

Name: Vik Bohra            
Job title: Program Manager
Organization: InBios International, Inc.
Email address: v.bohra@inbios.com & inbiosengineering@gmail.com    
Phone number: 206-245-9122
Organization that referred me to ReportStream: Not applicable
Public health department(s) I report to: Not defined
Current reporting method(s): csv format

### To Do 

- [ ] create individual tickets for this epic 

- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 

- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by sliu1000** [comment]
Update from Sender:

Hi James,

No problem, please find the attached 6 new csv files of the 6 new tests we pushed to your staging environment today. Please do review this at your earliest and let me know if everything on your end checkouts per the info in the csv files. We’ve lost a bit of time here, so if you can help prioritize this, I would greatly appreciate it.

Also, we received multiple errors when we pushed data from our iOS platform to your staging environment last week. Not sure if it was related to staging issues you were eluding to below. The error msg was requesting us to pass along 6 additional fields:

deviceName
patientCounty
performingFacility
patientState
specimenCollectedDate
testId
When we passed these 6 additional fields, then we received a 201 code, else errors were reported. These fields didn’t appear to be required per the guidance. But if something has changed, then please do share guidance on next steps. Thanks!

 

Regards,

Vik

**Comment by sliu1000** [comment]
Update from Sender:

Hi James,

Here is another sample of two submissions from the same patient. Please review and confirm that the data looks accurate on your end. Once you confirm, I can attempt to send additional samples from our two platforms from various devices with differing values. Thx!

 Regards,

Vik

**Comment by sliu1000** [comment]
Last email from Inbios (Marketa Hnilova).  Waiting for FDA approval.

Marketa Hnilova <marketa@inbios.com>
Vik Bohra <v.bohra@inbios.com>;Young, Tanea (CDC/DDPHSS/OD/HITSSU) (CTR)
Report Stream (CDC);James Needham <james@inbios.com>
5/1/2023

Our app is under FDA review at this moment. We will have better understanding of the future use after we receive the FDA feedback. We plan to follow up with ReportStream with more details then.

Thanks, Marketa

**Comment by GilmoreA6** [comment]
Closing as InBios has not been in contact for greater than 5 months
