### ISSUE TITLE
BD Veritor- API OTC Sender Onboarding

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8061]
### What You Need to Know 

- [x] Terms of Service agreement signed 

- [x] Kickoff meeting completed 

- [x] Company’s intake form: [paste info below this] 

Organization: Becton Dickinson
Job Title: Associate Director, Product Management
First Name: James
Last Name: Hunter
Email: james.hunter2@bd.com
State or Territory: California

Does this organization operate in multiple states or Territories? Yes
Does this organization agree to the ReportStream Terms of Service agreement? Yes

**Background Information:**
Reaching out from Becton Dickinson, BD, to initiate the process of sending BD Veritor-At-Home COVID-19 (OTC) test data to the CDC Report Stream.
Our COVID-19 at-home antigen test was authorized in October 2021 and is the only test system that uses the smartphone to image the test device and provide an objective analysis and result of the test stick. As a result, all of the tests processed on our platform are automatically shared with data reporting hubs. Since launch, we have been working with a vendor to send our test results to APHL Informatics Messaging Service (AIMS). 

As we look forward, we are interested in setting up an interface with CDC Report Stream. We have been working with Andrew Weitz and Krishna Julur at NIH RadX and were advised that CDC Report Stream would be the preferred MARS-compliant solution over the long term. 

Our developers have read through the API documentation and are ready to start the onboarding process.

### To Do 

- [ ] create individual tickets for this epic 

- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 

- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by sliu1000** [comment]
@brick-green  

BD Veritor has sent a test file for your review.  Can you please review and provide them feedback.  Also, they have provided you with their public key which is below.  Please let me know if you need anything else.

Update from Sender:

Thanks for setting that meeting up for us.  It was very helpful.
 
I’ve attached a file that contains our test/dummy hl7 message for review.  Please let us know if there are any issues with it. 
 
In addition, here is our public key (it won’t let me attach the file, so just pasting it here):
-----BEGIN PUBLIC KEY-----
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE7J4NhW3BOJzQR1PzJrbV36CLCIIJxTxD
Q2P+AxbxTIcaKT6KW+A9h8F1vcWWdzY4hxuuhcaD0IMQMgjHfsYqX8MX4mSdo34x
UGSjuuh8wta6KcP+8uSda1Gkb4yuBvf9
-----END PUBLIC KEY-----

**Comment by sliu1000** [comment]
Update from Sender:

Thanks very much Brick!

I’ll get started on implementing the two network calls in our app tomorrow and hopefully have a test message submitted in the next day or two.

Best,

Rami

signature_1651719900
Rami Burpee
Staff Engineer, Software
email: rami.burpee@bd.com

**Comment by sliu1000** [comment]
Update from Sender:

Hi all,

I’ve been trying to get the initial request set up to retrieve a bearer token, but not having any luck.  I keep getting a 401 Unauthorized response.  

No one specifically mentioned our client-id value, but I assumed that it is “bd-veritor.default” based on the scope value from Brick’s previous email example.   Maybe that is incorrect?  That’s the only thing I can think of.

Here is an example request that I made:

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/af50e349-31dc-4fb0-80a3-2f58e469ae6d)

The decoded JWT from that request’s client_assertion value is:

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/735d36f7-5857-4d81-a4dc-fcf090467ff0)
Thanks in advance for any help!

Have a great weekend.

Best,
Rami

signature_3599408005
Rami Burpee
Staff Engineer, Software
email: rami.burpee@bd.com

**Comment by GilmoreA6** [comment]
401 Errors BD-veritor
Gilmore, James (CDC/DDPHSS/OD/HITSSU)
rami.burpee@bd.com
Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR);DeGolier, Angela (CDC/DDPHSS/OD) (CTR);Report Stream (CDC)
Hi Rami,

I took a look at your last couple of attempts and everything looks good except the scope. The scope you are sending is "bd-veritor.default.report" and we are expecting "bd-veritor.*.report". Here is an example curl command:

curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "scope=bd-veritor.*.report&grant_type=client_credentials&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=<token-signing-secret>" "https://staging.prime.cdc.gov/api/token" 



The decoded JWT looks good from the screenshot I saw on the ticket but here is an example anyway for your reference:

{ 

    "header": { 

        "kid": "bd-veritor.default", 

        "typ": "JWT", 

        "alg": "ES384" 

    }, 

    "payload": { 

        "iss": "bd-veritor.default", 

        "sub": "bd-veritor.default", 

        "aud": "staging.prime.cdc.gov", 

        "exp": UNIX-time-goes-here, 

        "jti": "<jit-goes-here>" 

    } 

} 


Let me know if you are able to get the bearer token by changing the scope and if not we can troubleshoot further.

Thanks,

James

**Comment by adegolier** [comment]
Got confirmation from Rami that the suggested change allowed them to successfully fetch a token and submit data to the /api/waters endpoint.

**Comment by sliu1000** [comment]
@adegolier Hi Angela, i'm looking to update the sender onboarding tracker. Where are we on this onboarding. Did we every get them into production and if so what date?

**Comment by brandonnava** [comment]
BD Veritor no longer onboarding. Closing out
