### ISSUE TITLE
Website/Content Strategy Development

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#8142]
## Problem statement

As users increasingly rely on the site for their work with ReportStream, we need a comprehensive strategy that will guide content and design work on needed updates and new additions. With an eye on the goals of ReportStream being pandemic-ready, user-centered, and eventually owned by the CDC, this strategy will also support scalable, sustainable, transferable, and user-centered content throughout the RS experience

## Approach
- My approach prioritizes stakeholder involvement for alignment, user knowledge, and ownership. 
- Work is planned around phases that answer the following questions: where are we, what are our users' needs, are we meeting them, and what needs to change to better meet them? 
- A robust discovery phase leads to more effective and efficient planning and execution.
- It will take a holistic view of the web experience, rather than narrowing in on one user or feature. 
- This approach takes a content-first design mindset in focusing on implications of these questions on content that will set a foundation for further design work. 
- It will stay agile with the goal of moving quickly while not sacrificing being thorough and being flexible about how we are answering those primary questions.
- Activities current planned and the desired outcomes are details more thoroughly in the Mural linked below.

## Assumptions
- We have access to SMEs and stakeholders for their feedback and engagement throughout the process. 
- This work is a priority feeding into the goal of being user-centered. 
- These activities will gradually influence smaller pieces of work that will happen concurrently throughout the quarter.
- An implementation plan will be able to be completed for application next quarter.

## Out of scope
- More than one or two hours of research engagement with external users
- Content considerations outside of what is on/will be on the website (e.g. emails)
- Specific visual design decisions 

## Dependencies & risks
- Engagement availability from necessary stakeholders

## Open questions
- CDC stakeholders/future owners to involve in the process for foundation of future ownership

## What you need to know

- [Mural of general work roadmap/misc notes](https://app.mural.co/invitation/mural/nava4113/1673278109303?sender=uc55a7af3b66977fba12f5528&key=27b02b81-58ce-4f9b-a734-4aab2802ad5b)
- #7999 feeds into this work
- ...

## Definition of done/Acceptance criteria

- [ ] Work is planned around answering the questions: 

- Where are we?
- What are our users' needs?
- Are we meeting them?
- What needs to change to better meet them?

- [ ] Artifacts reflecting the findings have been created and shared with the wider team
- [ ] Action plan created based on answers to the above questions.

## To do

- [ ] ...

**Comment by audreykwr** [comment]
@lizzieamanning @chris-kuryak I'll begin adding tickets to this for this sprint.

**Comment by lizzieamanning** [comment]
@audreykwr Curious if you'd find value in adding any of the categories below: 

- Approach
- Assumptions
- Out of scope
- Dependencies & risks
- Open questions
- Links and resources
- Definition of done

**Comment by audreykwr** [comment]
I think some may be covered: 

- I think I have links that are relevant at the moment in there, but I'll try to add as more documentation is created along the way. 
- The broad definition of done seems like the ACs to me, but maybe those are too vague?
- Would approach be adding some more details to planned activities? Or let me know more about what you're thinking for that one. 
- Assumptions, scope, dependencies are good to think about, so I can add those when I can as a start

**Comment by chris-kuryak** [comment]
@audreykwr I like it!
I see you two are discussing perhaps a bigger question of "what info is required to be in an epic." Happy take that to a verbal forum for quicker disposition if easier, as we as a team have not defined hard guardrails yet.

We will keep this epic in the "New" column until you have finished putting all of the necessary issues into it.
Regarding Lizzie's comments above, I agree with those bullets and also feel like Acceptance Criteria should be a definition of "done". However, I would also say that the epic may not need Acceptance Criteria as the issues should have all of the AC's to describe "done". So happy to chat this out with y'all at your convenience.

**Comment by audreykwr** [comment]
@lizzieamanning @chris-kuryak added some things. Let me know what you think or what could be added/clarified.

**Comment by chris-kuryak** [comment]
Looks good to me @audreykwr !
The details (above the basics) of what Design wants to include is up to y'all.

Also, it appears that the Synthesis ticket could still use some work.

**Comment by chris-kuryak** [comment]
All issues complete.
