### ISSUE TITLE
Trusted Intermediary - API Sender Onboarding

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#8154]
### What You Need to Know 

- [ ] Terms of Service agreement signed 

- [X] Kickoff meeting completed 

- [ ] Company’s intake form: [paste info below this] 

 

### To Do 

- [ ] create individual tickets for this epic 

- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 

- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by jimduff-usds** [comment]
Will each ETOR sender need to separately sign the TOS?    Seems like we should ask Flexion to write a TOS, and have ours be a subset of it.

**Comment by LaFreda1** [comment]
@brick-green Is there anything else we need for this ticket right now?
