### ISSUE TITLE
Redesign Message Tracker Details Receiver Table

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#8157]
## Problem statement

We want to implement some changes to how the data is conveyed on the Message Tracker to improve the visual hierarchy and overall readability based on internal usability findings.

## What you need to know

- The new design includes two primary sections -- one about the Sender and one list the Receivers -- with more emphasis on actionable data. See the [Figma](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?page-id=283%3A1792&node-id=393%3A4529&starting-point-node-id=393%3A4746&scaling=min-zoom) for reference.

- Style Guide specs in [Figma](https://www.figma.com/file/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?node-id=708%3A8503&t=FKL6GYx93mG1f06N-0)

## Acceptance criteria

- [ ] Receivers section
  - [ ] Each Receiver's data is organized into a [table row](https://designsystem.digital.gov/components/table/) with the following columns:
    - [ ] Name (`receivingOrg`)
    - [ ] Service (`receivingOrgSvc`)
    - [ ] Date (`createdAt`)
    - [ ] Report ID (`reportId`)
    - [ ] File Location 
      - [ ] Parent (parsed from `fileUrl`)
      - [ ] Child (parsed from `fileUrl`)
      - [ ] File Name (parsed from `fileUrl`)
    - [ ] Transport Results (`transportResult` or `N/A` if null)
  - [ ] Each row is sortable by Name, Service, Date, Parent, Child, File Name, and Transport Results
  - [ ] Each table cell truncates longer content
  - [ ] Each table cell can be clicked to expand to reveal full content

**Comment by etanb** [comment]
For context, Penny, Jillian and I discussed next steps of this ticket and the design decisions we made going forwards: https://nava.slack.com/files/T03M7E63A/F04MMMKTPSS

**Comment by etanb** [comment]
For posterity, I'll paste the above notes here in case someone can't access the above:

Notes:
Average number of 9 receivers
Discussion of alternate cell expansion behavior for cells with long text fields
Current Figma design: Complex for engineers to build; difficult UX challenge 
Possible Solutions: Creating a horizontal scroll for the entire table; Create horizontal & vertical scroll within the cell itself; Add copy & paste button if needed 
Use Case: O&O engineers will want to expand the field to read the file name to look it up in Azure; O&O engineers will want to read the full Transport Results field (don’t need to copy paste it anywhere)
Warnings & Errors section
Tracking ID session long; unclear what it’s pulling from
Difficult to distinguish between rows
The error descriptions are very long
Decisions & Action Items
Etan: The File Name and Transport Results column will open in a modal to show the full, non-truncated text field
No additional UI needed 
Use default USWDS modal
Etan: Preserve column behavior as sorting one-at-a-time for this MVP
Jillian: Connect with Audrey about including the Tracking ID column and the Error Description field length
Penny: Restore default striped style to Warnings & Errors table

**Comment by chris-kuryak** [comment]
Increased to 5 points per Etan's revised estimate.
