### ISSUE TITLE
Chat with Support Team to determine what other Message Tracker features they want

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8188]
## Problem statement

Sharon Liu had mentioned wanting date/time filters and a wildcard search on the Message Tracker Feature, as well as some other possible filters. The goal of this issue is to meet with Sharon to determine what features she would like to see and why.

## What you need to know

- Sharon responded via a Slack message with

> We may not know the MessageID and only know a date range or something else. The ability to have a "contains" or "wildcard" would be nice.

## Acceptance criteria

- [ ] Meet with Sharon Liu to determine what features she would like added to Message Tracker feature and why
- [ ] Capture and link to the findings from that conversation on this ticket
- [ ] Inform PO when that is complete so they can begin refining with engineering

## To do

- [ ] Schedule meeting with Sharon Liu
