### ISSUE TITLE
FAQ Content Update

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#8492]
## Problem statement
The website serves as the first line of defense in answering a visitor's questions. Both senders and receivers currently email the support team with common questions that could be answered with improved content on the ReportStream website. Allowing users and visitors to answer their own questions on the website would reduce the time the Support team spends answering common questions via email. So ReportStream should answer the most common questions on the website.

Since the FAQ has not been updated in a while, this epic is to update the FAQ with answers to the most common questions.

## What to Know
- While the FAQ page is not ideal for content like this, the scope of this epic is to only add content to the existing FAQ page so that the support team can direct people to it as the first line of defense in answering common questions. Improvements to the FAQ page and how it works can come in the future.
- Existing research on determining which kinds of questions are the most common [this Mural](https://app.mural.co/t/nava4113/m/nava4113/1670249995005/9d9bf4d24b41e32f1aa05494c2cf363a8dc345f5?sender=u788ba8e0ebf56a2ad7d18905) with the most common questions shown in the 
- [The most common questions and answers](https://app.box.com/s/mj0wg2haui7v6zq964efigbg934slkld) highlighted in blue
- Connect with Chris Kuryak regarding the previous research and what the final status was
- Design team will develop the content for new questions and their corresponding answers in collaboration with the Support team

## To Do (optional)
- [x] Chris and Audrey meet with Sharon Liu to determine how this would best help them
- [x] Chris and Audrey meet to discuss what would be next steps

## Ready?
- [x] Epic Reviewed with team
- [x] To the best of our knowledge, all issues added and epic is ready
