### ISSUE TITLE
Base10 Genetics - API Sender Onboarding

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#8703]
### What You Need to Know 

- [x] Terms of Service agreement signed 

- [x] Kickoff meeting completed 

- [x] Company’s intake form: [paste info below this] 

 

### To Do 

- [ ] create individual tickets for this epic 

- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 

- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by oslynn** [comment]
An initial email requesting for sample hl7 file for validation sent last week.

**Comment by oslynn** [comment]
Done
