### ISSUE TITLE
Covx - API Sender Onboarding

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#8705]
### What You Need to Know 

- [ ] Terms of Service agreement signed 

- [ ] Kickoff meeting completed 

- [ ] Company’s intake form: [paste info below this] 

 

### To Do 

- [ ] create individual tickets for this epic 

- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 

- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by rnz6** [comment]
5/16: Follow-up email from CovX

Hi James,

I hope you’ve been doing well; I’m just reaching out to check if California has provided any additional feedback and if this integration has been approved by them.

Thanks,

Nathan Farmer
