### ISSUE TITLE
Message Metadata Search Via Lineage Improvement 

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#8733]
### User Story:
**More generically:** As a user of ReportStream, I want the ability to quickly retrieve message "metadata" associated with a particular message.

**More specifically:** As a STLT, I want to get a list of facilities that appear in a range of DELIVERED reports.

### Description/Use Case
Presently, we have a stored function in the database, called report_facilities, that takes a report and for each item in the report, recursively traces an item's lineage until it gets the message that belongs to the report that is linked to the covid_metadata_table and then uses that data. This does not scale and is not performant.

We need a more efficient way to get metadata, whether it be in covid_metadata_table or somewhere else (ElasticSearch), given a delivered report or set of delivered reports.

#### Idea One: Stamp every item_lineage entry in the DB with the report_id/index_id that is linked to the associated metadata

We can update the `item_lineage` table to contain new columns called `original_report_id` and `original_item_index`, or something like that.  These columns would contain the information of the report that is connected to the `covid_metadata_result` table, which may not necessarily be the very first report that spawned all the other reports. As data flows down the pipeline from parent to child, when creating a row in item_lineage, we would simply just copy over the two proposed columns from the previous child entry, that way every item will have this information. This design effectively creates a shortcut link between any message in a chain of reports and the report/index that is tied to the associated metadata, improving the performance of `report_facilities` and other such queries by eliminating the need to trace the chain.

### Acceptance Criteria

We see this as a 3 step process, with the first step already completed.  This ticket is to do steps 2 and 3:

- [ ] 1. Given a date range search criteria, find the set of delivered report_ids that meet that criteria.  (In theory this is done - its the `/api/waters/org/ORGNAME.SENDERNAME/deliveries`
API endpoint - just need to doublecheck it works well.)
- [ ] 2. Given a report ID or set of reportIDs, I can retrieve a set of (report_id, index) that are linked to metadata
- [ ] 3. Given a set of (report_id, index), an API endpoint can return the metadata associated.   Initially, we'll build this just for covid_result_metadata only, but the idea is that the first two steps are generic; the third is data-use-case specific.

Possible further work to modify step 3:

- [ ] To accommodate the specific user story outlined above, we need to ensure the specific query is performant. This might mean indexing the facility column in covid_metadata table or creating a new table to store the facilities.
