### ISSUE TITLE
Create pilot expectations + checklist for sender & receiver

### ISSUE THREAD

**Issue by jsutantio** [CDCgov/prime-reportstream#8778]
As a sender and receiver of ELR data, I'd like to know what to expect with regards to my participation in the ELR pilot, so that I can appropriately allocate time and resources to this effort.

### **Background & Context**
Create a sendable word document that convey's the high level expectations, responsibilities, and timeline of the ELR Pilot engagement with the Sender + Receiver. This should contain a reiteration of the pilot's goals and be easy for the user to read and reference throughout the engagement.

### **Working Links**
- [ELR Partner Outreach Plan](https://docs.google.com/document/d/1QycMnAiOk5YlbrTdmtILqLvELwYaHU_dXkD8U0DVpqA/edit?usp=sharing) (WIP)
- [ELR weekly meeting notes](https://docs.google.com/document/d/1k-xAiO91nwFdOpTkDA4D4CNt9RmXIOO-m_Km_O6Qtbo/edit?usp=sharing)
- [Service blueprint](https://app.mural.co/t/nava4113/m/nava4113/1672148125717/f376adefc22f136c60e40cb9f60b1b74ef4ee43d?invited=true&sender=u8e85df6f9eec764c4bfd6788)

### **Acceptance Criteria**
- [ ] Conveys detailed goals of the pilot
- [ ] Outlines roles and responsibilities (on both ends, but specifically what we are asking of the Sender)
- [ ] Conveys major milestones and lead times
- [ ] Exported as a pdf or word doc; saved in CDC PRIME RS SharePoint
- [ ] Linked within the [ELR Partner Outreach Plan](https://docs.google.com/document/d/1QycMnAiOk5YlbrTdmtILqLvELwYaHU_dXkD8U0DVpqA/edit?usp=sharing) for documentation purposes
- [ ] Emailed by ReportStream email to the Sender (cc'ing the appropriate RS members) alongside technical questions
