### ISSUE TITLE
Lower Support Ticket Time to Resolve in Key Categories

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#8840]
## Goal
We have two support related OKRs for Q2
1) 75% of support tickets handled by tier 1
2) Lower Support Ticket Time to Resolve an Issue in Key Categories

This Epic is to track the work for Goal #2 though Goal #1 may also improve in the process

##  Value Proposition 
Better track and understand support work so as to make actionable plans to decrease support ticket resolution time and tier 2 escalation.

## Impacted Objectives and Key Metrics (OKRs) 
Listed above in Goal section

## In Scope 
Analyzing current ticket categories, refactoring to fewer more descriptive new categories, getting resolution time data for old and new categories, coming up with a plan to lower resolution times where it would be impactful for new categories. 

## Out of Scope 
One support category is related to the formal onboarding process. This process has its own epic and initiatives for improving onboarding speed. A plan of action around onboarding would be out of scope. The other categories more tied to the performance of the support team are where we are focused here.

## Key Steps to Reaching Our Goal

- [x] Measure support ticket resolution time in all current categories over time
- [x] Consolidate down our current 20+ categories into a more manageable and meaningful set (ideally around 5 categories, no more than 10)
- [x] With new categories set, understand what we have done to lower the resolution time already and what more we can do 
- [x] Identify top categories we can make meaningful progress on, and if any categories can not be further improved flag them and explain why
- [ ] Get your strategy for reducing the top categories implemented at least 1 month before the end of the Quarter so we can hopefully see progress in time to plan for Q3

## Key Resources
- [Support Team box tracking the details of all categories ](https://app.box.com/s/5t5692yn9740p5m1citsgjt1d6fyni2g)(email exchanges)
- [Support Resolution Time Data Scatter Plots by Category](https://app.box.com/s/mnkmxbxrcjd8mcv9t802wh7vhnmpo8xz)
- [Google Sheets Raw Support Ticket Data](https://docs.google.com/spreadsheets/d/1OCZauG_VmsoTaMe54snu4NAvLLuNnPYnedRWeCpBnbg/edit?usp=sharing) with Analysis in the far right columns
- [Smartsheet version of raw ticket data](https://app.smartsheetgov.com/b/publish?EQBCT=a1e581bfdfd64955a26ee6c831180b4f)
- [Discovery notes doc](https://docs.google.com/document/d/1kC2b3Msen3H9t6MhUJzhXuoXhrJc_iQ4mJB3icYoSOc/edit#)

**Comment by sliu1000** [comment]
@brandonnava 
Please see the proposed new categories narrowed down to (10):  https://app.box.com/s/ovrhl3wa9dc5iizbg0esnbvvs2m15evo

Please review and provide feedback.

**Comment by lizzieamanning** [comment]
@brandonnava can you add details as you see them for these categories above:

Value Proposition 
Impacted Objectives and Key Metrics (OKRs) 
In Scope 
Out of Scope

**Comment by sliu1000** [comment]
@brandonnava @jakefishbein-navapbc - Please see the completed Recommendation Document https://app.box.com/s/bqhi4lcmqzy94vpca6tp0eivxpa9gp5c

**Comment by brandonnava** [comment]
Support resolution research complete with top categories to improve identified here: https://app.box.com/s/bqhi4lcmqzy94vpca6tp0eivxpa9gp5c
Next step is training the support team on top issues identified
