### ISSUE TITLE
Kentucky - Receiver Onboarding

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#9081]
### What You Need to Know 

- [ ] Kickoff meeting completed 
- [ ] Receiver intake form completed: [paste info below this] 

### To Do 

- [ ] create individual tickets for this epic 
- [ ] RS team member who originates this ticket: add any dependencies, as needed
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" 
     - [ ] Epics: [select the epic for this receiver we're onboarding]

**Comment by sliu1000** [comment]
Intake Form Reponses:
	 
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/9c8b0901-203b-4066-baf1-ed69a620d12c)

**Comment by TaneaY** [comment]
@LaFreda1 
Message from Courtney Marshall
Hi again,
I was able to speak to our HIE team and they would like to meet to discuss legal requirements with your team or someone from CDC’s legal team. This week is incredibly busy and we have a lot of staff out next week for conferences. Can we schedule this call including our HIE and whoever can answer legal questions on your end the week of May 15?

 

Thanks!

**Comment by LaFreda1** [comment]
Good morning Courtney,
Thank you for the update! I will discuss this request with the Report Stream team and follow up with a meeting invitation shortly.
