### ISSUE TITLE
Arkansas - Receiver Onboarding

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#9082]
### What You Need to Know 

- [x] Kickoff meeting completed 
- [x] Receiver intake form completed: [paste info below this] 

### To Do 

- [x] create individual tickets for this epic 
- [x] RS team member who originates this ticket: add any dependencies, as needed
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Receiver" 
     - [x] Epics: [select the epic for this receiver we're onboarding]

**Comment by GilmoreA6** [comment]
Closing epic as this work is completed
