### ISSUE TITLE
Puerto Rico - STLT onboarding 

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#9151]
### What You Need to Know 

- [ ] Terms of Service agreement signed 
- [x] Kickoff meeting completed 
- [x] Receiver intake form completed: 
![image](https://github.com/CDCgov/prime-reportstream/assets/86254221/876c3eed-4e86-4fa4-b13f-b00f081b6110)

### To Do 

- [x] create individual tickets for this epic 
- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by sliu1000** [comment]
Puerto Rico Completed their Intake Form:

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/59b0f826-9612-4ccc-8a90-ed908aded018)

**Comment by cloudmagic80** [comment]
We reviewed a private key from Puerto Rico but we need a public key instead. I am waiting on Puerto Rico. If they need assistance, I can get on a call with them to get the right key.

**Comment by cloudmagic80** [comment]
Update. Puerto Rico sent the public key file but ReportStream couldn't make a connection to PR's system. We will follow another approach where CDC sends them the public key.
Next steps are:

Send Elvis (Puerto Rico) public key
Elvis to create credentials for Donald
Assign the public key to those credentials so Donald can log into
Elvis to share credentials with Donald
Donald to create the yaml file in the format below and save in keybase.
Here is the basic format of the yaml file.

state: PR
sftp:
host: # the host name provided by the receiver
port: # the port to connect to
path: # provided by the receiver (the file path we write to)
userName: # provided by the receiver
password: # not used
ppkPassword: # the password generated above
ppkFileName: # the file name generated above
ppkFileContents: # the pub key file contents (or the putty file contents)

**Comment by cloudmagic80** [comment]
Connected successfully to Puerto Rico via ReportStream.
