### ISSUE TITLE
Universal Pipeline Condition Mapping

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#9177]
### User Story:
As ReportStream, I need to be able to determine what **condition** a _DiagnosticReport FHIR resource_ or _Condition FHIR resource_ relates to so receivers can easily filter on a condition or conditions.

### Description/Use Case
Presently, at least in the case of the California Flu pilot, receivers have to enter a long list of LOINC codes that are associated with the condition they are interested in and we filter on that via the condition filter. The main drawback of this method is that we have to manually manage the list of LOINC codes in the settings file, per receiver. So when a new test for a condition gets released we need to modify the setting file, which is unmanageable at scale. Even if we said "Okay, let's just start moving all LOINC codes to our LIVD table and map to conditions there", we still need to answer the following questions:
1. Where are we going to get all this information from? How do we keep it up-to-date?
2. Are LOINC codes enough? There are tests that use LDT instead

We need to have an **efficient** and **reliable** way to map test LOINC codes to the conditions they represent. Patricia has written up a [document detailing the intricacies of mapping codes in general (not just LOINC) to conditions](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Engineering/Condition%20Codes%20Research.docx?d=wf69d1be39e6b4524994d8a52b323ac67&csf=1&web=1&e=Q5nQ65). 

### Acceptance Criteria
- [x] Created an efficient, reliable, and maintainable method for mapping various codes found in ELR messages to conditions 
- [x] RS can route messages based on conditions
- [x] Condition routing/filtering is fully documented

**Comment by MauriceReeves-usds** [comment]
@GilmoreA6 I have some documentation and rough mapping from CSTE around condition mapping if you want to discuss this some more.

**Comment by bishoyayoub** [comment]
@LaFreda1 @brandonnava We have moved this epic over to Engagement.

**Comment by GilmoreA6** [comment]
Link to completed research document:

https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x0120004368ADED9C3BEA4B94E57C5781F119FF&id=%2Fteams%2FUSDSatCDC%2FShared%20Documents%2FPRIME%20ReportStream%2FDesign%20and%20Research%2FUniversal%20Pipeline&viewid=17db3ff6%2D95c5%2D4562%2Da1f3%2D12b5097b5947
