### ISSUE TITLE
Web receiver: content research and V2

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#929]
## Documents

- [Skylight-owned working doc](https://docs.google.com/document/d/1ofqy6G5ilavORJ-uIBn3_qqaZqc6EqWesvDbGgDuE30/edit#heading=h.lyhvt9fz49yr)
- CDC approval doc (link TBD after team review)
- ~
- [Content from James](https://drive.google.com/file/d/1DJUnoovHiJcLJrfjTpb61HvAV9pBHGKL/view?usp=sharing)
- [Style guide](https://docs.google.com/document/d/1re6dTgrY2kjY-E1rZHENh-1x0fs5voyyG9AWbEXWsbY/edit?usp=sharing)

## Todo

- [x] Initial V2 draft w/Skylight
- [x] Review
- [x] Research w/partners
- [x] Second draft
- [x] Team review (in progress)
- [x] CDC review & approval
