### ISSUE TITLE
South Dakota - Receiver Onboarding

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#9356]
### What You Need to Know 

- [ ] Terms of Service agreement signed 
- [x] Kickoff meeting completed 
- [x] Receiver intake form completed: 
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/56b234e3-eba3-49ce-8d14-ff0e23c014aa)
### To Do 

- [ ] create individual tickets for this epic 
- [ ] RS team member who originates this ticket: add any dependencies, as needed
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" 
     - [ ] Epics: [select the epic for this receiver we're onboarding]

**Comment by sliu1000** [comment]
Update from Receiver:

Jahnig, Lance <Lance.Jahnig@dsu.edu>
Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR);Burdick, Elizabeth <elizabeth.burdick@state.sd.us>
Shin, Donald (CDC/DDPHSS/OD) (CTR);lafredahoward@navapbc.com;Report Stream (CDC)

Sent connection via a secure link. Let me know if you have any problems with retrieving the file.

Lance Jahnig

**Comment by oslynn** [comment]
Sent and emailed:
Lance,

I sent sample file (covid-19-8eea6066-1dea-40f8-ae59-85f6d73255e7-20230510214600.hl7) to /Cert folder of your SFTP site.

Please validate the file and let me know the result.

Very respectful,
-Ott Sathngam

**Comment by oslynn** [comment]
SD can handle only a single message at a time.

Got it. The FHS and BTS need to be removed. We do not support batch files.
FHS|^~\&|CDC PRIME - Atlanta,|CDC PRIME - Atlanta,|||20230510214600
BHS|^~\&|CDC PRIME - Atlanta,|CDC PRIME - Atlanta,|||20230510214600
……..
BTS|1
FTS|1

**Comment by oslynn** [comment]
Turn the RS batch processing off and regenerate the sample file for SD:
Lance,

I reconfigured SD setting to send only one message at a time to you SFTP site. 
I send the new sample message file (covid-19-f104c035-5407-414d-aec0-ef48ce6166b2-20230511192801.hl7) to your SFTP root directory.
Would you please check, validate, and confirm the message that is what your system expect to see.

If everything is good for you, I will turn on SD production feed and SD will be in production.

Thank you very much for your help to make the onboarding goes smoothly.

Very respectfully,
-Ott Sathngam
CDC ReportStream Eng.

**Comment by oslynn** [comment]
@brick-green is going to take over from 2023-05-15 on ....

**Comment by sliu1000** [comment]
Check-In Notes with SD:

Met with SD today on 6/14/2023:
Attendance:
Elizabeth Burdick
Lance
Annie Bergman
John Shmulsky

Brick Green
Ott Sathngam
Sharon Liu


Done by South Dakota
-Validated the files we sent in
-SFTP credentials sent in

Can start pointing to the prod folder (next steps)

Annie - only reviewed positive test results that were sent.  Messages look great and have our stamp of approval to move to production.

Password Expires every 90 days (85 day password expiration reminder) - is that setup to go to the ReportStream Email (ask Ott)
Public Key Pair - wants it set up and test it (South Dakota) Can put that key in the SFTP folder (Please have us -Reportstream generate the key) into the root not the cert.

South Dakota - Positive only COVID
Back Log - we only create data for 60 days. Only want new data none of the old data please.

Before we onboard for other diseases - make sure to provide notification so they can test that data first.
Notify Lance when Ott puts the public key in the folder.
