### ISSUE TITLE
Final API Programmer's Guide Engineering Changes Pre-launch

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9579]
## Problem statement
Before launching the new web-based Programmer's Guide, we want to perform one final check to ensure that any bugs/enhancements that need to be fixed before rolling out the new Programmer's Guide are captured.

Additionally, since the API Programmer's Guide was built in sections in parallel, checking the internal reference links (that link within the pages/sections) could not be completed at review stage. Therefore, we need to check those links to ensure they are all working.

## What you need to know

- [New Programmer's Guide](https://reportstream.cdc.gov/resources/reportstream-api)

## Issue/Bug/Enhancement list
**Needed Before Launch/Roll-out:**

- [x] Side navigation: Remove subpage links & jumplinks from all of the sections, except for the Documentation section, see the [Figma](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?type=design&node-id=4812-37084&scaling=min-zoom&page-id=3592%3A36210&starting-point-node-id=4812%3A37084) for reference - JH
- [x] Side navigation: Too late to make the [side nav sticky as you scroll](https://www.figma.com/proto/6mwI5ac6rprACKDzDo4Ady/ReportStream-Workspace-%7C-2023?type=design&node-id=3592-36835&scaling=min-zoom&page-id=3592%3A36210&starting-point-node-id=4812%3A37084)? Can be future improvement if so - JH
  - Joseph Checking, may have to move out of MVP 
- [x] API Page and Documentation subpages: Has wider page/grid width than Getting Started and Documentation landing page
- [x] API Page: Card Links to Getting Started and Documentation (at top of page) link to non-existent pages
- [x] API Page: Download PDF link is broken - JH
- [x] Getting Started: Public key tool link is linking to the File Validator, should link to `https://reportstream.cdc.gov/resources/manage-public-key` - JH
- [x] API Page: "learn more" and "complete authentication" does not link to anything - AR
- [x] Getting started: Fake data file link does not work-AR
- [x] Getting started: Data model link in card box does not work -AR
- [x] Documentation: The "on this page" links do not correctly link  -AR
- [x] Documentation: All of the links in the sample payloads and outputs card do not work - AR
- [x] Getting Started: Above the file validator box, the new content is "When you’ve formatted your fake (non-PII) data file, test your data model using ReportStream’s file validation tool, and correct any errors you receive." You can see this change reflected in the [google doc](https://docs.google.com/document/d/1xsxkr7EnnpbXo8CcfdDcUnIYNKuFzY1u/edit#) as well (highlighted for easy reference right now).
- [x] Getting Started: Authentication section - Method 1, step 1, point 2 should now read the below content (You can see this change reflected in the [google doc](https://docs.google.com/document/d/1xsxkr7EnnpbXo8CcfdDcUnIYNKuFzY1u/edit#) as well - highlighted for easy reference right now).

> 2. Send the public key to the ReportStream team using our public key tool. Note: you’ll need to login to use that feature. If you do not have a login contact ReportStream support at reportstream@cdc.gov. ReportStream will associate the key with your configuration within ReportStream.
> 
> You only need to do this step once, not every time you submit reports. If you need to change your keys at any time, contact ReportStream support.

**Can Be Ticketed for future improvement:**
- [ ] All pages: Consistent vertical spacing between the nav and the page content/nav with the rest of the site (ex. the `product/overview`) - JH (added to #9688)
  - Difference exists for reason, needs review beyond MVP as a site-wide change. Will make a follow-on item post MVP. - CK and JA
- [ ] API Page: Comp match equidistant spacing between Getting started and Documentation cards, line rule, and Onboarding overview header (added to #9688)
- [ ] API Page: Make line rules thinner by ~.5x (Penny was also working on this on the Data Dashboard) -- this is the Horizontal Line thickness (should be thinner) (added to #9688)
- [ ] API Page: Replace alerts with Tip Callout component (used in File Validator & Public Key Tool, see Etan) (added to #9689)
- [ ] Getting Started Page: Comp match spacing between Data model card and following <p> (added to #9688)
- [ ] Getting Started Page: Comp match spacing between line rules and text (added to #9688)
- [ ] Documentation/Data page: Candidate for implementing sticky header (see Etan) (added to #9690)
- [ ] Getting started: We had notes that in the sample code snippets "healthy labs" was always styled blue, but one a couple instances are not blue -AR (added to #8941)

## Acceptance criteria
- [ ] All internal referencing links should be checked to ensure they are working properly.
- [ ] All issues/bugs/enhancements listed above are complete or ticketed for following sprints

## To do
- [x] Joseph to push main branch to trial front end after merging all existing PRs.
- [x] Design team to review newly deployed Programmer's Guide and note items that need changing before roll-out

**Comment by chris-kuryak** [comment]
@jillian-hammer The first line item:

> All pages: Consistent vertical spacing between the nav and the page content/nav with the rest of the site (ex. the product/overview) - JH

is the only one that we think should be a larger discussion (site-wide change). So we are going to roll that in to a follow-on improvement epic along with some of these other larger changes. Is that okay?

**Comment by jillian-hammer** [comment]
status: reviewed and left comments in [PR](https://github.com/CDCgov/prime-reportstream/pull/9656)
