### ISSUE TITLE
South Carolina - Receiver Onboarding

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#9610]
### What You Need to Know 

- [ ] Terms of Service agreement signed 
- [ ] Kickoff meeting completed 
- [ ] Receiver intake form completed: [paste info below this] 
-![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/b60eab12-4a9f-48e2-9b56-6e531aa0eadd)

### To Do 

- [ ] create individual tickets for this epic 
- [ ] RS team member who originates this ticket: add any dependencies, as needed
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" 
     - [ ] Epics: [select the epic for this receiver we're onboarding]

**Comment by oslynn** [comment]
Done
