### ISSUE TITLE
OK Onboarding Operations

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#974]
### What you Need to Know

The following items, generally in order, must be completed to successfully onboard a receiver to ReportStream:

* [ ] Added to organization.yml
* [ ] Added to organizations-local.yml
* [ ] Added to staging settings table
* [ ] Added to prod settings table
* [ ] Added at least one receiver
* [ ] Added OKTA group to download site
* [ ] Added customers to OKTA group for download site
* [ ] Is customer contact made?
* What doc format are we supporting for the receiver (HLV, CSV, other)? **(Add comment below)**
* What transport(s) are we supporting for the receiver (SFTP, other)? **(Add comment below)**
* [ ]  Got credentials?
* [ ] Tested ELR connection locally?
* [ ] Tested ELR connection from Azure?
* [ ] Has the receiver accessed the download site?
* [ ] Has the receiver been sent at least one test file?
* [ ] Has the receiver signed off on file formatting?
* [ ] Are there labs sending data?
* [ ] Has the receiver confirmed receipt of the data?
* [ ] Have the files processed successfully?
* [ ] Are we in production?

### To Do
- [ ] Please add individual tickets to this epic if you see that any are missing from the onboarding process - Thx, Berni

**Comment by sarahnw** [comment]
from OK (Lori Walker) 4/22
I’ve attached out API connection information. To set up the account, I’ll need the designated email address (can be a shared email, just need to be able to receive an email to reset the password) and preferred senderLabName to add the lab in our system.

 

Engineering:

·         Accept HL7 2.5.1

·         Sending protocol: REST API, see attached documentation

·         Accept HL7 batch messages, can come with or without batch headers

·         No batch limits

·         Batches every two hours is okay; can be daily batch

HL7:

·         MSH-5: OSDHMessaging^2.16.840.1.113883.3.1014.4^ISO

·         MSH-6: OSDH^2.16.840.1.113883.3.1014.4^ISO

·         Yes, please add name identifier in MSH-4.1 and CLIA number in MSH-4.2 (will also accept OID in 4.2)

·         Yes, we’ll receive AOE questions, if available

·         Yes, please suppress QST flag.

·         Require ordering facility name and address (street, city, state, and zip) and ordering provider last name and ordering provider phone number

·         MSH-21-1 = PHLabReport-NoAck

SFTP:

·         N/A

Data Quality Filters:

·         No, if a test is collected, tested, and read by an individual with no provider oversight they are not reportable in Oklahoma.

**Comment by brick-green-agile6** [comment]
@sarahnw Can you attach the "API connection information" that OK mentioned in their email?

**Comment by sarahnw** [comment]
[https://app.zenhub.com/files/304423150/e0aff630-34de-4425-a6d4-d2dd60ab1c65/download](https://app.zenhub.com/files/304423150/e0aff630-34de-4425-a6d4-d2dd60ab1c65/download)

oops - yes attached here!

**Comment by Adrian-Brewster** [comment]
@greene858 Tom is working on adding the organization and getting set up with the REST API. Going to push New York first, then Oklahoma.

**Comment by Adrian-Brewster** [comment]
@Adrian-Brewster to reach out and confirm REST API is the only transport option. sFTP please?!

**Comment by brick-green** [comment]
**HL7**
MSH-4.1: CDC PRIME REPORTSTREAM
MSH-4.2: 10DRPTSTRM
 
 
**HTTP Message Header**
SenderLabName: CDC PRIME REPORTSTREAM
SourceLabName: CDC PRIME REPORTSTREAM

**Comment by sarahnw** [comment]
@brick-green @greene858 I've converted this to an epic, please start adding individual tickets for what is left to do so we can start pointing and figuring out what's actually left!
