### ISSUE TITLE
Connecticut - Receiver Onboarding

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#9770]
### What You Need to Know 

- [ ] Terms of Service agreement signed 
- [x] Kickoff meeting completed 
- [ ] Receiver intake form completed: [paste info below this] 

### To Do 

- [x] create individual tickets for this epic 
- [ ] RS team member who originates this ticket: add any dependencies, as needed
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Receiver" 
     - [x] Epics: [select the epic for this receiver we're onboarding]

**Comment by sliu1000** [comment]
Notes from the Kickoff Call: https://docs.google.com/document/d/1DrnCBs55xCoFW_rYx2i_UsSV-0pLIIyKAEB-eTDsxMQ/edit

Action Items from the Kick-off call on 6/13/2023:

(1) Send Test Locations on data where the patient resides in CT.
(2) Send any documentation on setting up SFTP and/or Rest API (if available)

**Comment by LaFreda1** [comment]
CDC provided update to Glenn recently. Connecticut assumed they were connected to RS; we are waiting for them to reach out. If not, Glenn will reach out to them to get them connected

**Comment by MikaelahD13** [comment]
Closing, work completed.
