### ISSUE TITLE
Website updates & redesign v1

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9795]
## Definition of work
This work is to Design and Implement improvements to the ReportStream website so that it accurately reflects our current value proposition, messaging, and brand/styling. The majority of this research was performed in Q2, but as new UP-specific marketing and content becomes available during this epic, that content will be included.

## User value
- Improved user experience
- Better communication of our current offering and value proposition (to facilitate better user engagement)

## Linked dependencies
- None at this time, but some UP Content Marketing outcomes (Epic # TBD) will be included in these content updates if they are available.

## Outcome-oriented deliverable
- An updated ReportStream website that more accurately reflects our current offerings and value proposition

## Problem statement

The ReportStream website needs to be updated and redesigned to better serve our prospective and current users/partners. The WebX team has approached doing so from three concurrent bodies of work:
- **Content strategy:** Content audit of existing content showed that over 1/3 our current content could be edited for editorial consistency _(Related epic #8142)_; site-wide content updates are required to ensure our content is accurate and timely
- **Brand development:** Current website doesn't reflect the brand strategy messaging work in Q2 and will need to reflect the upcoming visual brand refresh in Q3 _(Related epic #9064)_; as the 'front page' of our product, the website needs to adapt the latest brand to introduce cohesion and consistency
- **Information architecture:** Current website has outgrown the simple current IA. Revised IA developed in response to user research (card sort) and upcoming content updates (full ELR) _(Related epic #9071)_; the website should be easy to navigate and find the information one needs

The website redesign is a culmination of these initiatives.

## Impacted Objectives and Key Metrics (OKRs) 
**O:** `TBD` pending Q3 OKRs
**KR:** `TBD` pending Q3 OKRs

## What you need to know

- Mural: [Q3 Roadmap](https://app.mural.co/t/nava4113/m/nava4113/1672323752891/18dba3187f29b396293271285034f988f4189801?sender=u0c3cdba5126734aceb613229)

**Related prior deliverables**
- Content strategy: [Content strategy proposal](https://docs.google.com/presentation/d/1Qa0Ek93niJZQWdHgQCl3LITHTh6_1wEXXAekNGHkh8U/edit)
- Branding: [Messaging summary](https://docs.google.com/presentation/d/16AnBMcWQFT4a8ZFMClOkA_VQttkwOhJfL3H0wpJhXYY/edit?usp=drive_link)
- IA: [IA research synthesis](https://docs.google.com/presentation/d/1d8GA7puc3IGCuHOiFgBUSCgGsCNYAhS3cVSr1OdNUkI/edit#slide=id.g21240411e1c_0_50)

## To do

- [x] Identify and align on website update priorities 
- [x] Assign design/content redesign/updates to specific sprints on roadmap
- [x] Write stub tickets for the rest of the quarter

**Comment by jillian-hammer** [comment]
hey all, took a pass at writing the redesign epic. @chris-kuryak can you take a look? ofc I could use some product insight re: the impacted Q3 OKR's, but feel free to revise throughout as you see fit.

cc tagging: @lizzieamanning @audreykwr @yudonoodles @Andrey-Glazkv for awareness

**Comment by lizzieamanning** [comment]
Looks good to me. Do we know enough to have an in scope/out of scope section? (i.e., for authenticated/non?) That could help

**Comment by chris-kuryak** [comment]
Let's wait until we have a clearer picture of scope/roadmap as for what we will be doing this quarter before solidifying this epic. Would like to see the synthesis work coming out of the existing sprint so we have a clearer picture of what we are looking doing moving forward.
I will work on the product documentation as well that will inform this epic.

**Comment by chris-kuryak** [comment]
Congrats to everyone who worked on this!
